### ISSUE TITLE
TmpFileDir -- Environment Variable Option

### ISSUE THREAD

**Issue by ikirker** [MRtrix3/mrtrix3#1033]
Disclaimer: I've not run MRtrix, I'm attempting to install and configure it for a user on a cluster I support.

Also disclaimer: I'm not that hot on C++.

Our cluster uses a setup whereby each batch job has its own allocated tmpfs temporary storage, whose path includes a numeric job ID.

This doesn't really work well with MRtrix's default of putting all temporary files into `/tmp` or a path set in a file in the user's home directory, since no two jobs, which could be running simultaneously, will have the same temporary storage path.

Would you accept a small change to `core/file/utils.h` that makes it accept either an MRtrix-specific environment variable, or a common environment variable to use for such things, `$TMPDIR`?

Something like (based on TmpFilePrefix):

```C++
      //CONF option: TmpFileDir
      //CONF default: `/tmp` (on Unix), `.` (on Windows)
      //CONF The prefix for temporary files (as used in pipelines). By default,
      //CONF these files get written to the current folder, which may cause
      //CONF performance issues when operating over distributed file systems. 
      //CONF In this case, it may be better to specify `/tmp/` here. Note that 
      //CONF this option can also be set using the `MRTRIX_TMPFILE_DIR`
      //CONF environment variable or the `TMPDIR` environment variable,
      //CONF without editing the config file. If both are set, 
      //CONF `MRTRIX_TMPFILE_DIR` takes precedence.

      const std::string __get_tmpfile_dir() {
            const char * from_env_specific = getenv("MRTRIX_TMPFILE_DIR");
            if (from_env_specific) return from_env_specific;
            const char * from_env_general = getenv("TMPDIR");
            if (from_env_general) return from_env_general;
            return File::Config::get ("TmpFileDir", 
#ifdef MRTRIX_WINDOWS
                  "."
#else
                  "/tmp"
#endif
                  );
      }
            
      const std::string& tmpfile_dir () {
            static const std::string __tmpfile_dir = __get_tmpfile_dir();
            return __tmpfile_dir;
      }
```

**Comment by ikirker** [comment]
Thinking about it a bit more, probably my best workaround at the moment is to add a symlink `tmpdir` from the batch job's working directory to the temporary storage and use something like `TmpFileDir: ./tmpdir`.

**Comment by jdtournier** [comment]
Sorry about the slow response - too many things on the go all at the same time. I've no particular issue with what you're suggesting, although it sounds like quite a niche set of circumstances... I've not come across this kind of setup, but it sounds like a good idea. Can I check whether the command itself executes within this job-specific tmpfs folder? If that's the case, you could probably get away with setting `TmpFileDir: .` to force it to store temporaries within the current folder, rather than a named absolute path like `/tmp`? Although that wouldn't prevent users from changing the current working directory to some other non-RAM-backed location (or even worse, a network-backed location), which would negate these benefits... 

Also, what is the problem with each job writing to `/tmp`? The temporary filenames are guaranteed unique, so there should be no conflict possible. If this is because you want to avoid [slowdowns related to forced write-back of dirty pages when handling large files](http://mrtrix.readthedocs.io/en/latest/troubleshooting/FAQ.html#linux-very-slow-performance-when-writing-large-images), then one other option is to create another dedicated `tmpfs` folder, and set the `TmpFileDir` location to that? It shouldn't matter that jobs share this location, or is this not possible in your setup?

**Comment by jdtournier** [comment]
By the way, if you do want to have these changes merged in, feel free to create a pull request for it. What you wrote seems fine to me, as far as I can tell it should work as-is (would obviously require some testing though... ). 

Not sure about allowing for `TMPDIR` though - it sound like it could introduce interference from other packages that may set this variable. Is there a convention around this variable? Otherwise I'd be inclined to stick with an _MRtrix_-specific one only...

**Comment by ikirker** [comment]
`TMPDIR` is specified in several UNIX specs, including the [POSIX standard][(http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03), and is respected by quite a few different things, especially the `mktemp` tool for creating disposable files and directories. I'd be happy either way, though.

Our batch job scheduler creates a new tmpfs for each job when it starts, with a size specified at submission, so that we can guarantee there's enough space to do whatever it is they need to do there. (Since jobs from multiple users can run on the same server, users would otherwise contend for storage with unpredictable results.) It's then unmounted by the scheduler's epilogue scripts at the end of the job. `/tmp` is a little more persistent than that, and automatically cleaning it up at the end of every job would involve deeply unpleasant book-keeping around what job created what file to avoid deleting files that are still in use. So, it's partly a reservation thing, and partly a clean-up thing.

I honestly haven't asked, but I would assume that people using MRtrix on our cluster are either running it from the temporary directory, which would allow `TmpFileDir: .` like you say, or from the Lustre parallel file system (probably more likely), which wouldn't. I'd assume that if they haven't read the docs for both MRtrix and our cluster setup they're running everything from the parallel filesystem and also using it for temporary files, which is probably terrible for performance. I can make recommendations to users as to whether to copy everything to the temporary storage before running if that's most appropriate, but that'll depend on how large the non-temporary files are, I guess.

In any case, I'm happy to submit a PR, but I'm not sure what kind of testing you'd want. Let me know about that and the variable choices and I'll put something together. No rush, though -- I know every season is a busy season. :)
