### ISSUE TITLE
computational requests not matched by commands

### ISSUE THREAD

**Issue by AlistairPerry** [MRtrix3/mrtrix3#1105]
I'm running into issues with the amount of cores allocated by mrtrix commands, does not actually match those specified by `nthreads` option.

In particular, when I run _tcksift2_ with:

`tcksift2 25M.tck wm.mif sift_weightfactor.txt -act r5TT.nii -fd_scale_gm -force -nthreads 8
`

I've set a watcher (see attached) which records the amount cpu's being used, as now indicated by the first column:

`911 tcksift2 25M.tck wm.mif sift_weightfactor.txt -act r5TT.nii -fd_scale_gm -force -nthreads 8
`

As you can see it's over the specified limit, and has been an issue I've encountered across multiple commands. This is a snapshot at each second, and so I've calculated all the instances where the cpu's are over-specified:

> [root@hpcnode040 ~]# awk '$3>=900' watcher.20170823.second | wc -l
> 2398 (about 40 minutes)

This issue could be data-dependent as the segmentations/co-registrations weren't entirely accurate, but nevertheless, this is sub-optimal when running on an institute-wide cluster. 

Just a few technical details:

>  CentOS 7 running kernel 3.10.0-327.3.1.el7.x86_64
>  File system is an nfs mount of an xfs file system
> 
> [root@hpcnode040 ~]# ldd $(which tcksift)
> linux-vdso.so.1 =>  (0x00007ffe8ff82000)
> libmrtrix-3.0_RC2.so => /software/mrtrix3/mrtrix3-20170815/bin/../lib/libmrtrix-3.0_RC2.so (0x00007f36b9141000)

Best,

Alistair
[watcher.20170823.second.txt.zip](https://github.com/MRtrix3/mrtrix3/files/1250810/watcher.20170823.second.txt.zip)

**Comment by CanWood** [comment]
Hi folks,

For those who are curious what you'll looking at with Alistair's attached [watcher.20170823.second.txt.zip](https://github.com/MRtrix3/mrtrix3/files/1250810/watcher.20170823.second.txt.zip), I was running the following on the host while the various mrtrix3 tools were running:
```bash
while [ 1 ]; do 
  ps -u alistaiP -o pid,ppid,pcpu,command -H |tee -a watcher.20170823.second
  sleep 1s
done
```
This way, once a second, we could see his process tree with full command lines, and cpu use of each process.  So any line in that attached file that includes `-nthreads 8`, that has a number higher than 800 in the third columns is an mrtrix3 tool that is using more threads than requested, if we've interpreted the docs correctly.

**Comment by jdtournier** [comment]
This is not unexpected - although I can see that it might be undesirable in certain circumstances... The reason is that `-nthreads` sets the number of _processor_ threads - those that do the heavy lifting. I'll try to clarify here. 

In commands that operate voxel-wise, this is exactly the number of threads you will get. Well actually, strictly speaking, `nthreads` _new_ threads will be launched, so the process will have an additional thread, with the main thread will sit idle waiting for the others to complete - [code here](https://github.com/MRtrix3/mrtrix3/blob/master/core/algo/threaded_loop.h#L348-L349)) - but CPU usage should nonetheless be as expected.

However, many tractography-related operations don't operate voxel-wise, so in this case we use a _pipeline_ framework, with first-in first-out queues serialising data between different stages. [Full docs here](http://www.mrtrix.org/developer-documentation/group__thread__queue.html#details) if you're interested. The process will normally request `nthreads` for the part of the pipeline that is expected to do the bulk of the work, with the other threads hopefully doing more lightweight duties and consequently spending most of their time idling. Clearly, this isn't always the case... 

So for instance, `tckgen` will run `nthreads` worker threads that generate streamlines, and one additional writer thread to serialise and buffer the data, then write it to file. You'll note in your data that `tckgen`'s CPU usage generally hovers around or below the expected 800% mark, but does max out at 816% - so sometimes the writer thread does seem to be working a little harder than usual. 

`tcksift2` is a different beast though... Looking at your data, most of the time, `tcksift2` consumes around 900% of the CPU - but at other points, CPU usage reaches over 1500%... e.g. here:
```
   PID   PPID %CPU COMMAND
 51366  67126 1515         tcksift2 25M.tck wm.mif sift_weightfactor.txt -act r5TT.nii -fd_scale_gm -force -nthreads 8
```
This could indeed come across as a little unexpected... There are of course very good reasons for this - @Lestropie will no doubt comment here. `tcksift2` runs different pipelines at different points in the code: it runs a [2-stage pipeline here](https://github.com/MRtrix3/mrtrix3/blob/b30ad75ca25938596eee1d8c70870b76384da611/src/dwi/tractography/SIFT2/tckfactor.cpp#L250) when estimating factors, but also a 3 stage pipeline before that when [mapping streamlines to fixels](https://github.com/MRtrix3/mrtrix3/blob/b30ad75ca25938596eee1d8c70870b76384da611/src/dwi/tractography/SIFT/model.h#L178-L183) - and this pipeline runs with `nthreads` for _both_ the middle and final stages... I guess this is because both stages are equally heavy, and depending on the input data, sometimes the middle stage dominates CPU usage, sometimes the final stage does - so to avoid idle CPU time, best to ensure both stages run with full CPU usage to pick up any slack. I'm actually surprised to find `tcksift2` manages to use the CPU so fully - this must be a rare case where the amount of work done in the two stages of the pipeline are well balanced (most of the time, one of the stages will idle quite a bit while the other works harder). 

However, this design is based on the assumption that the user is after maximum performance on a single-user system, where all CPU resources are available to the user and used to full capacity. I can appreciate that on a multi-user system, this might be undesirable. I'm not sure how strictly these limits are enforced on HPC systems, hopefully this doesn't lead to jobs actually being dropped due to exceeding their stated quota...? But as to how to 'fix' this, I'm not sure that we can do it without sacrificing performance for the more general user. It would be a shame to throttle back the process for users who can run at full CPU capacity (including HPC users if they're allowing to use individual nodes to capacity). Maybe @Lestropie has ideas about modifying `tcksift2` so that it honours `-nthreads` more exactly, but I have a feeling that can't be done without sacrificing performance so that the general case will run at much lower CPU usage than specified, or without some very deep modifications to the design of the code itself - neither of which are particularly desirable. I guess this all depends on how critical it is that _MRtrix3_ commands stick within the expected CPU usage...? Any thoughts & suggestions welcome...

**Comment by CanWood** [comment]
Thanks for the feedback.  Every HPC stack will have its own ways of either enforcing resource use, or simply taking advantage of the self reported expected resource use to schedule jobs on the appropriate hosts and allow them to run once there.  There's merits to capping resources and killing jobs that exceed their requests, but that can be a bit heavy handed.  In our environment, we prefer to work with the users to understand their tools and take advantage of their command line options to have the tools cap their own use.

As the documentation says that `-nthreads number use this number of threads in multi-threaded applications` our understanding was that would be its upper limit.  If a user wants to take full advantage of all available resources on a single user system, I'd expect that leaving the `-nthreads` off should give them that flexibility.

If there are stages that will use two times the `-nthreads` requested and others that will use three times, hopefully we can adapt to that by simply launching those tools or stages with the appropriate numbers dialled.  That said, I had a bit of a skim through the user docs and couldn't find any such indication.

Sorry for the confusion if we've misunderstood the use or purpose of the `-nthreads` parameter.  If it's meant as a threads per sample or threads per axis or threads per (insert other variable here), hopefully it'll be easy enough to navigate and adapt our command lines accordingly.

**Comment by Lestropie** [comment]
Yes, I'm guessing that I multi-threaded both the pipe and sink stages in the SIFT / SIFT2 streamline mapping because it would otherwise not use all available resources with the default invocation. However in this specific case, it should not be too difficult for me to produce a single functor that encapsulates both multi-threaded steps, and hence only require a two-stage pipeline and therefore more closely obey the requested resources. Note that this should also only affect the first ~ half of processing time, since it applies specifically to the streamline mapping process.

The other command where I'd expect you to observe this effect is `tckgen` when using the `-seed_dynamic` option, due to code [here](https://github.com/MRtrix3/mrtrix3/blob/b30ad75ca25938596eee1d8c70870b76384da611/src/dwi/tractography/tracking/exec.h#L94-L101). This one would be much harder to resolve in the implementation, as it's the only *four*-stage multi-threading pipeline in the software, the two multi-threaded stages are separated by a single-threaded stage, and many of the classes are shared with other parts of the library / `tckgen` code rather than dedicated to just providing dynamic seeding. So in that particular instance I'd suggest requesting half the number of threads actually desired if sharing the compute node.

In any other command though, the actual usage should not trickle much over the requested number of threads; while the actual number of threads may exceed the requested number due to the nature of the multi-threading pipeline design, those threads not doing the primary work should be idle for the majority of the time. If you've encountered any other examples where the usage is drastically higher than requested, please let us know here.

**Comment by CanWood** [comment]
Thanks!  We'll request that our users halve the ncpus in `tckgen -seed_dynamic` calls that run in the same HPC job as others, so they fit nicely in their workload.  If / when the changes are made to produce a single functor that encapsulates both multi-threaded steps, we'll fetch latest and retest.  We appreciate the explanation.

**Comment by Lestropie** [comment]
Closed by changes merged to `dev` in #1108.

**Comment by AlistairPerry** [comment]
Hello,

This issue has popped up again, as alerted from our cluster managers.

I'm running `dwishellmath` on single-shell data. I've placed a watcher to determine the amount of resources used - which is denoted by the first column.

```
0.0           /bin/bash /software/mrtrix3/mrtrix3-AP/bin/dwishellmath biascorr.mif mean meanshell.mif -force -nthreads 8
6346             dwiextract -shell 2999.44 biascorr.mif - -quiet
```

Where the top line is the parent command, and the bottom the subcommand.

Whilst `dwishellmath` is not a long-running process, you can imagine that this running over a number of subjects can be disadvantageous for cluster performance.

I'm currently on the dev branch, with a quick version check showing:

```
 == dwiextract 3.0_RC2-335-g14dd1ca1 ==
64 bit release version, built Dec  2 2017, using Eigen 3.2.7
```

Regards,

Alistair

**Comment by Lestropie** [comment]
[`dwishellmath`](https://github.com/MRtrix3/mrtrix3/blob/master/bin/dwishellmath) is a simple Bash script, and is not built on the *MRtrix3* Python libraries. Your `-force` and `-nthreads` options are being ignored entirely: The script literally never attempts to read anything beyond the first three command-line arguments.

As I mentioned in #692, it would be preferable for this and other Bash scripts to be ported to Python: Both so that they appear in the online documentation and have auto-generated help pages, and to prevent behaviour such as this.

**Comment by AlistairPerry** [comment]
Thanks @Lestropie,

Ill likely remove `dwishellmath` from my pipeline batching scripts for now.

Cheers,

Alistair
