### ISSUE TITLE
mrview: lightbox: fixel plot: inconsistent line thickness

### ISSUE THREAD

**Issue by rtabbara** [MRtrix3/mrtrix3#1140]
Fixel line thickness is inconsistent across all slices. Specifically, appears thickness changes are triggered by slices moving in and out of focus.

**Comment by thijsdhollander** [comment]
Just to add to clarify for others: this didn't only happen with fixels, but also with tractograms.  I was first starting to think it may have to do with slab thickness of tracks versus slice distance (increment) of the lightbox slices versus potentially the exact location of the focus (which isn't always the centre of the slice shown, so things may get complex with respect to (track) slab location versus slice location versus focus position).  Then again, that clearly didn't appear to be (at least the fundamental) the problem, since e.g. switching crop to slab completely off still showed things weirdly changing when clicking other lightbox panels, even though all panels *should* be showing the exact same full tractogram...  So well, let's see what #1142 gives. :slightly_smiling_face:

**Comment by rtabbara** [comment]
This is fixed in #1142
