### ISSUE TITLE
mrview: background mask image

### ISSUE THREAD

**Issue by rtabbara** [MRtrix3/mrtrix3#1141]
Possible feature request. Right now, setting the background colour isn't particularly helpful unless viewing a volume render. Might be helpful to allow a user to specify a background mask within the View options to allow a background colour to be tightly filled around a single slice?

**Comment by thijsdhollander** [comment]
Yep, I think this has come up before.  I think a lot of scenarios would already be covered if the "Thresholds" fields, and potentially even the "Transparency" fields (for added fun), where available in single slice mode, just as they are available in the volume render or even (single slice wise) for anything loaded in the overlay tool.

If the mask you're after is separate from that defined by a threshold on the main image itself (e.g. an independent brain mask), a manual trick I currently use myself it to overlay that independent mask via the overlay tool, and use the thresholds in the overlay tool to make the bit of the mask transparent where I want the main image to show.  Further trickery (potentially with inverting the colour map of that overlay) with the colour map of the overlay set to a custom colour allows to achieve the effect of a background colour for the "masked out" area.

Maybe we should write a docs page on "mrview hacks" or something. :smile: 

It may be good to show of some of these hidden tricks during our workshop as well. :wink: 

But yeah, back to the issue / feature request at hand here: what about already simply allowing the "Thresholds" fields for all viewing modes, rather than having them only limited to the volume render?

**Comment by rtabbara** [comment]
> Yep, I think this has come up before.

Yeah, you're [right](https://github.com/MRtrix3/mrtrix3/issues/241)..probably should have done an issue search beforehand :smile:

And I quote @jdtournier :

> ...only remaining issue was whether to enable the thresholds for non-volume render modes. Personally, I think they get in the way most of the time, and in the rare cases where you actually want a transparent background for your image, it's trivial to set those voxels to NaN independently and display that.

So I think I'll close this off for now &mdash; if there's any strong interest we can always reopen...
