### ISSUE TITLE
Store slice axes in header for subsequent mrdegibbs

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1173]
I was thinking it would be useful to store the slice axes in the mif header when importing from DICOM. This information can then be used to make sure `mrdegibbs` is using the correct slice axes, e.g. when processing data that was acquired with sagittal instead of axial slices. It could also be useful for other future commands that operate on acquisition slices.

**Comment by Lestropie** [comment]
Yes, I should ideally grab this for #1169 as well. I didn't bother at the time since `eddy` assumes `k` is the slice axis, but since it's applicable here too it's probably worth the effort.

**Comment by bjeurissen** [comment]
Definitely!

**Comment by Lestropie** [comment]
Initial attempt at capturing the data in eb447bc. No corresponding modification to `mrdegibbs` yet, and `dwipreproc` currently only does an error check (ideally it would permute axes if required so that the slice encoding direction is `k`, since `eddy` assumes that to be the case and doesn't offer a command-line input to change this).

Could also do with confirmation from @jdtournier that the approach / interpretation is correct. My understanding of DICOM is still somewhat limited.

**Comment by Lestropie** [comment]
Closed by #1175; will go out to `master` on next tag.
