### ISSUE TITLE
Incorrect version tag reported (RC1 instead of RC2)

### ISSUE THREAD

**Issue by ansk** [MRtrix3/mrtrix3#1223]
Dear experts,
my `mrtrix` binaries are reporting incorrect version tag (RC1 instead of RC2), despite building of master branch of most recent commit 7d68b748b8af1f078d4d1ffb3f1725bbdad92bb2 .
In my `build` script
`git describe --abbrev=0 --always`
is executed.
Looking to
https://stackoverflow.com/questions/4154485/git-describe-ignores-a-tag
adding `--tags` parameter is showing correct version:
```
git describe --abbrev=0 --always
3.0_RC1
git describe --abbrev=0 --always --tags
3.0_RC2
```
Antonin

**Comment by ansk** [comment]
I have encountered another problem with version reporting: Due to the fact that my most recent build of `mrview` (built against Qt5) does not work in my server with `vglrun` ( XCB error), I temporarily reverted `mrview` to version from August 2017 (built against Qt4), which was working with `vglrun`. Nevertheless, the reported git commit sha even for this older version is the most recent commit I built yesterday. When looking at `about MRView`, the build date is correct (August), when invoking `mrview -version`, build date is yesterday. Commit sha is wrong in both cases (pointing to yesterday build).

As a side note, rebuilding most recent commit against Qt4 resolved my primary issue - it is again working with `vglrun`.

**Comment by Lestropie** [comment]
I'd noticed some unusual behaviour here myself, though it's still unclear to me exactly what's going on.

Running `git pull --tags` before building also solves the problem; which suggests that our standard recommendation for people to update the software is somehow not pulling / resolving tag information.

The [`git describe` documentation](https://git-scm.com/docs/git-describe) suggests that the `--all` and `--tags` options are for enabling use of references other than annotated tags. But all of our tagged versions, including `3.0_RC2`, are annotated tags; hence I'm unsure why either of these options should be required in our case, or why adding these command-line options should fix the problem.

**Comment by Lestropie** [comment]
@jdtournier: Did we want to try to fix this for `3.0_RC3`?

**Comment by jdtournier** [comment]
OK, had a quick look into this, I don't think I'd wrapped my head around fully around this one at the time. There was a bunch of issues going on here, and I'm not sure they're all related. 

First off, it looks like the older mrview installation was still using the same version of the MRtrix3 library at runtime. Should be easy to verify by running `ldd $(which mrview)`. I would have thought that the settings we have in place (particularly the linker `rpath`) would have prevented that, but I'm not sure what would happen if for example `LD_LIBRARY_PATH` is set to point to the newer version's `lib` folder. In any case, the build date and version reported in mrview are the versions compiled into the library, whereas the version reported by the `-version` option uses the build date as reported by the `__DATE__` macro. I can't really figure out why they would differ, but maybe this was handled slightly differently in previous versions... 

Otherwise, I think you're right that we should suggest to use `git pull --tags` in the docs. I can't really find any detailed information as to how whether annotated tags get pulled by default, but it's best to assume they won't be. 

Hopefully that's all there was to these issues. The actual `git` calls are correct, as far as I can tell. I can't quite figure out why the version reported by `git describe` without `--tags` was out of date, but came good when `--tags` was added, if `master` was indeed the currently checked-out branch... That would suggest that `master` was out of date relative to the remote (GitHub) repo, maybe as a result of a `git fetch` without `git pull` on master itself? A quick `git status` should clarify...

But more broadly, the issues with `vglrun` once again suggest that there is something fishy with our OpenGL handling on Qt5. We'll need to look into this at some point, but I'd need a good clear week or two to really delve into that in detail again...

**Comment by jdtournier** [comment]
OK, just thinking about this some more:

- The tags issue should be dealt with by requesting users invoke `git pull --tags`. Pull request in #1332. 

- I think I know why the dates and SHA1 could come out so mismatched. The name of the shared library generated by the build contains the version tag (i.e. `lib/libmrtrix-3.0_RC2.so`). There's a faint chance that checking out an older tag means that the library that was built at the time remains as-is, and ends up being used. Not sure whether that's necessarily the problem... Nonetheless, it's made me think about whether we need to be versioning the libraries like this. I'd set that up way back when when we were using `ld.conf` (or `LD_LIBRARY_PATH`) to locate the libraries - means we could have different versions installed side-by-side, with different versions of the library installed in the same location. But now that we're using the `rpath` trick to locate the library, I can't think of any situation where we need to the library to be uniquely named. We could revert to a simple `libmrtrix.so`, which might avoid issues like that in future. Thoughts?

**Comment by jdtournier** [comment]
Solutions for the above proposed in #1332 - closing this issue.
