### ISSUE TITLE
Building my own machine

### ISSUE THREAD

**Issue by hackwave** [MRtrix3/mrtrix3#1253]
Hello, 

I'm building my own open source machine and I would like to interface with this project. Is there any interest in working on using this software to control a machine or is this purely for post measurement analysis on DICOM files?

**Comment by jdtournier** [comment]
Well, to be honest, I don't think any of us have ever thought about something like this... Part of the issue is that many of the processing steps that we have would be too computationally demanding for any form of real-time feedback. Do you have any specific use cases in mind where this would be good idea?

**Comment by jdtournier** [comment]
There's not been a great deal of activity on this issue... I'll close, feel free to re-open if necessary.
