### ISSUE TITLE
dwibiascorrect: De-mean

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1265]
Realised following [this forum post](http://community.mrtrix.org/t/mtnormalise-huge-variation/1509) that this issue hadn't been listed yet.

The N4 algorithm seems to not constrain the magnitude of the constant term of the estimated bias field. This can result in large fluctuations in global intensity scaling across subjects, probably proportional to the severity of the bias field and/or aggressiveness of field optimisation parameters.

Specifically for the `-ants` branch of `dwibiascorrect`, can compute the geometric mean of the scaling factor within the brain mask, and then explicitly subtract that term from the bias field before applying it to correct the DWIs.

**Comment by thijsdhollander** [comment]
Actually, we can also simply add the `-r` option to `N4BiasFieldCorrection`.  I thought I'd done that already at some point, but it seems I/we haven't, or it's been lost somewhere again.  `-r` will rescale to the min-max range of the original image within the mask.

For the record:

>  large fluctuations in global intensity scaling across subjects, probably proportional to the severity of the bias field and/or aggressiveness of field optimisation parameters

It's quite independent of that; it's quite hard to predict how the algorithm will drift, and in what "direction".  In principle, it can even drift "back and forth".  Essentially, the more iterations, the more opportunity there is to drift further away, but it's not necessarily a given.

**Comment by Lestropie** [comment]
> Actually, we can also simply add the `-r` option to `N4BiasFieldCorrection`.

Huh; I was quite sure I'd checked the command help page for such an option. Nevertheless: would it be better to constrain via the geometric mean, rather than the min/max? Requires a little more effort, but it intuitively seems more appropriate in terms of "conserving tissue volume".

> it's quite hard to predict how the algorithm will drift, and in what "direction"

Intuitively I'd have thought that number of iterations / granularity of field / any "regularisation" / any other optimisation parameters would all contribute to this, but I don't know the math behind it well or have a tremendous amount of experience with it. It's also an effect that's being noticed only more recently, so I figured the updated `dwibiascorrect` parameters might have made it more prominent; then again, maybe the effect was previously hiding behind `dwiintensitynorm` unnoticed.

**Comment by Lestropie** [comment]
Actually my original thought was just to get the integral of the input & output images within the brain mask, and use that ratio to scale the bias field. That's probably simpler to implement.

**Comment by thijsdhollander** [comment]
While I'm ok with the proposed approach (see pull request), just a note for future reference: even though I mentioned the `-r` option above, upon closer investigation, I'd actually stay way from that one (by all means).  I just realised the documentation of that actually says it rescales the output to the same min-max range... that's actually a weird (wrong) thing to do, since it'd introduce a _constant_ (in the _additive_ sense) as well as a factor.  I haven't tested whether is actually does this in practice, but the documentation is quite strict on it.  In principle, any approach that just rescales to the same "range" should only do a "zero-max" (i.e. just a "max") scaling, rather than a min-max one.

But well, no issues for an integral scaling; or any other scaling with is just a single factor.  I agree integral scaling is probably the simplest approach (to implement as well as compute); it's arbitrary up to some extent (I can think of other alternatives that are definitely not "the same"), but that's ok.  The purpose is not some kind of proper/sound normalisation, but just to limits the effects of algorithm drift.
