### ISSUE TITLE
mrtrix update

### ISSUE THREAD

**Issue by acamargofb** [MRtrix3/mrtrix3#1308]
Hi MRtrix3:

I would like to update my mrtrix, since I have a problem with mrinfo

mrinfo: unknown option "-export_grad_mrtrix"

Just in case the mrinfo version is:
mrinfo -version
mrinfo 0.2.12 (revision 410)
  Author: J-Donald Tournier (d.tournier@brain.org.au)
  Copyright 2008 Brain Research Institute, Melbourne, Australia
  using MRtrix 0.2.12, glib 2.48.2, GSL 2.1 (build Jan  1 2016)

Thanks a lot in advance for your answers,

Aldo Camargo

**Comment by maxpietsch** [comment]
Hello @acamargofb,

Assuming you are on linux, you can follow [these](http://mrtrix.readthedocs.io/en/latest/installation/linux_install.html) instructions. If you have further questions, please direct them to our community forum community.mrtrix.org/. You might want to wait a few days for our major upcoming RC3 update.

**Comment by jdtournier** [comment]
Just for completeness: you're using version 0.2.12 of MRtrix, presumably because it's already installed and listed in your PATH. You might find [this forum thread ](http://community.mrtrix.org/t/mrtrix-version-am-i-using/151/2?u=jdtournier)helpful. If that doesn't sort out the issue, then as @maxpietsch suggests, please use the forum for further assistance with this type of issue. :+1:

**Comment by acamargofb** [comment]
Thanks a lot for your quick answer :smiley:
