### ISSUE TITLE
fixelcfestats: Split functionalities

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1376]
From multiple requests, as well as for my own plans, want to split functionality across three commands:

- `fixelconnectivity`: Generate the fixel-fixel connectivity matrix, normalise / threshold, and save to file (need to determine an appropriate format).

- `fixelsmooth`: Smooth fixel-based data using both fixel-fixel connectivity and spatial proximity. Depending on the time required to re-load the fixel connectivity matrix into memory, may be preferable to input a text file containing paths to fixel data files, and smooth them all in one go, writing the result to a duplicate fixel directory, so that the matrix need only be loaded once per cohort.

- `fixelcfestats`: Take as input pre-smoothed data. Will also make interface more consistent with `mrclusterstats`, which expects pre-smoothed data.

**Comment by Lestropie** [comment]
An issue with this I came across when exporting fixel-fixel connectivity matrices for testing:

Even a thresholded matrix will typically still exceed 4GB, regardless of whether it is written in text form (easy: ~10 lines of code) or some kind of binary / compressed format. This would not be possible to write to a single contiguous file on a FAT32 file system (which has caused issues for some users with `tckgen` in the past). So this case would need to be caught & handled appropriately (ideally identifying the format of the output target file system and delivering a warning before matrix generation takes place).

**Comment by thijsdhollander** [comment]
> From multiple requests, as well as for my own plans, want to split functionality across three commands:

It would be good to detail what kind of requests (from how many people, for what purposes) and what plans this relates to; it'd need pretty solid justification to further "lengthen" the FBA pipeline (in terms of number of steps, as well as file (size) overhead that has to be generating during an FBA).

In any case, I'd still like the existing workflow (with only a _single_ `fixelcfestats` call) to be available: this still suits the intended purpose for a large number of users.  Many are already put off by the fact that the pipeline is so lengthy, so I'd avoid to lengthen it for those who don't need a more complex set up.

That said, if there's a genuine good justification and insight into these requests and plans, of course options can be *added* to `fixelcfestats` to allow for manual input of the connectivity matrix or pre-smoothed data (or, for the latter, an option to flag that the input is pre-smoothed).  So both kinds of users can easily be served by _extending_ the existing offering, without impacting on existing workflows.

**Comment by thijsdhollander** [comment]
> plan was always to have fixelcfestats input argument be either a track file (which infers smoothing hasn't been done yet) or a pre-computed matrix (which infers data are pre-smoothed, given a different matrix is typically used there)

:+1:  All good, if it were to be(come) like that.

**Comment by Lestropie** [comment]
While I have this working, the matrix load/save from/to disk is slower than I'd like; most of which I suspect is the number-to-string-to-number conversion. I've looked into sparse data storage formats but not really found any good advice / consensus.

Alternative would be to define a new *MRtrix3*-faithful format for such, with:

- Header containing magic ID string & key-value string pairs;

- Connectivity data stored using an integer-float pair for each fixel connection (width / endianness of both index and value types would need to be defined in the header);

- NaN & Inf indicating end of fixel & end of file respectively, as is done in the track file format.

**Comment by jdtournier** [comment]
I'm assuming you're using the Eigen market format at the moment...? I didn't realise it was text, doesn't sound great for us.

Couple of other suggestions:

1. Use our own fixel format: we just need to store one `uint32` for each connected fixel, and one `float32` for its corresponding connectivity value. Assuming the index image is at least a bit populated, it's already more efficient than storing both indices for each entry, I think.

2. Copy/paste the Eigen market reader/writer, and convert it to binary format, staying close to the original implementation. Advantage is it'd be a generic handler for binary sparse matrix storage, which we might even be able to contribute that right back to Eigen...

In both cases, I reckon it's worth having a good think about how the sparse matrix is repopulated. For our own dabbling with it, it's easy to write code that behaves really poorly for this, you want to do it in the right order, and pre-allocate beforehand to avoid needless and very costly resizes. This may entail multiple passes to figure out the allocation required. On that front, I reckon the fixel format might be advantageous, since the index image contains all the information you'd need for that - it would be a quick pass-though. 

But generally, I think if we decide to implement our own binary IO functions, we want to focus on something that is fast to read and write. Ideally, we want a zero-copy memory-mapped implementation. I think that can be done relatively easily, but would require a solid understanding of the way the data are stored in RAM. It's been a while, but I seem to recall there were two chunks to the structure (don't quote me on that, though!), which we could presumably simply dump to file as-is, and when opening again, all we'd need to do is memory-map the file and set the relevant pointers in the Eigen class to the right locations. It's likely to have a few other niggles though (particularly to avoid Eigen trying to deallocate on destruction), so you'd need to check it's feasible before diving in...

**Comment by Lestropie** [comment]
> I'm assuming you're using the Eigen market format at the moment...?

Nope, entirely custom code. Trouble with writing the matrix data to an Eigen structure in order to exploit I/O functions is that you may double up on memory usage. I suppose I could modify all of the code to use Eigen sparse matrices natively, but there wouldn't be much point, since:

> I didn't realise it was text, doesn't sound great for us.

Even though I'm not using it, the export function for this format is nevertheless text-based.

Eigen also deals natively in triplets, whereas using line number to correspond to row rather than explicitly storing the row index every time saves a decent amount of memory, and makes sense for how such data are eventually used in e.g. the CFE function.

> ... you want to do it in the right order, and pre-allocate beforehand to avoid needless and very costly resizes. This may entail multiple passes to figure out the allocation required.

Given the simplicity of using `std::vector`'s `shrink_to_fit()` function, I'd be tempted in this case to not have any kind of indication of number of elements per row; just read entries until you encounter a NaN, then shrink, and that's your row of data. Each resize is ultimately just a `memcpy()`, which should be reasonably fast. However:

> On that front, I reckon the fixel format might be advantageous, since the index image contains all the information you'd need for that - it would be a quick pass-though.

Hadn't thought of that. I suppose then there wouldn't be any need for end-of-row terminators either. Kind of weird to think that within a fixel directory, which contains a 4D index image, there would then be one or two connectivity matrices, probably each as its own directory, each of which would contain a 2D index image (for each fixel, need to know the number of elements, and the offset to the first element, for the row of the sparse matrix corresponding to that fixel).

One risk here is that at the generation step, if the output images can't be memory-mapped, then the memory requirements will double, since the matrix would need to be fully constructed & thresholded before the images on disk could be constructed. Well, I suppose you could do two passes in order to count the total number of connections, but it'd be pretty clunky, especially for exporting the fixel data smoothing matrix, where there's a bit more calculation involved in determining how many entries will be present per row. And the memory duplication issue still stands, unless `Image::dump_to_mrtrix_file()` is used.

Similar applies if loading a stored matrix from disk into local memory; unless all relevant code making use of fixel-fixel connectivity matrices were modified to operate directly on connectivity matrices that are stored in this format instead of on explicitly RAM-based representations, I suppose.

I'll let this idea simmer for a bit :+1:

I also need to test the current code on non-memory-mapped storage to see to what extent that's contributing; but such storage is probably pretty common in environments where these functionalities are used, so even if it turns out to be faster it's maybe not a "fix".

**Comment by Lestropie** [comment]
Closed by #1543; redirecting any further discussion / developments regarding the format for fixel-fixel connectivity matrix storage to #1604 since the functionality originally described in this issue is now met.
