### ISSUE TITLE
./configure -static fails with traceback

### ISSUE THREAD

**Issue by tutufan** [MRtrix3/mrtrix3#1390]
Despite the documentation, the `-static` flag seem not to work (at least in RC3).
```
./configure -static -nogui
Traceback (most recent call last):
  File "./configure", line 231, in <module>
    if noshared: build_options.application ('noshared')
AttributeError: 'list' object has no attribute 'application'
```

**Comment by Lestropie** [comment]
Hi Michael,

That one in particular was reported in #1339 and fixed in #1340; however while the hotfix is on `master`, it came after the `3.0_RC3` tag. So if you're determined to get a static compilation, you'll need to check out a version of the code that includes the fix. We've lately tended to move away from static compilation in favour of other solutions, which is probably how the mistake crept in there unnoticed in the first place.

Rob

**Comment by tutufan** [comment]
Thanks Rob.  No, I'd definitely prefer _not_ to use a static build--I was just grasping for any way at all to get it built on our system (RHEL 7.5 plus gcc 7.3).  After a lot of hacking about, I discovered that the configure/build scripts' rewriting of `-I` compiler flags to `-isystem` was triggering an obscure GCC bug.

**Comment by Lestropie** [comment]
Interesting: I've had issues myself in the past with `-isystem`, but was under the impression that it was something specific to Windows. Are there any pages you can provide a link to describing the bug?

**Comment by jdtournier** [comment]
> I was just grasping for any way at all to get it built on our system (RHEL 7.5 plus gcc 7.3)

I've had to do this once, and vowed never to do it again... RHEL is simply not designed for scientific computing, it's difficult to get many of the dependencies installed. I feel your pain.

> After a lot of hacking about, I discovered that the configure/build scripts' rewriting of `-I` compiler flags to `-isystem` was triggering an obscure GCC bug.

This is something you could probably get rid of if necessary - it's only there to prevent warnings from external headers that don't relate to our code as such. There was a time when the output of `./build` was full of compiler warnings from Eigen, which made it very difficult to identify warnings that we could actually do something about. Unfortunately, the `pkg-config` file shipped with Eigen uses a `-I` flag, which is why I'd resorted to modifying that in our scripts. You'd just need to [get rid of these lines](https://github.com/MRtrix3/mrtrix3/blob/master/configure#L526-L528), and maybe [these lines too](https://github.com/MRtrix3/mrtrix3/blob/master/configure#L1192-L1194) if the problem occurs with the Qt step. 

However, in my experience, the issue with that translation often relates to some weird issue with the output of `pkg-config` using a different (multi-byte) character encoding than expected, which causes all kinds of weird effects, including messing up the translation of these flags. Might be worth looking into whether that might be the issue here. Unfortunately, I've never managed to fully put my finger on it, much less come up with a foolproof solution...

**Comment by jdtournier** [comment]
A couple of links to relevant posts regarding the `pkg-config` issue:

http://community.mrtrix.org/t/error-running-configure/417/2?u=jdtournier
http://community.mrtrix.org/t/mac-el-capitan-problem-with-configure-the-mrtrix-install/274/21?u=jdtournier

**Comment by tutufan** [comment]
I called the `-isystem` behavior a bug above, but looking more, I guess it's technically not.  See these links:

https://stackoverflow.com/questions/37218953/isystem-on-a-system-include-directory-causes-errors
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

Anyway, I blocked the translation of `-I` to `-isystem`, and for me that seemed to fix the problem with no apparent ill effects.

**Comment by tutufan** [comment]
@jdtournier : Yeah, I'm not a super RHEL fan necessarily.  But some things just have to be dealt with.

**Comment by Lestropie** [comment]
I'd hoped that Eigen would have sorted the compiler warning problem and we'd now be able to revert back to `-I` to avoid this kind of issue, but the problem's still there on the newest Eigen version in MSYS2 (`3.3.4-1`). Version `3.3.5` was released two days ago, and that removes some of the compilation warnings but not all.

Maybe one mitigation would be to restrict the translation of `-I` to `-isystem ` in `configure` specifically to Eigen, and retain `-I` for all other includes? Certainly the two links provided above suggest that use of `-isystem` for suppressing compiler warnings is naive and can lead to precisely the kind of issue reported here; but I'd think Eigen is less likely to encounter system include header ordering issues than e.g. core gcc libraries.

**Comment by jdtournier** [comment]
I'd also rather not modify the flags reported by `pkg-config` - presumably the developers suggest these flags for good reasons. One way around this might be to use [GCC diagnostic pragmas](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html)? This might look something like:
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wformat" // or whatever the relevant error is
#include <Eigen/XYZ>
#pragma GCC diagnostic pop
```
This would get rid of 99% of the problems we face. We could also suppress these other warnings we get with the `abs()` calls - we'd just need to enclose the code that produces the warnings in the relevant pragmas, in the same way. I expect `clang` will honour these pragmas, since they aim for 100% compatibility with GCC. What do you reckon?
