### ISSUE TITLE
Debian 8.0 i386 build failure

### ISSUE THREAD

**Issue by yarikoptic** [MRtrix3/mrtrix3#1448]
```
g++ -c -std=c++11 -DMRTRIX_BUILD_TYPE="release version with openmp" -pthread -fPIC -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DEIGEN_FFTW_DEFAULT -fopenmp -Wall -O3 -DNDEBUG -Isrc -I./core -Icmd -isystem /usr/include/eigen3 core/formats/mgz.cpp -o tmp/core/formats/mgz.o

failed with output

In file included from core/formats/mgz.cpp:19:0:
./core/file/mgh.h: In function 'void MR::File::MGH::write_header(const MR::Header&, Output&) [with Output = std::basic_ostringstream<char>]':
./core/file/mgh.h:607:9: internal compiler error: in gen_rtx_SUBREG, at emit-rtl.c:748
         }
         ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccKlJOFj.out file, please attach this to your bugreport.
505) [CC] tmp/cmd/shconv.o
(208/505) [CC] tmp/src/gui/dwi/renderer.o
```
not sure if/what would be any fix/workaround, or either it should be attempted at all, feel free to close ;-) just reporting for completness - doesn't happen  on other builds or on amd64

**Comment by Lestropie** [comment]
Are you able to re-attempt compilation with a newer version of `gcc`? The [top Google hit](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64424) suggests that this may have since been fixed. I've often been tempted to increase the documented `gcc` minimum requirements to >= 5.0.

Additionally, try monitoring the RAM usage of the compiler process: it's possible that performing a 32-bit compilation is running into an address space issue; though admittedly this usually happens with a few select `cmd/` files, not header files.

**Comment by jdtournier** [comment]
Just to add my 2 cents: I haven't built a 32-bit version for years, and my guess is it should be strongly discouraged nowadays. You really can't do very much of any value on 32 bit system these days... There's no reason to remove 32 bit support at this point, since everything works as expected. But I'd be happy to simply phase out 32 bit support: there really isn't much of an incentive to fix this, and it's diminishing by the day...
