### ISSUE TITLE
dwipreproc should set OMP_NUM_THREADS

### ISSUE THREAD

**Issue by chrisadamsonmcri** [MRtrix3/mrtrix3#1479]
dwipreproc should set OMP_NUM_THREADS from the nthreads option to pass through to eddy_openmp

**Comment by jdtournier** [comment]
Good suggestion - although I'd advocate only setting it if `-nthread` is explicitly passed (which I think is what you're suggesting anyway). It might be worth also setting it to the detected concurrency capability of the system if it is currently unset. But if it's already set, it should be left alone (unless over-ridden with `-nthread`.

**Comment by Lestropie** [comment]
Not 100% sold on this. The [current description](https://github.com/MRtrix3/mrtrix3/blob/master/lib/mrtrix3/app.py#L406) for the `-nthreads` option clearly states that it only propagates this setting to *MRtrix3* multi-threaded applications. Just as `-nthreads` can be set at the command-line for an individual command invocation, `OMP_NUM_THREADS` can be equivalently set, and it is extremely clear in that instance what parameter is being set. 

For instance, if one were to run:
```
OMP_NUM_THREADS=4 dwipreproc -nthreads 8 ...
```
, should `eddy` use 4 or 8 threads?

What about if "`export OMP_NUM_THREADS=4`" appeared in the user's `bashrc` file, and they then run:
```
dwipreproc -nthreads 8 ...
```
?

It seems to me that in the first example, `eddy` using 4 threads makes more sense, whereas in the latter, 8 threads seems intuitive. Yet it's impossible to distinguish between the two within the code.

If the scope of the `-nthreads` option were to extend beyond only controlling *MRtrix3* applications, and this were to be a part of the script application library itself, it would become reasonable to expect that *any* command executed within any script written against the Python library will have its number of threads limited, regardless of the multi-threading mechanism underlying that command; but that could never logically be an exhaustive list / capability.

The alternative to this would be that the setting of `OMP_NUM_THREADS` based on use of the `-nthreads` option would be a *dedicated feature* within `dwipreproc` for the sake of `eddy` execution *only*.

Not 100% against it either, I just don't think it's totally unambiguous.

**Comment by chrisadamsonmcri** [comment]
If you specify a number of threads for the mrtrix code why would you want eddy to use a different number of threads? It would make sense that the user wants ALL processes within dwipreproc to use the number of threads specified. Under a grid scenario, for example, this is important since you reserve a number of threads to begin with and you want all processes to only use that many threads. Exporting OMP_NUM_THREADS in dwipreproc will not override user defaults elsewhere.

**Comment by Lestropie** [comment]
The important point is this one:

> Exporting `OMP_NUM_THREADS` in `dwipreproc` will not override user defaults elsewhere.

You are talking here about over-riding this environment variable *specifically* within `dwipreproc`, as opposed to being a generic operation that is performed by the *MRtrix3* Python script application library that would hence apply both in `dwipreproc` and any other conceivable script written using this library.

That's certainly possible. Though the `-nthreads` option is not specific to `dwipreproc` but is present in all other scripts as well; so it would require some hacking to modify the description of this command-line option only within the `dwipreproc` help page so that the description appropriately reflects this behaviour.

My point above was that ambiguous usage / behaviour is *possible*, and therefore a completely generic solution (i.e. extending beyond `dwipreproc` & `eddy`) would be problematic.

**Comment by thijsdhollander** [comment]
> For instance, if one were to run:
>> OMP_NUM_THREADS=4 dwipreproc -nthreads 8 ...

> It seems to me that in the first example, eddy using 4 threads makes more sense,

Not sure about this one; personally, my first interpretation there would've been 8, to be honest: the last / most recent command there is very explicitly asking for 8, so personally, I wouldn't be surprised at all that it "overrides" the former.  In the end, this just comes down to how `-nthreads` is documented.  I think @jdtournier's description above could be a very good one; just the sheer fact that it can be summarised so briefly, makes it very simple and easy to understand; rather than a more technical maze to navigate.  Just stating that it "simply over-rides" is as simple as it gets.
Relatively exotic scenarios like the above example should probably not drive the definition of the default behaviour, I reckon... if someone's running something like that, they're probably going to be the people who read the documentation to check what's exactly going to happen in that scenario.  They're probably also the people who can, as a last resort, even go in and modify the code if they're really specific about getting a particular behaviour...

> If the scope of the -nthreads option were to extend beyond only controlling MRtrix3 applications, and this were to be a part of the script application library itself, it would become reasonable to expect that any command executed within any script written against the Python library will have its number of threads limited, regardless of the multi-threading mechanism underlying that command; but that could never logically be an exhaustive list / capability.

True, but it can be "as much as possible".  All it takes is to add something to the documentation to state that this isn't universally *guaranteed*, and it's partially up to the developer of each individual script to take care of this.  At least we can make it so for those scripts that we currently provide.  Even though he used a specific example to describe his point, I think we can learn from this user's expectations here:

> If you specify a number of threads for the mrtrix code why would you want eddy to use a different number of threads? It would make sense that the user wants ALL processes within dwipreproc to use the number of threads specified. Under a grid scenario, for example, this is important since you reserve a number of threads to begin with and you want all processes to only use that many threads.

@chrisadamsonmcri can probably clarify; but I suppose he wasn't targeting `dwipreproc` in particular (but it was just the one he encountered the issue with)...?

**Comment by chrisadamsonmcri** [comment]
Eddy is the only external application I have encountered the problem with. I believe there are some other scripts that use external tools like ants and N4. That would require setting ITK_GLOBAL_NUMBER_OF_THREADS to -nthreads. Since you know which external applications you are using it is possible to exhaustively put in code lines to set environment variables/commandline options specifically for each external command so that the nthreads value is propagated. I just can’t imagine a scenario where you would want variable thread counts between processes.

My expectation is that if I run a mrtrix script and say I want a certain number of threads then all processes under that script should use that many threads.

**Comment by Lestropie** [comment]
> Since you know which external applications you are using ...

The Python scripting library is intended to be functional beyond just those scripts provided as part of *MRtrix3*, and beyond just the *MRtrix3* developers; but the requested capability is most logically integrated deep into the library rather than being dealt with on a per-script / per-command basis. My concern is that I don't know the full set of all possible mechanisms by which any command that could conceivably be executed within any conceivable script built against this library may control its number of threads, and hence such a capability can never be "complete". But probably just reflecting this uncertainty in the description of the `-nthreads` option would be sufficient.

**Comment by Lestropie** [comment]
Yes, a specific comment could be added within `dwipreproc` that use of `-nthreads` will override the `OMP_NUM_THREADS` environment variable in order to influence `eddy`.

**Comment by soichih** [comment]
I am not sure if it's related to this, but we are seeing eddy_openmp exceeding the number of -nthreads that we are passing in (see https://github.com/brain-life/app-mrtrix3-preproc/issues/10) 

For example, we are passing -nthreads 8, but the actual CPU usage is exceeding 1500%.  Do I need to set OMP_NUM_THREADS as well as -nthreads? 

We are running dwipreproc like this..

```
NCORE=8
dwipreproc -eddy_options " --repol --data_is_shelled --slm=linear" -rpe_none -pe_dir $ACQD ${difm}.mif ${difm}_eddy.mif -tempdir ./tmp -nthreads $NCORE 
```

Do I need to explicitly set some extra option if we are specifying -eddy_options?

**Comment by Lestropie** [comment]
> Do I need to set OMP_NUM_THREADS as well as -nthreads?

While fc8f3b41e sets `OMP_NUM_THREADS` based on the `-nthreads` option, that commit has not yet made its way onto the `master` branch. So until that happens, yes, `eddy`'s multi-threading operation needs to be handled separately to that of invoked *MRtrix3* commands.
