### ISSUE TITLE
mrtransform: modulate non-FOD data sets

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1484]
At the moment, the `-modulate` option can only be used for FODs. Performing modulation of scalar images (e.g. for VBA) requires users to get the determinants of the Jacobians of the deformation field and then applying those in the correct way to the image intensities, leaving a lot of room for error. It would be very useful just to support the `-modulate` option for both FODs and (series of) scalar images. This would require an explicit option to signal that the dataset should be interpreted as FODs in addition to a generic `-modulate` option.

**Comment by bjeurissen** [comment]
Any suggestions on how to approach this? Currently the modulation seems to be completely tied to the reorientation. Any ideas @maxpietsch?

**Comment by maxpietsch** [comment]
Sorry, I am not familiar with the modulation code. Interface-wise: Modulation means different things depending on whether one refers to fibre ODFs (scale so that fibre density is constant across fibre bundle) or scalar images (scale with local volume change). I think the two are equivalent for spherical ODFs but I am not sure if it would be a good idea to choose which to perform, depending on the `-reorient` option. We could make it explicit via `-modulate fc` and `-modulate jac` though?

**Comment by Lestropie** [comment]
> I think the two are equivalent for spherical ODFs ...

I'd have thought it *wouldn't* be: E.g. If you have compression in all 3 spatial dimensions, a scalar image modulated by the full Jacobian is going to incorporate all 3 factors, whereas a spherical ODF using "FOD modulation" would effectively "regress out" the expansion along the direction of the aPSF independently for each, resulting in the latter version not being scaled to the same magnitude as the former. So the more explicit version may be necessary.

**Comment by jdtournier** [comment]
> If you have compression in all 3 spatial dimensions, a scalar image modulated by the full Jacobian is going to incorporate all 3 factors, whereas a spherical ODF using "FOD modulation" would effectively "regress out" the expansion along the direction of the aPSF independently for each, resulting in the latter version not being scaled to the same magnitude as the former. 

I'm not sure, I have a feeling that ought to give (approximately) the right answer...?

But more to the point, if it's using the full aPSF backend to do the modulation on a scalar image, rather than simply modulating by the determinant of the Jacobian (I hope I've got that right...?), that alone is reason enough to change it...

**Comment by maxpietsch** [comment]
@Lestropie was correct, FOD modulation is different from that using the Jacobian determinant: I tested it on spherical ODFs for non-directional spatial scaling with aPSF reorientation using 6000 directions. The relative difference in intensity between FOD and Jac modulation is the cube root of the Jacobian determinant.
