### ISSUE TITLE
mrtransform: disable implicit FOD reorientation

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1485]
`mrtransform` currently performs FOD reorientation by default if the number of volumes indicates that the series can be interpreted as a series of SH coefficients. This is quite a dangerous practice as it could silently mess up pipelines, e.g. if input data happens to have a number of gradient orientations that corresponds to a number that can be interpreted as a series of SH coefficients. So I feel it would be a safer option to disable FOD reorientation by default.

**Comment by Lestropie** [comment]
Just to add to this: I suspect FOD reorientation was turned on by default at the time because this was perceived at the time to be the most common usage. However with the current FBA pipeline reorientation actually has to be turned off explicitly at the transformation stage, as this is instead deferred to `fixelreorient`. So having this off by default and instead activated explicitly within `population_template` would actually be simpler usage for users.

**Comment by maxpietsch** [comment]
Agreed, it makes sense to change this behaviour. I am just concerned that changing this might silently trip off scripts that implicit relied on FOD reorientation. This is a source of error that is hard to detect. The safest approach would be to rais an error if the number of volumes indicates an SH file and the orientation option is not provided.

**Comment by thijsdhollander** [comment]
It let this idea sink a bit in: initially, I was feeling quite opposed to it, because of the initial problems and confusion this could again unleash upon users of the FBA pipeline.  The biggest problems (every time) being that, once this release would go out, the online docs get updated, but that doesn't mean users update their install; yet they still use the (new) documentation they find online.
So in this case, that would've meant: in the online docs, the `-noreorient` option disappears, causing copy-pasting users to not specify it any more.  But if they're still using a previous version, that would mean they do end up reorienting.  ...and then another time at the fixel stage.  So 2 reorientations, which is obviously wrong.

...but now I believe @maxpietsch's proposal should guard against it (so I do like that one): simply require users being explicit on what needs to happen in case of those particular numbers of volumes that match SH series.  I'd call it `-reorient_fod` though, to avoid the impression that it's the right thing to do for anything represented in the SH basis (e.g. an SH fit of the signal or something).  I wouldn't actually even relax it towards the future; while the premise of Ben's initial suggestion is that users would naturally expect no reorientation to happen, I'm not so sure of that myself (at all).  As we discussed while writing the paper, the main functionality of our registration code (at the moment), and thus the tools that go with it in MRtrix (such as this one) is still FOD registration.  The most natural thing in general I'd expect to happen when transforming my FOD images with MRtrix (which is backed by reorientation functionalities for FODs), is for those FOD images to be properly reoriented.  So well: different users, different expectations, I reckon.  This calls for forcing them to be explicit, I'd say.

**Comment by maxpietsch** [comment]
> I'd call it `-reorient_fod` though, to avoid the impression that it's the right thing to do for anything represented in the SH basis

Everyone ok with a command option `-reorient_fod bool` that becomes mandatory if the number of volumes matches that of an SH image?

**Comment by Lestropie** [comment]
It would need to be SH with lmax >= 2: XxYxZx1 will pass `Math::SH::check()`.

Another factor to consider is behaviour if this option is specified but input is not a valid SH image... ignored but with a warning level message?

**Comment by jdtournier** [comment]
I assume #1484 is relevant to this discussion...?

**Comment by maxpietsch** [comment]
> I assume #1484 is relevant to this discussion...?

I see them as related (for FODs) but separate options as the modulation with the Jacobian determinant also applies to other non-FOD applications. I think the choice of whether to reorient an SH image should be independent of intensity modulation and vice versa and I would tend to force the user to be explicit about both choices.

> Another factor to consider is behaviour if this option is specified but input is not a valid SH image... ignored but with a warning level message?

I'd say it warrants an error. On the other hand, I'd probably issue a warning when a user modulates a suspected FOD image with the jacobian instead of using the aPSF modulation.

```
# sh.mif: lmax>=2, scalar.mif: number of volumes not in [6, 15, 28, 45, ...]
mrtransform sh.mif -reorient_fod true ...  #  reorientation only
mrtransform sh.mif  ...  #  error: missing option -reorient_fod
mrtransform scalar.mif ...  #  fine
mrtransform scalar.mif -reorient_fod true ...  #  error

mrtransform sh.mif -reorient_fod true -modulate fod ... #  reorientation and aPSF modulation
mrtransform sh.mif -reorient_fod true -modulate jac ... #  reorientation and jacobian modulation, warning
mrtransform sh.mif -reorient_fod false -modulate jac ... #  jacobian modulation, warning
```
