### ISSUE TITLE
dwipreproc explicit volume recombination

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1493]
https://github.com/MRtrix3/mrtrix3/blob/16090b5b4ccdad9652bada2473e904ecfc64c047/bin/dwipreproc#L996

translates to

```
mrcalc field_map.nii.gz 0.123 -mult - | mrfilter - gradient - | mrconvert - field_deriv_pe_1.mif -coord 3 1 -axes 0,1,2
```
causing

```
mrcalc: [100%] uncompressing image "field_map.nii.gz"
mrcalc: [100%] computing: (field_map.nii.gz * 0.123)
mrfilter: [100%] applying smoothing prior to calculating gradient
mrfilter: [100%] applying gradient filter to image -
mrconvert: [ERROR] omitted axis "4" has dimension greater than 1
```
when performing explicit volume recombination

field_map.nii.gz is 4D containing 6 volumes
after mrfilter this becomes 5D containing 3 x 6 volumes
subsequent mrconvert then fails when trying to omit a non-singleton dimension

**Comment by bjeurissen** [comment]
Problem seems to be that field_map.nii.gz should not be 4D. Is a change that was introduced in FSL 6.0?

**Comment by jdtournier** [comment]
For reference: [problem was reported on the forum](http://community.mrtrix.org/t/omitted-axis-4-error-in-dwipreproc-of-siemens-vida-xa11a-data/2019/6?u=jdtournier) - I should have created an issue for it, my apologies...

> Problem seems to be that field_map.nii.gz should not be 4D. Is a change that was introduced in FSL 6.0?

As far as I can tell, yes. I'm not sure what the best way to handle this is. I assume the simplest would be to detect whether the field is 4D in the script, and if so extract the first volume?

> Related to this: should we even perform recombination? 

@Lestropie would be better placed to comment on that, but as far as I can tell, this only happens when the `-rpe_all` option is provided. In this case, if we _don't_ recombine, I don't see how that would differ from `-rpe_header` - with the exception that the latter requires that the PE information is already in the headers, while the `-rpe_all` option doesn't need that since it expects a particular organisation of the data. On that basis, I can see your point...

**Comment by Lestropie** [comment]
`topup` field map output being 4D appears to be related to FSL6. I don't have a working copy of this yet so have not updated `dwipreproc` to suit. I don't want to make code changes whilst only assuming that the data are of a particular format.

Jesper's comment referenced there specifically is about use of `eddy_combine`, which does a basic averaging of phase encode reversed pairs. I've also seen criticisms of the least-squares reconstruction for such within `eddy`, as it can result in ringing artifacts. The volume pair recombination performed in `dwipreproc` is different again as it is weighted by the jacobian. I can guarantee that if this step were disabled, there would be questions on the forum as to why `dwipreproc` isn't doing "what it's supposed to": if people have acquired all of their DWIs with reversed phase encoding, they will be expecting them to be combined. So unless there's strong evidence in support of not doing this step, conforming to users' expectations & reducing processing time wins out.

`-rpe_all` *always* does volume recombination; `-rpe_header` will *also* do volume recombination *if* the input data provided are appropriate for doing so.

**Comment by bjeurissen** [comment]
Sounds sensible!

The 4D bug is indeed down to fsl 6.  I have a backwards compatible patch ready to push tomorrow.
