### ISSUE TITLE
Better name for dwipreproc

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1544]
Some older discussions going on from about here: https://github.com/MRtrix3/mrtrix3/pull/1047#issuecomment-315278398

Some more recent discussions popping up again in #1161 .

For the current methods on offer, as well as what we know is coming up in the future ( https://github.com/MRtrix3/mrtrix3/issues/1161#issuecomment-459694427 ), the top level call seems to be a Python script (with binaries being called upon at a lower level within the Python script).  This renders it technically possible to go for a single script with an algorithm selection.

A proposal I'd raised in some of the above discussions at some point was `dwiundistort` (see some arguments in there), as a compromise between specificity as well as brevity.  Other proposals of course absolutely welcome.

If going for a single script with algorithm selection, we have to identify the basic common interface between all such algorithms (and leave the other arguments and options to the specific algorithms themselves to be defined).  The benefit of the single script would be discoverability, and avoiding confusion with many similar sounding names of different scripts/commands.  Key is then to choose the algorithm names to be very clear on what algorithm they refer to of course.

**Comment by Lestropie** [comment]
@dchristiaens: Thanks for the insight in #1161.

Given this description, I think that moving `dwipreproc` to `dwiundistort fsl` or `dwiundistort eddy` or the like makes sense, and makes it even more explicit that this is fundamentally a wrapper around FSL tools; plus, future alternatives that serve a similar purpose then fairly sensibly get incorporated as alternative algorithms that fundamentally serve the same purpose (removal of image distortions from DWI).

Is anybody *against* this proposal?

**Comment by thijsdhollander** [comment]
Nope, still all for it.  Is everyone else happy with the proposed name as well?

**Comment by maxpietsch** [comment]
If I had to map `dwiundistort` to the FSL tools, I'd guess `applytopup` not `eddy`. How about `dwidistortioncorrect`? A bit longer to type but sounds more active to me and does not have a negation in the name.

**Comment by thijsdhollander** [comment]
Still sounds alright to me.  It's more or less at the limits of a "reasonable" length, I reckon; but just within bounds, I'd personally say.  Autocomplete makes it very manageable still too.  It's also closer to how people describe this kind of step in publications; so that's a plus for sure. 👍

**Comment by Lestropie** [comment]
If the name of the FSL algorithm within the `dwiundistort` script were called `eddy` instead of `fsl`, that should remove the chance of being misinterpreted as just an `applytopup` wrapper.

I'd really prefer a snappy name for this: comes up in discussion & on forum so much. I don't think "undistort" leaves any more ambiguity than "distortioncorrect", and is more consistent with things like "dwidenoise" / "mrdegibbs".

**Comment by thijsdhollander** [comment]
Happy with either choice myself, but I wouldn't call the FSL algorithm `eddy` though.  More than just a single plain `eddy` call happens most of the time, and `topup` is in many scenarios even a part of that.  So I'd definitely err on the "safe" side and call the algorithm `fsl`.  Would work with both `dwiundistort` as well as `dwidistortioncorrect` (or even `dwicorrectdistortion`).  `dwiundistort` is indeed snappier, but `dwidistortioncorrect` is arguably slightly less abstract (e.g. my argument above: people never write about "undistort(ing)", but about "correcting for distortions", or "distortion correction").  They do write about "denoising"; although probably not really about "degibbsing". ("unringing" is not unheard of though)

So well, arguments either way are a bit all over the place... None clearly "wins" (over the other) for me personally.

**Comment by thijsdhollander** [comment]
@dchristiaens, what's your take on this?  Given that in this scenario, your contributions would be an algorithm of this command (so support-wise, you'd probably have to refer to it often), it'd probably best have a name you think works well, all relevant considerations taken into account.

**Comment by jdtournier** [comment]
Just my 2 cents for what it's worth:

- happy with the overall strategy of going for a script with algorithm selection. I think that will serve us well in future, and does make it more explicit that it's a wrapper.

- prefer `fsl` over `eddy` as algorithm name, pretty much for the reason highlighted by @thijsdhollander

- not sure about any of the candidate names so far... My main gripe is that in my experience, the big advance that `eddy` provided when it arrived was not eddy-current distortion correction, but motion correction. Up till then, nothing really cut the mustard when it came to high b-value data. Eddy current distortions were never a big concern at the time since we were using the twice-refocused SE sequence, as were many other sites - motion was always a far greater concern. The `topup` step was and remains optional - yet susceptibility-induced distortions are the most obvious distortions that you might expect something called e.g. `dwiundistort` to correct for - eddy-currents come a distant second IMO. So I think if we are to come up with a better name, it should reflect its ability to correct for motion first and foremost, as well as various sources of distortions. Not that I have any decent suggestions on that front though...

**Comment by dchristiaens** [comment]
I agree with script+algorithm selection and also prefer `fsl` as naming over `eddy`.

Regarding the name, I have the same concern as @jdtournier. To me these steps are instinctively much more about motion correction than about distortion correction. As explained in #1161, my top-level script is called `dwimotioncorrect` and I think we should consider it as an alternative to `dwiundistort` and other suggestions. Although I acknowledge that I may be biased working in a perinatal unit, there are several other reasons why I prefer motion correction as the core name:

- Even in compliant adults, I generally consider subject motion a greater concern than eddy current distortions on modern scanners.
- Susceptibility-induced distortion is indeed a larger effect, but also one that is almost trivial to solve _in the absence of motion_. It's only under subject motion that things get tricky, since the field is then no longer static. 
- [_minor point_] My method currently takes a field map as input. Of course, the script can calculate this with Topup if not provided, and at some point I would also like to do some work on integrating dynamic distortion correction in the motion correction framework. But, I would not want to lose the option of providing a scanner B0 field map. This would be one use-case where, if renamed as such, a `dwiundistort` script would not actually be estimating image distortion...
- [_minor point_] There is also scope for developing independent static and dynamic field mapping methods at acquisition and/or post-processing level, which enables to correct susceptibility distortion prior to motion correction (our lab has one in the pipeline for fetal imaging). This is again a use case where this processing step only serves for motion correction.

I suppose that, at a higher level, I can see the logic behind FSL's Topup-Eddy split as two steps/commands. That is not to say that there aren't good reasons to integrate them in one script, but I like having the flexibility of running both steps independently in less standard applications. If integrated as one, in my opinion motion correction dominates.

P.S. I also have a separate command to undistort images given a B0 field and a motion trace (more or less a `applytopup` equivalent in our formats), currenly given the monstrous name `dwifieldunwarp`. If deemed useful, this could be renamed to `dwiundistort` at some point.

**Comment by thijsdhollander** [comment]
We discussed this with all relevant parties involved during the 5th March meeting.  Correct me if I'm wrong (by all/any means), but just trying to summarise the essence of where we ended up without re-visiting every detail of that hour long discussion:

Current proposal (see minutes) is `dwifslpreproc` or similar as a rename that is more specific than the current name.  Benefits: more specific, more clear, and a bonus acknowledgement to FSL, which this current script builds heavily upon.
@dchristiaens' future additions could end up in their own script and set of binaries.  Benefits: future flexibility, not locking ourselves into a specific (kind of) interface and name towards the future.  Will probably also allow the name(s) for those additions to be (more easily) specific, without a need to resort to overly artificial names trying to embody very different underlying functionality.

At the end of the 5th March meeting, at least several people informally flagged they could see this / live with this / accept this / ... as a decent solution.  But we went off allowing ourselves some time to let it sink in.

Way forward: @MRtrix3/mrtrix3-devs think about this, make up their mind, and we discuss and conclude at next meeting.  Easy!   :wink:

**Comment by thijsdhollander** [comment]
Side kind of thing that I recall @jdtournier briefly mentioning that might be (or have been) useful in all of this: "`geom`", which is mostly what I originally tried (and admittedly failed a bit) to capture in `undistort`; in the challenge of finding something that embodies motion and various distortions in a small amount of characters.  While neat, this might not be so important anymore in light of the above proposed resolution to the whole matter though.

**Comment by Lestropie** [comment]
Failed to update this issue after having discussed in person with @dchristiaens.

Given the fact that the *native* output format of the SHARD-based reconstruction will be different to what is currently `dwipreproc`, we decided that having those two approaches interfaced using the `mrtrix3.algorithm` module would not be wholly appropriate. What we seemed to converge to instead in that discussion was to rename `dwipreproc` to `dwifslpreproc`: apart from greater FSL attribution, it also perhaps implicitly conveys that this script performs a *subset* of DWI pre-processing.

Still not ideal, but might be the best of a bad lot.
