### ISSUE TITLE
tcktransform drops header / corrupts tck file

### ISSUE THREAD

**Issue by LeeReidCSIRO** [MRtrix3/mrtrix3#1558]
Hi,

This is either an issue with `tcktransform` or the description of the tck file format [here](https://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html#tracks-file-format-tck).

This states:

>  It consists of a text header in the same key: value format, ending with a single ‘END’ statement, and followed by binary data. ... The only required keys are ... 
> **file** a file: . offset entry is required to specify the byte offset from the beginning of the file to the start of the binary track data ... 
> **datatype** specifies the datatype (and byte order)

The files produced by tcktransform, however, have dropped the entire header, after 'mrtrix tracks    ' , with no `file`, `datatype`, or `END` tags

![image](https://user-images.githubusercontent.com/26998292/52454310-0b3b4300-2b97-11e9-8cae-66db317bceb4.png)

MRview, at least, seems to handle this without crashing, but I haven't checked other executables. Our in-house software crashes and burns because it's built on the standards listed in the help documentation. Our in-house software can be rewritten to handle this, but to me this seems like a bug in mrtrix (or at least the help documentation) that should be patched up?

**Comment by thijsdhollander** [comment]
...yeah, we should probably adhere to the standards we've set out ourselves, right...? :man_shrugging: :stuck_out_tongue_winking_eye:

**Comment by Lestropie** [comment]
I couldn't reproduce. It's hard to tell what's actually in there from an ASCII readout: a screenshot from a hex editor / download of the file would allow us to determine whether that's actually track data in there or just junk. Are you able to consistently reproduce the issue yourself? To me it looks like a straight file corruption; I can't identify any code path by which a track file could be produced with the magic string but no header data, it's part of the [same function](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC3/src/dwi/tractography/file_base.h#L88).

It's as though specifically the [second `seekp()` call](https://github.com/MRtrix3/mrtrix3/blob/3.0_RC3/src/dwi/tractography/file_base.h#L120) is not succeeding, resulting in commencing write of track data right after the magic string... I don't suppose this happened to be on network-based storage? Could be some kind of lag / packet drop effect.

As far as `mrview` handling the file, I'd have expected it to hit [this Exception](https://github.com/MRtrix3/mrtrix3/blob/master/src/dwi/tractography/file_base.cpp#L50-L51), given the key-value reader would either read "`END\n`" entirely by infathomable chance, or reach EOF, and not have read the datatype...

**Comment by LeeReidCSIRO** [comment]
Hi Rob,

On closer inspection:

1.  I can't reproduce this with tck files that are recently made. This file is ~3y old - I'm not certain which software produced it (perhaps the old version of mrtrix, perhaps something custom), which makes me wonder if it is corrupted. That said, I can't see anything wrong with its header, there are no warnings when opening the file, and it's perfectly viewable in mrview (see image; but note I view results on a build from July: 3.0_RC3-62-gd6656921). 🤷‍♂️ I never had issues with it years back...
2.  It's not just tcktransform or tcknormalise. Even the following command causes this issue: 
```tckedit input.tck output.tck```

![image](https://user-images.githubusercontent.com/26998292/52460882-371af080-2bb8-11e9-96cb-659f25b4fabe.png)


I've sent you some streamlines on cloudstor:

- tracks_from_mesh.tck is the original offending file
- input_cleaned.tck is the same file but I've manually cleaned up the header in case there was an issue there (result is the same)
- result.tck is what I get out for ``tckedit input_cleaned.tck result.tck```

I've produced the error on two linux computers. To reproduce:

1. clone mrtrix main branch (commit 2b8e7d0c2cb8c0d821a0461944855275766dc4f1)
2. configure with no gui
3. build
4. ```tcktransform tracks.tck warp_mrtrix.mif output.mif```

**Comment by Lestropie** [comment]
Cool, thanks for the files. A cursory look shows that the original offending file `tracks_from_mesh.tck` was indeed generated using MRtrix 0.2. However the format hasn't changed and backwards compatibility was ensured when *MRtrix3* development first started. I'm jammed up with admin work right now but this has grabbed my curiosity... Suspect it has something to do with the latest iteration of the file I/O tricks we use to prevent race conditions if the track file is loaded while still being generated. But we'll see.

**Comment by Lestropie** [comment]
Solution: Change byte at offset 0xfe from 0x20 to 0x0A :sweat_smile: 

The code parsing the file header assumes that key-value pairs are separated by a colon, and *terminated by a newline character*. In your file, "`END`" is followed by a whitespace character, resulting in the key-value parser thinking that it is just the start of a key-value pair with a very long name. In fact it ends up reading 57,646 key-value pairs (all but the first few of which contain binary data gibberish) before it gets to the end of the file. But it can still read the track data just fine, because it captured the requisite information (datatype & file offset). The file pointer is manually set to the contents of "`file`"; the fact that the key-value parser erroneously progressed beyond that point doesn't actually matter.

I traced "`END`" being followed by a newline character in *MRtrix3* as far back as [2009](https://github.com/MRtrix3/mrtrix3/commit/59addf8d6e119ab5ab1d90b84d2c2fc4718aa4d3#diff-af87782310eb3ae344213c6fd1d4ccd6R146); likewise for [MRtrix 0.2](https://github.com/jdtournier/mrtrix-0.2/commit/2695d5ee920f8143cf26400075af5bc3291e5675#diff-af87782310eb3ae344213c6fd1d4ccd6R171), but in the latter case the code is likely older than that again, I just can't access the full history (`git` > `svn`). So I'd suggest that this particular file has been produced using some other code.

The documentation probably needs to be a little more clear about the fact that key-value pairs appear as lines, and therefore have newline characters separating them, and that this also applies to the "`END`" symbol.

**Comment by Lestropie** [comment]
P.S. This also explains the gibberish at the start of the file in the screenshot you provided: that's actually the contents of the first key-value string pair that appears in the header :rofl:

**Comment by jdtournier** [comment]
Nice detective work! :+1:

**Comment by LeeReidCSIRO** [comment]
Good stuff! And easy to patch up these files. Thanks a ton
