### ISSUE TITLE
Handle QFileOpenEvent on macos

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#1631]
... to enable image opening on a double click in Finder or a file drop on the mrview Dock icon.

See https://doc.qt.io/qt-5/qfileopenevent.html for details.

This would enable packaging of mrview as a true macos app bundle without having to rely on applescript wrappers and their limitations.

The handling could probably be almost identical to that of drag and drop.

**Comment by maxpietsch** [comment]
Maybe related: macos does not seem to support opening multiple instances of an app other than from the command line via `open -n`. Would it be possible to have a "new window" context menu entry (`cmd + n`) to launch a new window & instance of mrview? I couldn't find the QT-way that would avoid making a system open call. Would our debug image display function work for that?

**Comment by bjeurissen** [comment]
To open a new instance of mrview would require creating a menu with an option "Open new instance of mrview" and then setting that as the dock menu using https://doc-snapshots.qt.io/qt5-5.9/qmenu.html#setAsDockMenu.

**Comment by bjeurissen** [comment]
The toy example below seems to do the trick:

```
#include <QApplication>
#include <QPushButton>
#include <QFileOpenEvent>

class MyApplication : public QApplication {
public:
  MyApplication(int &argc, char **argv) : QApplication(argc, argv) {
    button = new QPushButton("Hello world!", 0);
    button->resize(100, 30);
    button->show();
  }

  ~MyApplication() {
    delete hello;
  }

  bool event(QEvent *event) {
    if (event->type() == QEvent::FileOpen) {
      QFileOpenEvent *openEvent = static_cast<QFileOpenEvent *>(event);
      hello->setText(openEvent->file());
    }
    return QApplication::event(event);
  }

private:
  QPushButton* button;
};

int main(int argc, char **argv) {
  MyApplication a(argc, argv);
  return a.exec();
}
```
This way, I can open a file natively (without wrapper) by double clicking. If I double click additional files with the application open, these are opened in the application that is already open, which sounds sensible for mrview as well.

Where in the code should I best insert the event handler?

**Comment by maxpietsch** [comment]
I think the event handler needs to be registered to the global qApp accessible via [qApplication::instance()](https://doc.qt.io/qt-5/qapplication.html) to add the drop on dock icon functionality: https://stackoverflow.com/questions/33442490/accept-file-drop-on-dock-icon

**Comment by maxpietsch** [comment]
Gave it a shot, added the event to `Window::GLArea::event` but that does not get triggered with drag and drop on the dock icon (tested when started from terminal not as an application). @jdtournier If not `Window::GLArea`, what is the equivalent of `QApplication` in mrview?

```
src/gui/mrview/window.h:
#include <QFileOpenEvent>

src/gui/mrview/window.cpp:
bool Window::GLArea::event (QEvent* event) {
  if (event->type() == QEvent::Gesture) {
    return main->gestureEventGL (static_cast<QGestureEvent*>(event));
  }
  else if (event->type() == QEvent::FileOpen) {
    TRACE;
    QFileOpenEvent *openEvent = static_cast<QFileOpenEvent *>(event);

    vector<std::unique_ptr<MR::Header>> list;
    try {
      list.push_back (make_unique<MR::Header> (MR::Header::open (openEvent->url().path().toUtf8().constData())));
    }
    catch (Exception& e) {
      e.display();
    }
    if (list.size())
      main->add_images (list);
    return list.size();
  }
  return QWidget::event(event);
}
```

**Comment by bjeurissen** [comment]
@maxpietsch That also did not work in my dummy example with a proper QApplication. Only opening a file on double clicking worked.

**Comment by maxpietsch** [comment]
Manual file association works without modification for double-clicking if assigned from `context menu --> get info --> open with`, so I am assuming you want to automatically assign the file type to the application?  I can't see where in the app you shared you defined the file extension, did you declare the mif file type in Info.plist and associate it with the application? (see [custom file type declaration](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_declare/understand_utis_declare.html#//apple_ref/doc/uid/TP40001319-CH204-SW1) and [these SO instructions](https://stackoverflow.com/questions/2774343/how-do-i-associate-file-types-with-an-iphone-application)). 

Since opening after manual association works, I guess it's not a problem with a missing file open event. I can't test the above code as macos doesn't allow me to select the binary to open file types and I can't get mrview to open from your application bundle without modifying mrview's linked libraries.
