### ISSUE TITLE
a few minor things wrt testing and files left behind

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#1654]
As the title says: a few minor things; happily split into multiple issues or whatever works. Here they go:

* Running `./run_pylint` offline also checks `lib/mrtrix3/_version.py`, which reports a pylint error: `W:  1, 0: Unused variable '__version__' (unused-variable)`. Obviously, this variable is crucial here. I suppose `./run_pylint` should simply not check `lib/mrtrix3/_version.py`.

* Running `./check_syntax` offline generates, and leaves behind, `.check_syntax.tmp` and `.check_syntax2.tmp`. However, these are not in `.gitignore`. I suppose they should either be in `.gitignore`, or alternatively be cleaned up upon finishing `./check_syntax`. Given their context, I'm guessing it should be the latter. (although the former, even in addition to the latter, might not hurt in general in any case)

* More complicated, not related to testing: docs for python scripts are generated "from" (or using) the `.pyc` files (e.g. when running `./build doc` or similar). However, when switching from a branch/tag (or commit in general), that has a certain algorithm for a script e.g. in `lib/mrtrix3/...` and has it's `.pyc` file already there, to another branch/tag (or commit in general) that does not have this algorithm, the `.pyc` file still gets left behind. When then regenerating the docs (e.g. by running `./build doc` or similar), that algorithm will still be included, resulting in docs that don't "align" with the state of things as to presence of `.py` source code. This is a bit as with binaries: should these `.pyc` files be cleaned up as well at certain stages, e.g. when regenerating docs or similar. Long story short: `.pyc` files and their presence or how they linger around isn't 100% taken into account yet for some scenarios. Not sure what the best answer is, but it seems worthwhile thinking about it.

**Comment by thijsdhollander** [comment]
This is all on `dev` by the way; some might apply to `master`, but I haven't checked.

**Comment by Lestropie** [comment]
Couldn't reproduce the final issue & having trouble figuring out from the code & description how it could come about, either for `bin/` files or script algorithms. It seems that the `iter_modules()` call can grab the lingering `.pyc` file, but I couldn't get it to propagate that to the help page / documentation, all I could get was a crash when reading a Python 2 `.pyc` using Python 3 (and there's a chance the fix for that in #1913 would fix your observation). If you can give detailed steps for reproduction after #1913 I'll re-open.
