### ISSUE TITLE
Branch / version naming / policy following release

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#1673]
A brief thought on the naming of development branches following software release.

The intent is to move to semantic versioning upon release. Once this occurs, it may be possible to have software developments occurring *at a hierarchy of levels*; e.g.:

- Backwards-incompatible API changes (whether it be relatively basic API changes, or such a massive refactor that it becomes the precursor to *MRtrix4*);

- Addition of new functionalities, as is currently done in `dev`;

- Modification of existing functionalities that changes outcomes, as is currently done in `dev`;

- Fixing of issues that are outright incorrect, but are not sufficiently urgent to warrant a tag version update (currently we'd just merge anything of this sort straight to `master`, but if every such merge were to require a tag update, some of such updates may instead be deferred);

- Fixing of issues that are more urgent, which would currently be merged to `master` and probably announced on the forum.

So having only `dev` and `master` to choose from may not be an adequate level of granularity once semantic versioning is invoked.

What I would propose instead is: in addition to the `master` branch, have *three* central development branches, that are named according to semantic versioning: `major`, `minor` and `patch`:

- `major` would be for anything that breaks backward compatibility. The magnitude of API change necessitating a major version update needs to be determined:

  - If semantic versioning were to be taken literally, then *any* API code change would necessitate a major version update, in which case we may want the major version to start at "1" rather than "3";

  - Alternatively, we may want to keep the major version fixed at "3", and accept minor API changes at the minor version level, at which point the `major` branch would be reserved for @jdtournier's inevitable compulsive future API overhaul :-P

- `minor` would serve a very similar purpose to `dev` currently, collecting new features and any changes that alter command behaviour.

- `patch` would be filled with any changes that are "fixes", but not of urgency; e.g. fixing spelling mistakes in command documentation or the like. When a more urgent bug fix is encountered, it would be merged to `patch`, and all contents of `patch` would then be merged to `master`, forming a patch-level tag update.

Open to thoughts / suggested alternatives.

**Comment by jdtournier** [comment]
OK, a few thoughts here. First off, I don't see the need to a `major` branch just yet (you'll be glad to hear), and the major version would start at 3 - we can't move back to 1 now... 

However, I'm not sure we really need to change things at all, given that our workflow is already compatible with that anyway - major versioning aside (mostly because we have no need for it at the moment). Semantic versioning applies to the version numbers we give, but doesn't necessarily mean we have to use those names for the branches themselves. We're currently using something pretty close to [this approach](https://nvie.com/posts/a-successful-git-branching-model/) to manage our workflow, and the versioning can happily follow the [semantic versioning](https://semver.org/) recommendations without changing that in any way - they're not the same thing. 

- `dev` is already _de facto_ the branch holding the future minor version. We can and should specify that any merge of `dev` to `master` should trigger a minor version increment.
- `master` is already _de facto_ the branch that holds the future patch version. We can and should specify that any tag of the `master` branch should trigger a patch version increment. 
- actual versioned releases correspond to tagged commits on `master`

We have to use git tags for actual releases since these are immutable, that's what they're for. We can't use branches since they're designed to evolve. So I don't think there's any problem using `master` as the 'pending patch' branch, and `dev` as the 'pending minor version' branch. 

All of this is perfectly compatible with semantic versioning, and I don't really see a need to change it a great deal, other than formalising the kinds of changes that we expect each of these branches to hold. This is basically what we've been doing so far anyway, with the difference being that since we're in pre-release, merges of `dev` ➡ `master` have so far triggered patch version updates, while the minor version had been stuck at 3 (until we started the release candidate versions). Once we do release, we'll naturally start using proper versioning as above, I reckon. As long as we use the workflow we've been using so far, but adopt a process whereby merges of `dev` ➡ `master` trigger a minor version update, and explicit tags of `master` trigger a patch version update, we're good, right?

**Comment by Lestropie** [comment]
On the conditions that:

1. Any sufficiently "major" API changes go to a project separate to *MRtrix3*;

2. We are content with minor API changes being part of minor version updates, despite being technically against semantic versioning spec;

3. There's no problem with merging something to `master` and *not* triggering a tag / patch update;

, then there's no issue with the current arrangement.

**Comment by thijsdhollander** [comment]
> Any sufficiently "major" API changes go to a project separate to MRtrix3;

You can still create a branch when that happens, or the need for it arises; acknowledged by:

> workflow is already compatible with that anyway - major versioning aside (mostly because we have no need for it at the moment)

GitFlow is very well established, and works well for far, far larger teams and projects even.  You just need the discipline (or policy, or whatever) to stick to it, and it'll work its wonders.  E.g. stick to hotfixes merging "concurrently" to `master` and `dev`, etc...  It's all basically designed to avoid diverging branches and messy merges as a consequence.  A core part of achieving that goal successfully is keeping the number of main persistent branches (`master` and `dev`) as low as possible; basically a case of Occam's razor.

**Comment by jdtournier** [comment]
OK, I get the issue that if we did think about starting a whole new version of MRtrix, it ought to be named MRtrix4, and this repo (and entire organisation) is named MRtrix3. Problem is that the `mrtrix` username is already taken... 

So yes, I agree that there's a problem. But I don't think starting major version numbers at 1 is going to help with that - I'd find it awkward to have "MRtrix3 v1.0.3"... I think we'll have to work this out if & when the issue crops up. And it might be that setting up a whole new repo is the simplest, or maybe by that stage we can grab the mrtrix username if it's available (or convince its owner to let us have it...).

**Comment by jdtournier** [comment]
On your point 2: this is where we might indeed have divergence with the strict interpretation of semantic versioning. For core libraries, a really important aspect is that they should be binary compatible with versions with lower minor/patch numbers. We're not talking just API here, but ABI (application _binary_ interface): applications linked against the library do not even need a recompile. To ensure ABI compatibility imposes quite a few constraints and requires much stricter rules and discipline than what we're used to. Even adding a member to an existing class is likely to break ABI compatibility: if it's not added at the end, it mean the memory layout of the members will be altered, and existing members will be at a different offset into the structure than previously compiled applications will expect. And even if it's added at the end, any code that uses a vector or array of such structures is likely to break if the size of the class changes. There's lots of other things that can break ABI compatibility (e.g. adding an optional argument with a default value to an existing function). Personally, I don't think we can provide that level of compatibility here. And I don't think we need to, we're not providing core system functionality. As long as we make it clear that minor versions will be (broadly) API compatible, we're not going to ensure ABI compatibility. 

As to API compatibility, I reckon whatever changes we'll be making will be more peripheral, and/or adding functionality rather than changing it. The main thing is we're not anticipating large changes in the image handling, command-line parsing, streamline handling, etc backends in the foreseeable future, and these are the main things that would drive a major version change. I don't anticipate we'll need to modify existing applications at the source code level as a consequence of minor version increments (though they will no doubt change for other reasons). That might not hold true for scripts though...

**Comment by Lestropie** [comment]
> That might not hold true for scripts though...

#1527 is relevant. In the absence of pre-compilation, API changes can result in weird runtime errors, which in turn results in user complaints. It might be worth bumping that to release miliestone, so that external scripts written against the first "released" *MRtrix3* version will be capable of detecting subsequent *MRtrix3* updates.
