### ISSUE TITLE
Add estimated b=0 term to tensor image output

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#17]
This gives two benefits in the context of the generalised orientation overlay tool (Issue #11):
* Allow to automatically determine whether loaded image is SH with lmax=2 (6 volumes) or a tensor image (now 7 volumes)
* Allow more options in scaling of tensor glyphs

**Comment by Lestropie** [comment]
Bumping one more time since the tensor overlay is now tentatively working in updated_syntax. DT images are initially opened as lmax=2 SH images, and need to be manually changed to tensor mode to visualise properly. Some previous discussion of pros and cons in 7faeb67.

**Comment by thijsdhollander** [comment]
I'm mostly aligned with Donald's comments in https://github.com/MRtrix3/mrtrix3/commit/7faeb679ad5c0948e01764c1245a0778cb958906#commitcomment-13304437 on this one.  A good approach to fix the "manual change" problem in the GUI could just be to provide buttons to load specific stuff, e.g., "Load SH file", "Load tensor file", "Load dixel file", etc...  Functionality of changing "modes" for stuff that's already loaded is probably not a requirement (since any file's contents will only be suitable for a single mode).

**Comment by Lestropie** [comment]
Agreed RE mode changing; but disadvantage of separate load controls is that you can't select multiple overlays with different types from a single dialog; which I have used myself. Six of one, half a dozen of the other...

If there's no strong support let's leave this aspect as-is.

**Comment by thijsdhollander** [comment]
@Lestropie : not sure myself, but, do you think there might be an opportunity to (semi-)robustly detect the difference between the tensor coefficient vector and the lmax=2 SH one?  One particular feature of the SH one, is of course that the DC term typically stands out quite a bit from the rest...  If the mode-wise option is still there, the user can of course still fix the odd case where such a detection mechanism would fail.

**Comment by Lestropie** [comment]
There's definitely options for making a better guess as to which it should be. In addition to the SH l=0 domination, the tensor coefficients are a couple of orders of magnitude smaller. But you also don't want to scan the entire volume on image load to inform such a heuristic. Given the mode-wise option is always there, I'm not overly concerned, unless I start receiving complaints.
