### ISSUE TITLE
dwi2response dhollander: crash when whitespace in folder name

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#1749]
`dwi2response response` fails to invoke `dwi2response tournier` if there are any whitespaces in the working directory.

**Comment by thijsdhollander** [comment]
Hmm, surprising; I think I remember running it on such.  [The line where this call happens](https://github.com/MRtrix3/mrtrix3/blob/master/lib/mrtrix3/dwi2response/dhollander.py#L138) is pretty simple; equivalent almost to [the same line in dwi2response msmt_5tt](https://github.com/MRtrix3/mrtrix3/blob/master/lib/mrtrix3/dwi2response/msmt_5tt.py#L86), so I reckon it must be something with how calls to other scripts, or more specifically those with algorithms maybe, are performed in the library.  Does the same happen with `dwi2response msmt_5tt`?

This might already behave very differently on `dev` (at least for `msmt_5tt`) due to all changes in the Python library.  Might be worthwhile checking whether anything has already inherently solved it there.  I don't know what the release timeline is, but it might not be worth fixing anymore with a customised hack on `master` at this stage; I haven't seen it come up as an issue in years at least.  I wasn't able to reproduce on `dev` with `dwi2response msmt_5tt` at least, unless I'm not reproducing the correct scenario.  If it's still an issue on `dev` (that I failed to reproduce), it would show up in #1689 as well; something we should remember there then at least.

**Comment by jdtournier** [comment]
fixed with 177a44b, as part of #1689
