### ISSUE TITLE
[dwipreproc]: [eddy]

### ISSUE THREAD

**Issue by JEAN-WEIJ** [MRtrix3/mrtrix3#1767]
eddy --imain=eddy_in.nii --mask=eddy_mask.nii --acqp=eddy_config.txt --index=eddy_indices.txt --bvecs=bvecs --bvals=bvals --out=dwi_post_eddy

I'm thrown
terminate called after throwing an instance of 'EDDY::KMatrixException'
  what():  KMatrixException: msg=MultiShellKMatrix::SetDiffusionPar: Data not shelled

**Comment by Lestropie** [comment]
Hi @JEAN-WEIJ,

Being an FSL command rather than *MRtrix3*, I do not know the specifics of exactly how this error is generated (`dwipreproc` simply propagates the error message generated by `eddy` up to the user). This is however [not an uncommon error](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide#A--data_is_shelled). What you need to do is manually check the nature of your diffusion gradient table:

1. If the data are not arranged into "shells" (where the b-values of multiple volumes are almost identical but the direction of diffusion sensitisation is varied), then `eddy` (and therefore `dwipreproc`) is not currently applicable to your data.

2. If the data are arranged into shells, but for whatever reason `eddy` is failing to classify the data as such, you can force `eddy` to process your data by including "`-eddy_options " --data_is_shelled"`" in your `dwipreproc` call.

Rob

**Comment by JEAN-WEIJ** [comment]
Dear Rob:
Thank you very much.
My problem was solved by installed the latest version of FSL. Thanks!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Robert Smith"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月16日(星期三) 上午9:42
收件人:&nbsp;"MRtrix3/mrtrix3"<mrtrix3@noreply.github.com&gt;;
抄送:&nbsp;"魏静"<4599152@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MRtrix3/mrtrix3] [dwipreproc]: [eddy] (#1767)




Hi @JEAN-WEIJ,
 
Being an FSL command rather than MRtrix3, I do not know the specifics of exactly how this error is generated (dwipreproc simply propagates the error message generated by eddy up to the user). This is however not an uncommon error. What you need to do is manually check the nature of your diffusion gradient table:
  
 
If the data are not arranged into "shells" (where the b-values of multiple volumes are almost identical but the direction of diffusion sensitisation is varied), then eddy (and therefore dwipreproc) is not currently applicable to your data.
 
 
 
If the data are arranged into shells, but for whatever reason eddy is failing to classify the data as such, you can force eddy to process your data by including "-eddy_options " --data_is_shelled"" in your dwipreproc call.
 
  
Rob
