### ISSUE TITLE
mrconvert -export_grad_fsl result is different from dcm2nii

### ISSUE THREAD

**Issue by fangrongzong** [MRtrix3/mrtrix3#1804]
Hi MRtrix Experts,

When I ran the following command:
mrconvert DICOM-DTI/ dwi.nii.gz -export_grad_fsl bval bvec
I got the bvec in which the gradient direction is opposite than the file I got from dcm2nii. 

Is it normal? Just would like to make sure that the gradient direction is right before any further processing...

Thanks
Fangrong

**Comment by Lestropie** [comment]
Hi Fangrong,

When you say "the bvec is opposite", are the vectors *exactly* antipodal, i.e. all of the x, y, z components of each vector are multiplied by -1? Because if that's the case, then the difference should be inconsequential in almost all instances, since the diffusion signal itself, and almost all models of such, assume antipodal symmetry. The only case off the top of my head where this difference may be consequential is in the modeling of eddy current distortions during pre-processing, depending on the underlying method.

It may be worthwhile comparing (if applicable / interested), for a purely axial DWI acquisition (so there's no difference between scanner-space and real-space axis directions), the data that were provided to the scanner to define the gradient directions, to the `bvec` files you get from the two softwares, and see which one matches (taking into account reversal of the first component in the bvecs file for radiological data; see [documentation](https://mrtrix.readthedocs.io/en/latest/concepts/dw_scheme.html)).

Rob

**Comment by jdtournier** [comment]
@fangrongzong, did this answer your concerns? If so, can you close this issue? 
Thanks!

**Comment by fangrongzong** [comment]
Hi Rob,

Thanks very much for your explanation. Yes, all of the x, y, z components
of each vector are multiplied by -1. I understand that it may not be an
issue if computing FA and MD values, but how about fibre tracking? I
started to notice this issue after I found the incorrected tracks.

Thanks,
Fangrong

**Comment by fangrongzong** [comment]
Hi Donald,

Sorry for the late reply. I just get access to my gmail account. I
still would like to follow this issue. But if I can email you guys in
other ways, I'm happy to close this issue.

Best,
Fangrong

**Comment by jdtournier** [comment]
> I still would like to follow this issue. But if I can email you guys in other ways, I'm happy to close this issue.

No, only close the issue if it's resolved. Not a problem. The only thing I might suggest in future is to address these kinds of queries to the [community forum](https://community.mrtrix.org/) first, unless you're very confident there is a bug - there are a lot more people monitoring that forum than the GitHub site... 

> I understand that it may not be an issue if computing FA and MD values, but how about fibre tracking?

It shouldn't be an issue either. Diffusion is symmetric about the origin, and so are the derived fibre orientations. You should be able to verify yourself by tracking using the `dcm2nii` output and comparing to the MRtrix3-converted output.

> I started to notice this issue after I found the incorrected tracks.

This sounds like a different issue, then. Please tell us as much as you can about the nature of your data, what scanner they were acquired from, whether they are human/animal, whether a manufacturer-supplied or a custom sequence, etc. For instance, you'll find that DICOMs produced by Bruker are rarely properly encoded, but things should work for the 3 main manufacturers. Also provide a screenshot to illustrate the problem, that is often a lot more informative than any description.

**Comment by fangrongzong** [comment]
Hi all,

Sorry for the late response. I figured out the issue by comparing different
method files.  It is tricky to process Bruker gradient files. And since I
do not know why it happens when exporting the gradient file, the only thing
I can correct is to swap x/y +/- multiple times to find the correct
orientations. Thanks again for your patience. Please feel free to close the
issue.

Best,
Fangrong

**Comment by jdtournier** [comment]
Great, thanks for the feedback. I'll close, but feel free to re-open if needed.

**Comment by Lestropie** [comment]
> And since I do not know why it happens when exporting the gradient file, the only thing I can correct is to swap x/y +/- multiple times to find the correct orientations.

Give the `dwigradcheck` script a try.
