### ISSUE TITLE
Save the command used to generate a file in the output header

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#183]
We could even propagate the commands saved in the input images to the output images, such that each file has a history of where it came from.  

By saving absolute file paths in combination with the git hash (see #111), a record of exactly how the file was generated would exist. We could add a -history option to mrinfo to dump what is effectively a bash script, so then you could re-run the analysis if code or the input images are changed. Since some files may have common ancestors, we could even have a dedicated mrtrix command called 'regenerate', that takes multiple input files, reads their history, removes any duplicate commands, and re-runs the analysis.

This would also serve as a great tool for making backups of what you did, without having to store duplicate copies of all images.

As Thijs raised, the only concern with absolute paths is that sensitive information might be saved in files (such as a persons username or patient names if the parent folder is labelled as such)

Of course if files are moved after they are created then this will also be an issue. But the history 'script' could easily be modified.

**Comment by draffelt** [comment]
I guess if we made it clear when storing the command used to generate the file what arguments were input files, then we could always write a script/app to work backwards build the complete history of commands on the fly, providing that the input files were not moved. This would avoid us having to store the complete history in each file (along with the git hash for each command).

**Comment by Lestropie** [comment]
Probably wouldn't put this in the header storage; just store the generating command string as-is in the header, and e.g. parsing the output of `__print_full_usage__` for each command would allow a script to figure out what's input and what's output for each. Or implement an alternative command-line option that just gives the necessary information, maybe `__interface__` or the like, and have the set of Python scripts output something appropriate as well. Though I guess this wouldn't work for non-MRtrix stuff.

Also need to think about how piping might be handled in this context.

**Comment by draffelt** [comment]
Good point, piping could be an issue

**Comment by Lestropie** [comment]
Could potentially be done if the translation of the '-' were done immediately at argument/option parsing time rather than by the pipe image format/handler; that way both calls would store a path to the same (non-existent) temporary file.

**Comment by jdtournier** [comment]
Yes, the idea of storing the command history in the header has come up quite a few times before, and I've always thought it would be worth doing. Problem is that doing it _right_ is actually very tricky...

First off, the command history is rarely linear. Many commands take multiple inputs, and each of these commands would have their own history. So we would need to store a history _tree_. Not impossible clearly, but not as neat and tidy as might appear at first sight.

We could, as Dave suggested, store each image's generating command only, and rely on these input images still residing on disk, so that an appropriate script could extract the full history by examining all the inputs recursively. As mentioned before, problem there is that any pipes will cause loss of history unless handled appropriately (not sure how exactly). And it's not unlikely users will remove temporary files once they're done, which we really can't detect. And there's also the next point:

Regardless of all these issues, obviously this only works for mif/mih format images. Many (if not most) users will use NIfTI preferentially (grumph, despite my best efforts at convincing them of the inferiority of the format...), making this worthless for them. Even we use NIfTI at various stages of many of our pipelines, and every time we do, this would break the history chain.

Clearly we can't expect this to be perfect, and maybe that would be good enough. It would provide a fallback in the event that we genuinely need to figure out what was done and the commands weren't scripted. It also allows us to figure out which _version_ of the code was used at each stage of the pipeline - not insignificant given for example the changes to the SH basis. So I do think there's value in this, but I don't see that it can ever replace the full script itself, which is why I've never really bothered to do anything about it...

An alternative option that doesn't rely on MRtrix at all is to encourage users to use tools such as [the script command] (http://unixhelp.ed.ac.uk/CGI/man-cgi?script), which allows you to record your entire command-line session to file. I think this would be much more useful, since it would also record non-MRtrix steps...

In any event, we should very definitely store the git version in the header. Probably as the first comment, which does get stored in the NIfTI header as well. Or use a dedicated field in mif/mih and repurpose the NIfTI header comment field as a version string - either way, that would already provide a really useful way of inspecting data retrospectively.

If we do go with sorting the full history, there's also other minor details like handling special characters in filenames (otherwise running the command as-is will fail, and might still be ambiguous when trying to fix it up manually), storing the git version of each command in the chain, etc. But there are obvious solutions for these, I'm just flagging them up for reference...

As a final aside: relying on `-` as the image name to detect temporary (piped) images is not enough: you can provide the _name_ of a temporary file as an argument, and it will be treated as if it has been piped through - I even wrote a [wiki entry on the topic](https://github.com/jdtournier/mrtrix3/wiki/Unix-pipelines#really-advanced-pipeline-usage)...

**Comment by dchristiaens** [comment]
I think it would be a great feature, but just thinking of my typical pipelines, I use lots of non-mrtrix commands in between (FSL, ANTs, custom python scripts, ...). As such, I don't think a native mrtrix solution would ever be able to log the entire history tree, and I would probably still end up keeping a custom shell script for each experiment/dataset I process. Nevertheless, logging the history of parts of the pipeline could definitely ease the workflow a bit, especially for mrmath/mrcalc/mask editing/thresholding/... operations that I like to check visually.

**Comment by jdtournier** [comment]
superseded by #962
