### ISSUE TITLE
ENH mrview: display full path of loaded files

### ISSUE THREAD

**Issue by ansk** [MRtrix3/mrtrix3#1866]
When loading multiple files (via tractography, fixel plot, etc.) the full paths of loaded files are NOT displayed in the toolbar. It becomes particularly frustrating when loading multiple files with differing names only somewhere in the directory tree, since there is further no way to figure out, which file is which. The full file name is not displayed when toolbar is resized. 

It could help to
a) display the full path as the popup tooltip when mouse is hovered over
b) update displayed path to fit to resized toolbar size
c) when clicking at "open", to jump to directory of currently selected file in the toolbar

**Comment by jdtournier** [comment]
Yes, that's been bugging me too... Take a look at #1867, which I think fixes your first two points. 

The last point (about opening in the same place as the currently selected item) should also be possible, but I'm not convinced it's always the best policy. Wouldn't mind hearing other opinions on that one before looking into it.

**Comment by ansk** [comment]
Hi, @jdtournier,

super, it helped!
Could you please also add a popup tooltip of the filename of `.tsf` file used in `colour map and scaling` and `thresholds` in `Tractography` toolbar and also in `Fixel plot`?

Antonin

**Comment by jdtournier** [comment]
OK, I've added tooltips for the .tsf handling. But I'm not sure we need that for the fixel plot tool, since these comboboxes are populated by the contents of the corresponding fixel directory. They're not allowed to be in any other location than the main fixel dataset itself (@Lestropie, correct me if I'm wrong... :grin:). Assuming that's right, there is no point in additional tooltips there.

By the way, I'm closing this issue, but feel free to keep commenting and making suggestions on #1867.
