### ISSUE TITLE
mrtransform usage on drop2 registration output 

### ISSUE THREAD

**Issue by asmagen** [MRtrix3/mrtrix3#2004]
I am using [drop2](https://github.com/biomedia-mira/drop2) registration for histopathology images but the outputs are deformation_field_x.nii.gz and deformation_field_y.nii.gz deformation fields which I would like to apply on the RGB png image channels to get a registered png RGB image.

Is mrtransform the right function to use? How do I use it on an RGB png image and the deformation field gz field above?

Thanks

**Comment by maxpietsch** [comment]
Yes, `mrtransform` is the command to warp images using deformation fields. I believe we support warping png images but I have not personally tested this with mrtransform. 

For you to apply your drop2-generate warps, you'd need to get a couple of things right so that  `mrtransform` interprets these correctly (header transformations, image stride dependencies, warp format conventions). If drop2 uses ITK conventions you might find a way to convert these warps to mrtrix3 format [here](https://community.mrtrix.org/t/convert-mrtrix-warps-and-affines-to-itk-format/1670/4).

However, if drop2 has a tool that allows warping images using their native warp format I'd suggest you follow the procedure described in the [docs](https://mrtrix.readthedocs.io/en/latest/spatial_normalisation/warping_images_with_warps_from_other_packages.html) instead. If you need help with this, I'd suggest you post in our [community](https://community.mrtrix.org/search?q=warpconvert) forum where we prefer to collect and discuss QA threads.

**Comment by Lestropie** [comment]
For clarity: On `dev` (which will imminently be version `3.0.0`), PNG is supported as a native image format, and so can be used as an input or output anywhere that a `.nii.gz` could otherwise be used. But this will not work straight away for you if you are using the `master` branch or `3.0_RC3` tag.

**Comment by asmagen** [comment]
Thank you @maxpietsch and @Lestropie 
I tried posting followup questions in the forum you pointed me to but the google/github login features aren't working at the moment, not sure if you're aware of that.
@maxpietsch The post you mentioned discusses a conversion from mrtrix3 to ITK format, not the opposite, am I correct?
And the issue with a separate x y object (I have two nii objects corresponding to x and y deformations) is making it difficult to utilize existing tools. @Lestropie Is the functionality you're referring to capable of handling these two objects or is there a simple way to combine my separate x,y nii objects?
Thank you

**Comment by jdtournier** [comment]
> I tried posting followup questions in the forum you pointed me to but the google/github login features aren't working at the moment, not sure if you're aware of that.

Darn, no, wasn't aware. It was working not that long ago... Not sure what happened. I'll chase this up at some point, but it might be while before I find the time.

**Comment by asmagen** [comment]
Thanks. I would be glad to have your input for the other questions @maxpietsch @Lestropie.

**Comment by maxpietsch** [comment]
Yes, the post is about MRtrix3 to ITK format but you should be able to go the other way using `mrcalc` to flip signs, `mrcat` to concatenate images along any the 4th dimension and `warpconvert` to convert your warp to a deformation field if needed. If you want to go that way, our warps are deformation fields that map from one to another image via the x,y,z coordinates stored in the 4th dimension as lookup table. You'd need to figure out whether our x,y is your x,y. You could get the z component via multiplying x with zero using `mrcalc` (if it is a displacement field) or from `warpinit` (if it is a deformation field). 

This likely takes some trial and error and validation and if there is a discrepancy on how coordinate systems are defined you also might need to fiddle with the header transformation of the png image.  Hence my suggestion to follow the instructions in the docs (using the dev branch).

**Comment by maxpietsch** [comment]
Closing this issue, reopen if necessary.
