### ISSUE TITLE
Drop python2 support?

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#2047]
Python2 is no longer supported by the Python developers since January 2020: https://www.python.org/doc/sunset-python-2/.

And major Linux distributions like Debian and Ubuntu as well as macOS have now also deprecated python2. This means they ship with python3 instead of 2 and have changed all shebangs in python scripts to #!/usr/bin/python3.

The general idea that seems to be adhered to by both Linux and macos seems to be: Installing 'python' will always install the deprecated python2 and calling 'python' will always run deprecated python2. This also means that any package still using #!/usr/bin/python will have python2 as a (deprecated) dependency. Ultimately, the idea is that you always call 'python3' or install 'python3-foo' and that running 'python' and installing 'python-foo' should become a thing of the past.

E.g.: https://wiki.debian.org/Python/2Removal: 

> port upstream package to python3 (or file upstream bug): make sure package doesn't call python at build- or compile time (as there won't be a python package and no python command in bullseye, only python3.)

and https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3#.2Fusr.2Fbin.2Fpython: 

> /usr/bin/python is a symbolic link to /usr/bin/python2 and belongs to the python2 package. This also means that packages that require /usr/bin/python (usually due to shebangs) de facto require Python 2.
...
Since Fedora 26, there is no python package, only python3 and python2. python is virtually provided from python2.

So the "python-is-python3" package that I mentioned I installed on ubuntu 20.04, is only an ugly workaround that will break software that still relies on the deprecated python2 and the right way forward seems to be to update all our python scripts to use #!/usr/bin/python3 instead... This would also mean that we effectively drop support for python2.

Any thoughts on this?

**Comment by Lestropie** [comment]
[Relevant PEP](https://www.python.org/dev/peps/pep-0394)

It looks like Arch is the outlier here, having [had `python` point to Python3 since 2010](https://www.archlinux.org/news/python-is-now-python-3/).

My summary of the PEP would be to keep "`#!/usr/bin/env python`" for anything intended to run in a virtual environment only, and to shift to "`#!/usr/bin/env python3`" everywhere else.

So I think that I would be in favour of changing; though preferably as part of a minor rather than macro update.

**Comment by jdtournier** [comment]
More relevant musings on the matter from the GNOME devs:
https://blogs.gnome.org/mcatanzaro/2018/02/16/on-python-shebangs/

Seems using `/usr/bin/env` is also problematic - but is nonetheless recommended in PEP 394 _for use in virtual environments only_ (which doesn't apply to us since we expect our scripts to be used in all kinds of contexts). On the flip-side, most of the issues of concern to the GNOME devs don't necessarily apply to us - users adding a borked version of python to their PATH may cause MRtrix3 scripts to fail, but they won't make the system unusable as might happen with system or core UI components. 

Personally, I don't see that a universal solution exists. What we're doing right now is probably not far off the only thing we can sensibly do, and I agree the only discussion should relate to whether we change that `python` to `python3`. I'd lean towards `python3`, but I'd be surprised if it doesn't break something for some users somewhere.

One mitigation strategy here might be to add a simple script to allow users (and package maintainers) to update the shebang line easily. That way, we would only need to document in the installation instructions that this step may be required if the right version of python can't be found. .

The other solutions mentioned all require more work:

- update all of our shebang lines when building to hard-code a known-good python interpreter. Will cause issues with git - we'd need to store the versioned script files elsewhere, copy them over to `bin/` when building, and update the copies if needed. Very hard to see how we can guarantee correct operation when packaging for distribution, unless the package itself is very specific to a particular OS/version combination, or the package mechanism includes a means of verifying or updating the shebang if needed. Likely to cause issues on HPCs if the correct version of python needs to be pulled in via `module_load` or similar. No fun - and probably best left to package maintainers for the various distros. But this might include us in due course, particularly for MSYS2 (it would avoid [this hack](https://github.com/MRtrix3/mrtrix3/blob/master/configure#L171-L174)) and the anaconda builds (not sure what their recommendations are on that front). 

- a wrapper script that will store or detect the correct `python` interpreter. Advantage is that it would provide a single entry point that can be modified more easily. Typical way of achieving this on Unix is by symbolic-linking each command to the wrapper script, have the wrapper read its original invoked name in `argv[0]`, and invoke the corresponding script with the right interpreter. Means moving our script files out of `bin/` and into most likely `lib/mrtrix3/bin`, adding the symlink at build-time, and also (fairly importantly) no Windows support (no simple symlinks)...

- require all our users to prefix the scripts with the intended interpreter (e.g. `python3.4 dwifslpreproc ...`). Neatly shifts the onus for getting this right onto the users, but likely to cause no end of confusion for those less technically inclined. May be worth documenting anyway, but it seems a bit heavy-handed to force this onto most users where there isn't currently a problem.

There's probably other ways to deal with this, but ultimately, it's messy and I don't think we're going to find a neat solution...

**Comment by Lestropie** [comment]
Bumping to `3.1.0` milestone.

There's also some gymnastics around supporting both Python2 and Python3 in various scripts, both for execution and for passing `pylint` testing, that could be simplified if dropping Python2 support. E.g. With latest Python3 `pylint` it's starting to suggest changes that result in invalid syntax for Python2.

**Comment by Lestropie** [comment]
Started branch `drop_python2_support`; the first commit is actually just `pylint` changes, but should nevertheless use that as a starting point for removing Python2 support entirely.

**Comment by bjeurissen** [comment]
I was informed that ``#!/usr/bin/python3`` and out-of-the-box availability of python3 are problematic on macOS versions that we still support, e.g. /usr/bin/python3 does not exist on macOS Mojave and earlier.

**Comment by bjeurissen** [comment]
This weekend, I upgraded to macOS 12.3 and now python2 has been completely removed (https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python).

This means no more 'python2', but also no more 'python'... As a result, anyone trying to build and use our stable branch on macOS 12.3 will run into "env: python: No such file or directory". The dev branch (and future release) should not have this problem.

**Comment by Lestropie** [comment]
That's reason to contemplate promoting hard-coding to Python3 as part of `3.0.4` rather than `3.1.0`. The alternative is to recommend that users themselves create a softlink `python` pointing to `python3`, but the fact that this is not done automatically on that system suggests that there may be some other good reason for not doing so, which would then be circumvented by our advice.

**Comment by dchristiaens** [comment]
I concur. The safest option by far will be to use `#!/usr/bin/python3` or `#!/usr/bin/env python3` in all scripts.

Any objections to speeding this up to the 3.0.4 release?

**Comment by bjeurissen** [comment]
I think we should bite the bullet go for either:

1) ```#!/usr/bin/python3```

or

2) ```#!/usr/bin/env python3```

Both mean python2 will be no longer supported (which I think is a good thing).

The first one might break if there is no OS-provided python3. Maybe this can be an issue on HPC machines?

The second one might not be ideal for shipping it as an OS package (like our Debian and ubuntu packages).

**Comment by bjeurissen** [comment]
Could we go for option 2 and leave the other option as the responsibility of package maintainers?

The idea is that an OS provided package should always use ``#!/usr/bin/python3`` as this points to python3 as provide by the OS, whereas ``#!/usr/bin/env python3`` could just point to whatever a user has set up.

**Comment by jdtournier** [comment]
> Any objections to speeding this up to the 3.0.4 release?

As I mentioned in #2539, I'm not comfortable with making this change for 3.0.4. I do think we can provide a simple quick fix for macOS users though, in the form of a `python` symbolic link in the `bin/` folder pointing to their `/usr/bin/python3`. It's a bit of a hack, but frankly, anything we do at this stage is a bit of a hack... 

Something like this ought to do the trick, right?
```
which python || ln -s /usr/bin/python3 $(dirname $(which mrconvert))/python 
```
Basically, if we can't find a `python` executable, add the symbolic link to their MRtrix install. As long as there is no pre-existing `python` executable, that's unlikely to interfere with anything else. We have to be careful though, this could wreak on older systems where `python` is expected to be `python2`...

**Comment by jdtournier** [comment]
As to whether to invoke via `/usr/bin/env` or not, I'm happy to stick with the `env` approach, since that leaves users with the flexibility of using whichever version they might prefer (e.g. their `miniconda` install or something). Our tools are not a security risk or essential for healthy system function, so allowing a different interpreter isn't going to cause dramatic issues for anyone. Package maintainers may take a different view, and if they chose to modify these, that's up to them and fine by me, and it shouldn't be a difficult change to implement.

**Comment by dchristiaens** [comment]
If you think it's better to wait until 3.1 that's OK for me, but at some point we will need to rip the bandaid off...

That line of code seems right. Would you want to add this to the `configure` script or simply add it to the user docs?

**Comment by jdtournier** [comment]
> If you think it's better to wait until 3.1 that's OK for me, but at some point we will need to rip the bandaid off...

I'm hoping 3.1 won't be too far off... :crossed_fingers: 

> That line of code seems right. Would you want to add this to the configure script or simply add it to the user docs?

I think this one should be documented in the wiki somewhere. It's not appropriate for the reference docs (depends on the version of the OS, not on the version of MRtrix...).

**Comment by Lestropie** [comment]
Discussion regarding shebang should go to https://github.com/MRtrix3/mrtrix3/issues/2261.

**Comment by Lestropie** [comment]
I've recently spotted a couple of vestigial references to Python2 support, so this could do with one more scroll through the Python API prior to `3.1.0`.
