### ISSUE TITLE
FODs and b-values

### ISSUE THREAD

**Issue by DimitriosGk** [MRtrix3/mrtrix3#2050]
Hello,

Thanks a lot for a great and useful software. 
Lately I have been using MRTRIX for FOD analysis on high angular and spatial resolution diffusion data of primate brains. As my intention on this analysis is a bit different, I would like to have an input on the following:  
Going through the publications, and (very fast) through the code (and the matlab code here: https://github.com/jdtournier/csd), I wonder where exactly the b-values are used in the kernel or the FODs calculations using CSD (msmt and fa). In my tries, the b values changing to random high or low numbers (for example, from 0 5000 5000 5000... to 0 10000 10000 1000..) didnt show any difference in the resulting FODs or kernel  (as I actually expected, as the 'effect' of the real b-value lies withing the DW data themselves): 
<img width="672" alt="Screenshot_2020-05-08_18-51-06" src="https://user-images.githubusercontent.com/29710018/81430373-94a54080-915f-11ea-927d-7489285453ba.png">

To put it in a simpler context, assuming a dataset of for example 60 orientation-depended values  and 60 corresponding orientations (no b-values), in theory, could I use MRTRIX to get the FODs with CSD without a problem?

Thanks in advance,
Best regards,

Dimitri

**Comment by bjeurissen** [comment]
Indeed, the actual b-values are not used in the CSD calculation! CSD uses a response function which describes the signal at a constant b-value for an ideal single fiber WM voxel (agnostic to what the actual b-value is) . It then performs a spherical deconvolution using the signal measured in each voxel and the response, resulting in the WM FOD. Changing the b-values in the header will affect neither the response, nor the FOD as the measured signal also does not change.

If you want to see the effect of using different b-values you should _acquire your data_ using different b-values rather than just changing them in the header.

On a different note: GitHub issues are not the right place to raise questions not related to the development of MRtrix. Instead, use the community forum at https://community.mrtrix.org.

**Comment by DimitriosGk** [comment]
Thanks a lot! 
I just used the different b values to prove myself the point, as you said it all comes to the measured signal. I will make sure to use the right forum in the future.

Best regards,
Dimitri
