### ISSUE TITLE
Image::Info: Better usage

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#210]
Since we did the `Image::Info` / `Image::Header` class redefinitions a while ago, I still feel as though there's a lot of places that are not quite up-to-date.

For instance: Class constructors that are templated to receive some '`InfoType`' class; these should in principle be able to be constructed by casting back to the base `Image::Info` class, unlike the old `DataType` interface that was implemented separately for a number of classes. This would however require virtualizing any `Image::Info` functions that may be overloaded. There's also some classes that don't derive from `Image::Info`, but do provide an `info()` function, so you would get a type conversion error unless you pass the result of `info()` to the constructor.

One place this kind of thing often trips me up is in constructing an `Image::Header` from an `Image::Info`; you currently have no choice but to construct an empty header, then go `H.info() = template_info;`. That one's an easy fix, but I wonder if it's worth a more thorough look-through / discussion.

**Comment by jdtournier** [comment]
Yes, I've often wondered whether there is a cleaner way around this... 

The answer is, there is. At least in terms of usage - the fix itself is messy. Basically you'd need to implement separate constructors for the different types that need to be handled differently: one for an InfoType, one for an Image::Header, etc. But these will need to be templated, since there is no such thing as an `InfoType`... To do this, you'd need to bring in [SFINAE](http://en.cppreference.com/w/cpp/language/sfinae) to allow the compiler to figure out which constructor to use. To do this right, we'd need to provide some struct/function that can used to unambiguously identify a class as an InfoType, a BufferType, a VoxelType, etc. _at compile-time_. The simplest thing there is to invoke various members that you expect to be provided by that type and not the simpler types. It can be done, but it's messy stuff to implement. I had a go at this a while back, and decided it wasn't worth spending the time on it - maybe we could revisit if you feel very strongly about it? But bear in mind it's not necessarily going to make the code any easier to read or write...

> This would however require virtualizing any Image::Info functions that may be overloaded.

There is no way we're going to make any of these calls virtual... Many of them are invoked in tight loops, and the overhead of the function call can make a big difference. It's just not worth it. We could make some of the non-performance critical calls virtual, but there'd be no point if you can't make _all_ the over-ridable methods virtual...

**Comment by Lestropie** [comment]
Personally I was thinking more along the lines of making the constructor explicit, and therefore forcing the programmer to pass the output of the relevant `info()` function to the constructor. For any classes that don't derive from `Image::Info`, instead of a const reference to the base class that function would instead need to pass a const reference to an internal `Image::Info` member.

**Comment by jdtournier** [comment]
Ah, OK. I guess there's no harm in adding a constructor for `explicit Header (const Info&)` to the `Header` class. Even those classes that don't have an `info()` function can be used with a construct like

    Image::Header header (Image::Info (other_class));

since the `Image::Info` constructor is templated... Do you want to do this?

**Comment by jdtournier** [comment]
Closing since this won't be relevant after #225...
