### ISSUE TITLE
CI: Test different Qt versions

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2120]
Have raised previously, but it seems to have [bitten us](https://community.mrtrix.org/t/mrtrix-3-0-1-update-errors/3864) after all.

CI should ideally test the most recent Qt4, the most recent Qt5, and any prior Qt5 versions where API changes have been introduced.

**Comment by Lestropie** [comment]
Linking to #2121.

**Comment by bjeurissen** [comment]
One could also consider dropping Qt4 support. I think any distribution that supports gcc5 and up also supports qt5, as qt5 predates gcc5 with 2-3 years.

**Comment by jdtournier** [comment]
I'd also be minded to drop Qt4 support - I doubt it's even supported by the maintainers themselves anyway.
But as we currently still support Qt4, that was definitely a goof on my part...

**Comment by bjeurissen** [comment]
I've had a look at packages.ubuntu.com, and the oldest version that we can reasonably expect people to run is 16.04, which comes with GCC 5.3.1 and Qt 5.5.1. So requiring Qt>=5.5, might be sensible.

**Comment by bjeurissen** [comment]
For Debian, the oldest supported version that comes with GCC>=5 appears to be stretch, which comes with GCC 6.3 and Qt 5.7.1. For fedora, it is 22, which comes with GCC 5.3.1 and Qt 5.5.1. So I have the impression that a distribution with GCC >= 5, but Qt < 5.5 is pretty hard to find.

**Comment by bjeurissen** [comment]
> I'd also be minded to drop Qt4 support - I doubt it's even supported by the maintainers themselves anyway.

Support for Qt4 ended on December 19th 2015: https://www.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year

**Comment by bjeurissen** [comment]
Also had a quick look at centos, as it seems to be popular for scientific computing and at universities. There, gcc>=5 is only included since the very latest release (8), which comes with Qt 5.12.5. The first version that would be able to compile MRtrix using packages from the package manager is version 7 as it comes with clang. There Qt is at 5.9.7.

So I have the impression that we can really rely on the availability of Qt>=5.5 as soon as a C++ compliant compiler comes with the distribution.
