### ISSUE TITLE
Changelog missing for 3.0.1

### ISSUE THREAD

**Issue by gdevenyi** [MRtrix3/mrtrix3#2124]
There are 116 commits and ~1000 changed files 3.0.0 to 3.0.1.

Could the developers please provide a changelog in the release page of github?

Slightly related, please consider using https://semver.org/ for future versioning to assist to understanding what a release changes. Thanks!

**Comment by bjeurissen** [comment]
The release announcement and detailed changelog are here: https://community.mrtrix.org/t/mrtrix-3-0-1-release

As far as I can tell we already adhere to the semantic versioning principle: 3.0.0 --> 3.0.1 was a bugfix release.

**Comment by jdtournier** [comment]
Yes, `3.0.0` was our final move from beta to proper release, and as part of that we switched back to semantic versioning. Maybe the confusion is that there was a big switch between the ` 0.2.X`, then `0.3.X` series (which became known as _MRtrix3_), and the 'sudden' jump to `3.0.0`, which is really because this is our first 'proper' release, but calling it `1.0.0` didn't feel like a good idea when that branch had become known as _MRtrix3_...  There were also too many release candidates, which didn't help the situation.

But yes, the plan is to stick to semantic versioning more carefully in future now that the project is more widely used.

Regarding the changelog, yes, we should link to it in the release page. I think this had come up in discussions before, and we forgot about it. Thanks for raising it.

**Comment by Lestropie** [comment]
Regarding the large number of changed files: this is due to an automated update of the copyright notice at the head of each file (#2053). The volume of practical changes in `3.0.0` -> `3.0.1` is much smaller.

I've also added to our documentation for how to perform updates in the future, instruction to add to the description of the GitHub release hyperlinks to the forum update announcement and changelog; so we should consistently include those links for all updates from now on.
