### ISSUE TITLE
Provide example image with MRtrix

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#227]
Can't remember where the suggestion came from, but don't think it was mine.

If an example image was provided with MRtrix within the code repository (would need to be a small-ish image, but preferably still 3D), it would allow downloading the package and demonstrating / testing it without requiring access to image data.

Thoughts?

**Comment by draffelt** [comment]
Sounds like a good idea to me

**Comment by jdtournier** [comment]
Definitely a good idea. This was mentioned a while back on the forum, and I've even received data from a user specifically for this purpose. Haven't had a chance to look into it yet though.

One thing though is that I'd rather not have such a large chunk of data be part of the repo. We should host it elsewhere with a link to it from the wiki. I think the github.io pages might be suitable for this - it's where the doxygen developer doc is hosted, it accepts straight uploads of stuff. Not sure whether there are space restrictions though, although I just noticed some stuff on GitHub about large file support...

On that front, I was also thinking that the testing stuff might be better hosted on a separate repo, since the testing data may amount to a fair bit by the time we add tests for everything... Would be trivial to do using the modules framework.

**Comment by jdtournier** [comment]
Actually, on second thoughts we should just push the data to a different repo, maybe 'mrtrix-data' or something. Assuming we don't keep changing the data all the time, it shouldn't grow too massively...(?)

**Comment by jdtournier** [comment]
OK, I think we have a winner. We'll create a new repo with essentially just a readme, and [create a release from it, which can include binary data, with no limits on file size](https://help.github.com/articles/creating-releases/). What do you think?

**Comment by jdtournier** [comment]
This has been beautifully addressed [Marlene Tahedl](by http://community.mrtrix.org/t/mrtrix-tutorial-available-on-osf/1942?u=jdtournier) - closing.
