### ISSUE TITLE
mrview: dixel view on Apple M1

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#2281]
Trying to load a diffusion weighted data set using the dixel view to inspect the raw signal results in a crash on Apple M1.

Is this related to the issues with the pseudo tube rendering reported #2247 (suspected to be the consequence of using geometry shaders on Apple M1)?

**Comment by Lestropie** [comment]
Yep, the dixel render [uses a geometry shader](https://github.com/MRtrix3/mrtrix3/blob/3.0.2/src/gui/dwi/renderer.cpp#L247-L250). The "blocky" appearance is achieved by calculating the normal on a per-triangle basis rather than a per-vertex basis. Achieving the same without a geometry shader, i.e. doing it instead in the vertex shader, would require a lot of vertex duplication.

**Comment by bjeurissen** [comment]
Just noticed that disabling slab visualization when rendering fixels, also results in a crash.

**Comment by bjeurissen** [comment]
Using Big Sur 11.5 and 11.6, I can no longer reproduce this issue (dixel view crash).
