### ISSUE TITLE
dwibiascorrect: usage info misleading

### ISSUE THREAD

**Issue by crossmanith** [MRtrix3/mrtrix3#2292]
The usage message states:
**dwibiascorrect [ options ] algorithm ...**
This way the gradient table option is ignored which leads to an error because the data isn't identified as diffusion data.

The documentations on the website states:
**dwibiascorrect algorithm input output [ options ]**
This way dwibiascorrect works as expected.

-  OS: Ubuntu 20.04.2 LTS
-  MRtrix 3.0.2-65-g6e74de10

**Comment by Lestropie** [comment]
Thanks for the report @crossmanith. There are all sorts of issues that arise with the command-line parsing of *MRtrix3* Python scripts due to my manipulation of the existing `argparse` module. Ideally I'd write the whole thing from scratch (#1608)... 

Once you bring up the inline help page for a specific algorithm (e.g. "`$ dwibiasocrrect ants`"), the "`[options`]" item appears after the algorithm selection, which works; it's only the help page for the wrapper script ("`$ dwibiascorrect`") that shows it in the wrong place (as do a couple of other scripts that use the same interface).

#2293 should resolve the issue.

Cheers
Rob
