### ISSUE TITLE
MRview: Ability to set background colour

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#241]
Would be handy esp. in the case of the connectome tool for generating figures for print that have a white background instead of black.

**Comment by jdtournier** [comment]
Agree. All it would take is modifying `window.cpp`, line 1207, to read values from the config file. Could also add a UI option for it if you want, all it would need to do is call `gl::ClearColor()`...

**Comment by rtabbara** [comment]
@Lestropie @jdtournier You should now be able to select the background colour via the View menu. I also initialise the default colour from the newly added config. parameter ImageBackgroundColour (feel free to rename this).

**Comment by jdtournier** [comment]
Seems fine to me... :smile: 
![screenshot from 2015-05-12 09-41-48](https://cloud.githubusercontent.com/assets/3221000/7583194/67e4dc58-f88b-11e4-8980-035f34dcd71d.png)

Just need to document the config file option so it shows up on the wiki. You just need to add a few comments in the format `//CONF ...` - lots of examples in the code...

**Comment by rtabbara** [comment]
Comments for new parameter added.

**Comment by thijsdhollander** [comment]
Works really well; setting a non-grayscale background in combination with a grayscale image is actually very handy for navigation when specific thresholds are applied. :+1: 

...which made me wondering: shouldn't the threshold settings in the `View options` tool also be available/applicable to the non-`Volume` viewmodes (`single slice`, `Orthoview` and `LightBox`)?  Would make the switch between these and the `Volume` mode more seamless when a threshold is applied in the latter.  It somehow also makes sense because the threshold option is also available for these modes in the `Overlay` tool (although of course for even more obvious reasons in that one).

**Comment by draffelt** [comment]
We used to have this feature. I was a big fan. Then Donald took it from us.

I guess you can always load the image up as an overlay, then hide the back
ground image. However this might not be obvious to everyone.

On Wed, May 13, 2015 at 10:42 AM, Thijs Dhollander <notifications@github.com

**Comment by thijsdhollander** [comment]
> We used to have this feature. I was a big fan. Then Donald took it from us.

:confused: 

Anyway... another thing just crossing my mind: it maybe makes sense to have the new background colour setting apply to the new ODF preview "subtool" as well.  That would make the latter's background inherently also default to black (whereas it currently is white), but that actually does seem quite logical to me (being initialised as a separate window now, it actually feels like a tiny viewer of its own).

**Comment by jdtournier** [comment]
> We used to have this feature. I was a big fan. Then Donald took it from us.

:sob:

It was in there before mostly for convenience - it was needed for the volume render, so I just added them and didn't bother disabling them for the other modes. But I have to say, up until now there really hasn't been a use case that justified it, in my opinion. I didn't know you needed it, but more importantly, why? What were you doing with the thresholds & transparency in slice mode?!? The problem I had was that switching from volume render (with thresholds and/or transparency set) to any slice mode meant having to reset those parameters to display the slice as expected - and vice-versa to switch back to volume render. 

In any case, I can see that now that we have the custom background colour option, that feature does make sense - I actually had the exact same thought when checking out this commit... More than happy for someone to put it back in. But I think we'll need to keep separate parameters for volume and slice renders, otherwise it'll be really annoying to use in practice...

@thijsdhollander the ODF preview window does have its own background colour config file option (`BackgroundColour`, defined in `src/gui/opengl/lighting.cpp`). However, there is no way to modify it on the UI. In general though, I don't think we should be using the same colour for both - you will want a black background for the image 99% of the time, and a white background for the ODF preview 90% of the time (I think...). But again, happy for that feature to be added, it makes sense.

**Comment by jdtournier** [comment]
This is good to close - only remaining issue was whether to enable the thresholds for non-volume render modes. Personally, I think they get in the way most of the time, and in the rare cases where you actually want a transparent background for your image, it's trivial to set those voxels to NaN independently and display that.

So I'm going to close this, and if anyone feels strongly about the thresholds issue, please create a new issue for that specifically - but it probably _shouldn't_ be part of the release milestone...
