### ISSUE TITLE
MRview: Button/option to hide main image

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#242]
So often I'm just opening an image to set the FoV then RMB dragging to hide it. Or in volume render mode, you get the expense of drawing the underlying image even though it's all hidden. Would be nicer to just have an 'eye' button (like many of the tools) to skip drawing the main image.

**Comment by rtabbara** [comment]
@Lestropie @jdtournier Main image menu now has a "Show image" item. Let me know if it's what you were after.

**Comment by thijsdhollander** [comment]
Works great; I reckon finding myself in the exact same scenario Rob described quite often as well.

I do think it makes more sense being accessed by a "(crossed out) eye button" in the `View options` tool though.  The image menu seems to be more about properties and navigation through the loaded image(s)?

**Comment by jdtournier** [comment]
I agree with @thijsdhollander , I also went looking in the view menu first, the image menu wasn't the obvious location for me...

**Comment by rtabbara** [comment]
Yes, I agree. I've now moved the Show image item to the View menu.

The only reason why I prefer to keep it in the main menu rather than as a button in the View options tool is so users can make use/are aware of the key shortcut to easily toggle between showing/hiding an image.

**Comment by draffelt** [comment]
Can we keep both the menu and button?

**Comment by rtabbara** [comment]
Done. There's now a Hide button in the View options tool that syncs with the main View menu item.

**Comment by thijsdhollander** [comment]
Works perfect (doing whatever I could, I was unable to break the sync :+1: ).

As part of a little bit of cleaning up here and there, I did make the hide button's position a bit more consistent with all the other tools (actually, 6 out of 7 tools now have it, which is pretty nice -- we now have a viewer that... can *hide everything*!).  To compensate for the fact that it is the only "top row button" in the View tool (whereas all the other tools at least also have an open and a close button), I added some text along the icon, so it doesn't look as lonely in the wide button.

I was wondering: would it be confusing to new/general users that the option is called "Show image" in the View menu?  I mean, rather than "Hide image"? (i.e. like all the hide buttons do)

**Comment by thijsdhollander** [comment]
I unified the appearance (text) and behaviour of the option in the view menu and the view options tool.  There should be no opportunities for confusion any more: it's quite clear now that both refer to the same function, but are simply available in both places for convenience.  Closing the issue here, as it's definitely working well!
