### ISSUE TITLE
is_nan() function

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#2439]
https://github.com/MRtrix3/mrtrix3/commit/a56f6bf40a68c93379d073f0bd6b7358c7b145c9

Seems to me that function `is_nan()` will return `true` if there are *no* NaNs in the data, which is the converse of what's conveyed by the function name. So intend to rename it, or throw in a `!`.

Anyone know of use of this in external projects? *MRtrix3* repo currently doesn't depend on it.

**Comment by jdtournier** [comment]
I'd be happy to remove, especially since Eigen 3.4 now has convenience calls just for that ([hasNaN()](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase.html#ab13d158c900560d3e1b25d85d2d33dd6) and [allFinite()](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase.html#af1e669fd3aaae50a4870dc1b8f3b8884)).

**Comment by Lestropie** [comment]
Looks to me like they've [been there since `3.2.0`](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.2.0).
