### ISSUE TITLE
ODF preview pane: Add system controls

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#245]
On Thij's computer, the ODF preview pane doesn't have the maximize/minimize/close buttons.

**Comment by thijsdhollander** [comment]
This is now fixed in #219 , by using a dock for the ODF preview pane.

On a slightly related note: I also don't have a "x" type close button on the lighting dialog boxes; but it's no issue, since there is a big "X Close" button on those.  I'm no expert in this, but I guess the fact whether system controls are present on a dialog box type of window, is again related to the window manager?

**Comment by jdtournier** [comment]
Yes, I need to make the lighting dialog box a QDockWidget also... This bit is ancient code (predates the current version of MRView by some margin, was originally designed for `shview`).
