### ISSUE TITLE
Lighting dialog box should be a dock widget

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#246]
Dialog for lighting is a normal window, when all other settings boxes in MRView are dock widgets. This makes it inconsistent, but also it doesn't have stay-above-main-window behaviour, and can't be docked.

This will probably impact `shview` as well, which might need to have its main window changed to a QMainWindow (or whatever it's called...).

**Comment by rtabbara** [comment]
Had a go at this in  4835759. <code>GUI::Dialog::Lighting</code> has moved to <code>GUI::LightingDock</code> with corresponding .h/.cpp files also renamed/moved.

For the standalone <code>shview</code>, the lighting panel remains as a QDialog.

**Comment by thijsdhollander** [comment]
@rtabbara : I quickly gave it a test before I'll head off home.  It seems to function well, there's 2 small details that might (or not) be issues:

1) It opens in a docked state.  Was a bit surprised at first because I expected it to "float" by default; possibly because I was used to the behaviour of the old dialog.  Because I was testing with the ODF display tool docked as well, it "popped up" docked underneath, which then actually *did* seem nice to me.  But then reasoning a bit further: if a user undocks the ODF display tool first, and then opens the lighting panel, it also still opens docked to the main window (and that's a bit odd).  So probably it makes more sense to have it initialise as floating...

2) It's maybe also good to bring it to the top of the docking stack whenever the button is pressed; so when one or more tools are used in an undocked state (the preview sub-tool probably being the most likely one), it comes back into view when the user might have "lost" it.

**Comment by thijsdhollander** [comment]
...so on second thought, maybe having it docked by default is actually fair enough for the majority of use cases.  I reckon that this does guarantee (when the ODF display tool or tractography tool are docked in their default state) the lighting controls popping up "near the cursor", which is actually quite handy in practice.  So probably this issue is fixed as it is now...?

Side note: when testing it with the tractography tool, I noticed the "object colour" in the lighting settings is never used... is that correct? (I know the actual colour *can* be set by right clicking on the tractogram's entry in the list)

**Comment by Lestropie** [comment]
> Side note: when testing it with the tractography tool, I noticed the "object colour" in the lighting settings is never used... is that correct?

It shouldn't have any effect in that context; then again, it's trivial to create the lighting settings widget with the object colour control omitted... the solution is left as an exercise for the reader :-P

**Comment by thijsdhollander** [comment]
> It shouldn't have any effect in that context

Why not?  To elaborate: it does have "that kind of effect" in the ODF overlay tool.  If I want overall purple ODFs, I have to use it; if I want overall purple streamlines/tubes, I can't use it; but have to somehow know that I have to right-click in that context. :dizzy_face:  Streamlines don't really naturally trigger my personal natural urge to right click. :wink:

**Comment by Lestropie** [comment]
> Why not?

Because for the tractography tool the colour is set independently for multiple files. It would be better to hide that button for the tractography tool lighting; or even better, give the ODF tool a separate colour control within the toolbar, and remove this functionality from the lighting widget altogether.

**Comment by thijsdhollander** [comment]
> Because for the tractography tool the colour is set independently for multiple files.

Yep, I'm aware that's *how it came to happen*.

> give the ODF tool a separate colour control within the toolbar, and remove this functionality from the lighting widget altogether

Fully agree.  That was basically my point. :wink:

The "object colour" as it's now available in the lighting tool can be whatever we want it to be; but it shouldn't be two entirely different things because the (artificial) context is different.  If it was initially meant to be the colour of the light source, it indeed doesn't apply to any current available functionality (and also should've been called "light colour").  If, however, the "object colour" *is* the object colour, then it should be the object colour. :smile:

**Comment by jdtournier** [comment]
Yes, you're both right. The object colour attribute dates back to when the lighting dialog was designed as part of what is now shview - circa 2008. And I fully agree that it really doesn't belong in the current codebase. I'm all for removing it, and adding a colour button to the ODF tool. We'd also need to add a menu entry to set the colour in shview - unless @thijsdhollander has his way with his suggestion in #272...

Generally, I think this dialog is due a revamp, but I can't justify spending any time on it. The light position controls in particular have always struck me as a temporary solution, but I can't think of a simple yet intuitive alternative...

I anybody feels like having a go, you'd be most welcome.

**Comment by Lestropie** [comment]
Looks like the remaining part of this issue was moved to #408 and then completed.
