### ISSUE TITLE
mrcat segmentation fault when used in revpe_dwicombine

### ISSUE THREAD

**Issue by timpx** [MRtrix3/mrtrix3#251]
using the script ```revpe_dwicombine``` fails for me at line 132 with ```mrcat```.

```
$ mrcat dwi1b0.mif dwi2b0.mif - -axis 3 -debug                                    
mrcat: [INFO] opening image "dwi1b0.mif"...
mrcat: [DEBUG] reading key/value file "dwi1b0.mif"...
mrcat: [DEBUG] sanitising image information...
mrcat: [DEBUG] mapping image "dwi1b0.mif"...
mrcat: [DEBUG] memory-mapping file "dwi1b0.mif"...
mrcat: [DEBUG] file "dwi1b0.mif" mapped at 0x7fcbfea9f000, size 31715712 (read-only)
mrcat: [DEBUG] image "dwi1b0.mif" loaded
mrcat: [INFO] opening image "dwi2b0.mif"...
mrcat: [DEBUG] reading key/value file "dwi2b0.mif"...
mrcat: [DEBUG] sanitising image information...
mrcat: [DEBUG] mapping image "dwi2b0.mif"...
mrcat: [DEBUG] memory-mapping file "dwi2b0.mif"...
mrcat: [DEBUG] file "dwi2b0.mif" mapped at 0x7fcbfcc5f000, size 31715712 (read-only)
mrcat: [DEBUG] image "dwi2b0.mif" loaded
mrcat: [INFO] creating image "-"...
mrcat: [DEBUG] sanitising image information...
mrcat: [DEBUG] creating temporary file of size 0
mrcat: [DEBUG] resizing file "/disk3/mtx-tmpbLneeu.mif" to 63432384...
mrcat: [DEBUG] sanitising image information...
mrcat: [DEBUG] mapping piped image "/disk3/mtx-tmpbLneeu.mif"...
mrcat: [DEBUG] creating RAM buffer for file "/disk3/mtx-tmpbLneeu.mif"...
mrcat: [DEBUG] file "/disk3/mtx-tmpbLneeu.mif" held in RAM at 0x7fcbf8fe0010, size 63431424
mrcat: [DEBUG] image "/disk3/mtx-tmpbLneeu.mif" loaded
mrcat: [DEBUG] voxel accessor for image "/disk3/mtx-tmpbLneeu.mif" initialised with start = 229808, strides = [ -16 -2016 229824 1 ]
mrcat: [DEBUG] voxel accessor for image "dwi1b0.mif" initialised with start = 114904, strides = [ -8 -1008 114912 1 ]
mrcat: [DEBUG] initialising threads...
mrcat: [DEBUG] launching 3 threads "loop threads"...
mrcat: [DEBUG] waiting for completion of threads "loop threads"...
mrcat: [ 98%] concatenating "dwi1b0.mif"...Erreur de segmentation
```

Any ideas?

**Comment by Lestropie** [comment]
... Now that's a weird one. Everything looks sensible, and to make it to 98% before segfaulting... wacky.

I can't reproduce; any chance of getting access to some data?

**Comment by timpx** [comment]
I sent you the data by mail.

**Comment by Lestropie** [comment]
Thanks for the report and the data @timpx. This should now be fixed.

@jdtournier: This traces through to `lib/image/loop.h:471-471`.

**Comment by jdtournier** [comment]
Good get! Took me a while to figure out what the fix was supposed to do... I guess we'd better document more clearly for those not too familiar with the code (ahem, me...) that the loop uses the first image's dimensions to iterate over...

**Comment by jdtournier** [comment]
Actually, on second thoughts, I'm not sure this genuinely fixes it. It won't crash, but does the data get concatenated properly? I'm guessing we're talking about feeding mrcat a bunch of single-volume 4D files? The problem is the loop will include the 4th axis in the loop, which clearly won't match between the (single-volume) current input image and the multi-volume output. Switching the order means it'll only loop over the one volume, but it also likely means that the volume index for the output image will stay stuck at zero... So you'll get the last image as the first volume in the output, and nothing else for the remaining volumes. Is this not the case...?

Assuming this indeed doesn't work as advertised, I think the simplest solution is to pass an Adapter::Subset for the output volume to the threaded loop.

**Comment by timpx** [comment]
Thanks for the fix, this part now works fine for me. However, and I don't know if this is related to the comment of @jdtournier, the ```revpe_dwicombine``` script now fails at the topup step, with the message: 

```
Topup: msg=topup_clp::topup_clp: Mismatch between b0all_crop.nii and config.txt
Command failed: topup --imain=b0all_crop.nii --datain=config.txt --out=field --fout=field_map.nii --iout=b0_topup.nii --config=/usr/share/fsl/5.0/etc/flirtsch/b02b0.cnf
```

**Comment by Lestropie** [comment]
My test data was two images with `dim(3)=8`, and the output data were good. But you're right, now doesn't work properly for multi-3D-volume input. The output volume increment usually happens at `mrcat.cpp:167`: `out_vox[axis] = axis_offset;`; but something's setting `out_vox[3]=0` whenever the `in` volume is only 3D.

Knew I should have branched... might be a good time to make a `mrcat` test script too.

I'll look into that second error @timpx, but it's 1:30AM here and the code is starting to blur :-/

**Comment by jdtournier** [comment]
@lestropie, no worries, I'll take the mrcat issue over from here, try to get it fixed later tonight. And yes, I might as well add some tests while I'm at it...

**Comment by jdtournier** [comment]
OK, last remaining bug in mrcat fixed (and tested) in 8f6544a (tests also now in testing repo). Turned out to be a simple fix...

@timpx, let us know whether that fixes the remaining issues you were having with `revpe_dwicombine`...

**Comment by Lestropie** [comment]
OK @timpx, found a couple of little errors with the `revpe_dwicombine` script (unfortunately I only had one data set to test with when I wrote it); fixed in effe335ca1b.

I'm now having issues at the `applytopup` step (line 192) with your data: `applytopup` fails without any information (even if run with `--verbose`). It does however work if I add `--interp=trilinear` to the `applytopup` call. It _may_ be a RAM issue: I'm only testing on my laptop right now, being a weekend.

So give it a go, and try the modification above if it fails for you as well. I might need to branch in the script depending on whether or not `applytopup` fails if it's a regular occurrence.

**Comment by timpx** [comment]
Thanks to both of you, the ```aplytopup``` step worked fine for me (but taking a long time, I don't know if this is normal), however the script stopped at the ```eddy``` step with error:
```
 what():  eddy: msg=--imain and --mask images must have the same dimensions
```

**Comment by timpx** [comment]
After inspecting a bit more my data, the problem seems to be that the image given to ```--imain``` of ```eddy```, that is dwiall_crop.nii, is 126x124x68x400 whereas the mask is 126x124x69. The lost dimension comes from the cropping, because the dimension of dwiall.nii is uneven (line 155). So I guess a possible fix would be to crop the mask as well?

**Comment by Lestropie** [comment]
Yep, that's the one. Apologies: thought I had committed the fix for this, turns out it was sitting in my git stash...

Unfortunately I haven't been able to test the script in full (still only working off a crummy laptop), but from memory the `eddy` step commenced without error.

**Comment by timpx** [comment]
Now it fails at line 242 (after a day of computation), because field_map.nii is not found, the name actually being field_map.nii.gz, somehow ```topup``` at line 190 compress automatically field_map.nii. I will rerun with the correction.

**Comment by Lestropie** [comment]
Ugh. Sorry about the time it's taking to get this working right; I simply hadn't tested this script other than on the one data set that was given to me, and probably on the one machine at the time.

Unfortunately FSL is not very well standardized in terms of image handling: some commands honour the `FSLOUTPUTTYPE` variable, some don't; some strip the file extension if you specify it explicitly and add their own; some expect a basename with no extension and will erroneously double-up on file extensions if you specify it explicitly; and some change behaviour between software versions in the same command. Makes it a nightmare to interface scripts with.

I'm running the fix on a reduced version of your data (less volumes so it completes faster), and will commit if it works. At some stage I should probably interrogate the FSL binaries in more detail and document the behaviour of each...

**Comment by Lestropie** [comment]
OK, ran all the way through successfully on my system after 02ff4a8a40c833.

If it still borks at your end I'll need to know exactly what version of FSL you have and the value of `FSLOUTPUTTYPE`, so I can modify the script to figure out what file extension `topup` is going to use. Otherwise, thanks for your feedback in getting this script more robust; hopefully more people will have the data to make use of it in the future.

**Comment by timpx** [comment]
Yep, It also worked fine for me with the small correction. Thanks again for all you help.
