### ISSUE TITLE
Scripts: Better on-the-fly cleanup

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#253]
Ran into issues running `revpe_dwicombine` with input images with a large number of volumes; the tmpfs ran out of space. So if -nocleanup is not specified, try to delete some intermediary files as the script executes.

**Comment by jdtournier** [comment]
A bit confused by this one. When you say 'tmpfs', are you talking about the filesystem holding the temporary piped images (which will now typically be a tmpfs), or the temporary folder you create to hold the (explicit) temporaries needed for your script...? If the former, I don't see how you could delete these temporaries, the commands should be doing that themselves. Assuming the latter, I'm guessing this is because you're now creating this folder in `/tmp` also? I think if you're really expecting to hold a lot of large temporary files, this might be a bad idea, you'd be better off storing then in the current folder (maybe providing an option to specify where to store these temporaries?). Issue being that on modern systems, this filesystem is held in RAM, which places restrictions on how much can be stored in there. Also, this could create problems for other processes as RAM becomes scarse.

**Comment by Lestropie** [comment]
In the scripts, I make a temporary directory in the same location as the temporary files used in piping (checking the config files in case the path is set manually), and dump all of my working files in there. But when your two input images are ~ 400MB each, and you have to immediately do axis permuting / format conversions, your 2GB /tmp filesystem runs out pretty quick.

Should be OK if I just clean up after myself a little better. It'd be nice to be able to set the temp path with an option at the command line, but that'll require a full command-line parsing implementation (currently require arguments before options, and all options are argument-less).
