### ISSUE TITLE
mrview isn't working on WSL

### ISSUE THREAD

**Issue by Microdeep-ZL** [MRtrix3/mrtrix3#2536]
I'm using WSL2 (Ubuntu-22.04) to install MRtrix3 (3.0.3) through miniconda. When I run `mrview`, I got this 
>mrview: [WARNING] unable to determine OpenGL version - operation may be unstable if actual version is less than 3.3

I spent a lot of time searching the Internet for a solution. I can't remember where I knew this, but simply adding this line to `.bashrc` can perfectly solve the problem.
```bash
export LIBGL_ALWAYS_INDIRECT=0
```
By the way, I'm using MobaXterm to display GUI. 

Perhaps you can modify the code so that adding that line is automatically done for WSL users? I don't know whether that problem occurs on non-WSL linux.

**Comment by Microdeep-ZL** [comment]
Well, I recollected that this solution is from [here](https://community.mrtrix.org/t/wsl-mrview-could-not-connect-to-any-x-display/4775/4)

**Comment by jdtournier** [comment]
These kinds of recommendations would best be added to the relevant [wiki on the forum](https://community.mrtrix.org/c/wiki/12) -- and indeed it looks like [they're already there](https://community.mrtrix.org/t/installing-on-windows-subsystem-for-linux-wsl/3637/5?u=jdtournier). 

I have no intention of modifying the install for WSL users specifically, since Microsoft has recently added [support for Wayland on WSL2](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps), and that allows `mrview` to work out of the box without any external X11 solution (mobaxterm or similar) - and with full hardware acceleration (the indirect solution basically means use software rendering, and doesn't work for volume rendering). Wayland is only supported on Windows 11, but given this is now an officially supported solution, this is what we will soon be recommending for Windows users, and we will eventually phase out MSYS2 support.

**Comment by Microdeep-ZL** [comment]
I see. Thank you for your reply! 

I also heard the news that WSL now supports GUI apps from [here](https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps). However, I followed the instructions but the problem with GUI display persisted unless I use MobaXterm. I think that's probably because I didn't get the vGPU driver right. I'll have another try with vGPU installation.

**Comment by jdtournier** [comment]
OK, I'm not too sure what I did to get it working, but I don't remember encountering any particular issues at the time... Hopefully you'll get it working OK - and if you do, it would be great to add some instructions for this to the wiki... :wink:

**Comment by Lestropie** [comment]
> `export LIBGL_ALWAYS_INDIRECT=0`

I found that in one circumstance setting this envvar to 1 helped in the case of running `mrview` from a Singularity container (see #2370). Can't really provide input on exactly what it does though.

**Comment by jdtournier** [comment]
Some answers to that question online, e.g. [on StackExchange](https://unix.stackexchange.com/a/1441). 

Briefly, as I understand it: 

Modern Xorg tries to use [_direct rendering_](https://en.wikipedia.org/wiki/Direct_Rendering_Infrastructure) where possible, whereby the application dispatches OpenGL commands directly to the GPU, bypassing X11 entirely. This cuts out a lot of unnecessary round-trips and associated dead-time, and also a lot of unnecessary copying of data around the place, since a lot of data transfer can now happen by [DMA](https://en.wikipedia.org/wiki/Direct_memory_access), etc. This of course won't work for remote connections or any situation where direct communication between the application and the GPU is problematic (e.g. on a Virtual Machine). 

With indirect rendering, OpenGL interactions happen over the X11 protocol - basically a network protocol. For OpenGL, this requires the use of the [GLX extension](https://en.wikipedia.org/wiki/GLX), which basically allows OpenGL commands to be forwarded over X11. But crucially, GLX only supports OpenGL versions up to 1.4 (I think). Since MRView uses OpenGL 3.3, the GLX is essentially no use in this situation. 

Until recently, that was the end of that - no X11 rendering (whether remotely or via a virtual machine with a 3rd party X11 solution). More recent versions of [mesa](https://www.mesa3d.org/) however come with software rendering support for OpenGL versions 3 & 4, which means that applications can render in software, and pass the rendered frames over X11 - this means that there is no need for explicit X11 support for OpenGL, it's just passing a fully-rendered frame over the wire (note in this case that the rendering is done on the system running the application, not on the system where the results are to be displayed, as would happen using GLX). 

My understanding is that by forcing the use of indirect rendering, requesting an OpenGL 3.3 context results in the use of the mesa software renderer, which at least has the merit of supporting OpenGL 3.3.

But I've also noticed that this doesn't always work. My guess is that this requires both the client and server to both support this particular use case - i.e. both ends of the connection needs to run sufficiently recent versions of mesa. It's just a hunch though, there may be other things that come into play here...

**Comment by Microdeep-ZL** [comment]
Sorry for the late reply. Thank you so much for your advice! Now I'm able to run GUI apps directly from WSL without using MobaXterm or any kind of forwarding!

I got WSLg installed by running `wsl --update` in cmd (This requires administrator privilege). To confirm the successful installation of WSLg, you can run `where wslg` in cmd. I can even access my NVIDIA GPU from WSL by `nvidia-smi`. The output is different from what I would get from typing `nvidia-smi` in cmd.
