### ISSUE TITLE
 dwi2response (all other python2 wrappers)

### ISSUE THREAD

**Issue by pkashya** [MRtrix3/mrtrix3#2539]
I'm on the latest MacOS and have reinstalled mrtrix

I get the following error when running dwi2response:

(env: python: No such file or directory)

I got the same error when I was trying to configure-build the software, but just used python3 to execute those.
For wrappers that use python, is there a way to ensure that mrtrix functions uses python3 instead of the deprecated python2 for all future uses?

I tried the python3 -m venv option as well, with no luck.

**Comment by jdtournier** [comment]
This is unfortunately not trivial to fix in a way that works on all systems -- see previous discussion on the topic on #2047. 
If you have any suggestions for how to fix it universally, we'd love to hear it!

For now, your best option is to create a symbolic from `python` to your system's `python3` executable. The simplest is to put it in the same folder as your current `python3` (presumably `/usr/bin`), but that requires admin privileges. If that's not possible, you can also put it in any folder on your `PATH`. 

Tagging @bjeurissen & @dchristiaens as they're probably best placed to advise...

**Comment by pkashya** [comment]
Thanks for the swift response, the macOS update deletes python2

'brew link python' cannot solve the issue

Neither can we reinstall python2 :(

Any other ideas?

**Comment by bjeurissen** [comment]
You could make a symbolic link (inside a folder that is in your PATH, e.g. ``/usr/local/bin``) that links ``python`` to your ``python3`` binary:

```
 cd /usr/local/bin
 sudo ln -s /usr/bin/python3 python
```

Note that you need admin rights to write to /usr/local/bin.

Alternatively you could create such link in any other directory that is in your PATH (or create it in an entire new directory and add that to your PATH).

Note that this is a known issue that will be fixed in one of the upcoming releases (if not 3.0.4, then 3.1.0, although given the impact I am hoping for 3.0.4).

**Comment by jdtournier** [comment]
> Note that this is a known issue that will be fixed in one of the upcoming releases (if not 3.0.4, then 3.1.0, although given the impact I am hoping for 3.0.4).

All for it, but do we have a fix yet...? If so, let's discuss it on #2047 and add that to the 3.0.4 milestone.

**Comment by dchristiaens** [comment]
> How does one install python2 (called as python) on new MacOS?

You do not need to install `python2`. All Python code in MRtrix is already compatible with `python3`.

The issue arises because our scripts look for an executable named `python` in your PATH. On recent versions of macOS, no such executable exists because Apple has chosen to make the version handling explicit, i.e., users need to call `python3` explicitly.

To fix this issue on your system, you need to create a symbolic link in your PATH that passes any call of `python` onto `python3`. @bjeurissen gave the instructions to do so in his reply:

> You could make a symbolic link (inside a folder that is in your PATH, e.g. `/usr/local/bin`) that links `python` to your `python3` binary:
> 
> ```
>  cd /usr/local/bin
>  sudo ln -s /usr/bin/python3 python
> ```
> 
> Note that you need admin rights to write to /usr/local/bin.

---

> Also, #2047 is > 2 years old...is the fix going to be released sometime this year?

I can't make any promises about _this_ year, as in the next 2 weeks, but 3.0.4 should be out very soon.

**Comment by pkashya** [comment]
Fair enough, 2 weeks is too soon :)
I'll try out the symbolic link and also prefix the dwi2response with python3 later this afternoon and keep y'all posted.

Thanks much for all the prompt support, really appreciate it.

**Comment by jdtournier** [comment]
OK, a few things:

First, I don't think the fix is going to be in 3.0.4. If we make that change, there's a very good chance things will fall apart on older systems and HPCs. We'll consider it for 3.1.0.

Next, one simple solution, assuming you have write access to your MRtrix install, is to place the symbolic link in there. This command should do the trick:

**Comment by pkashya** [comment]
Alrighty, the symbolic link doesn't work either or if I prefix the dwi2response with python3

This is the error I get

(xcode-select: Failed to locate 'python', requesting installation of command line developer tools.)
>(https://developer.apple.com/forums/thread/704099)
Command line tools is looking for the python binaries that do not exist...

Thoughts now? Please let me know if y'all wanna zoom (if free the next few hours)

**Comment by pkashya** [comment]
@dchristiaens can you please "re-open" this issue as its not resolved...

**Comment by jdtournier** [comment]
Hi @pkashya, 

Sorry for the slow response - I still have a mountain of marking to get through... 

It's annoying that we can't find a solution that works... Were there any issues when you ran the command I suggested? No error messages or anything? 

Also, what does `which python` report? 

Finally, it might be worth thinking about whether using this symbolic link approach is somehow being thwarted by macOS's security policies...

**Comment by pkashya** [comment]
Hey @jdtournier,
 
Please do not apologize, its the weekend and y'all have been very prompt with the replies.

which python: /Users/pk218/mrtrix3/bin/python
Also, I did not get an alert on System Settings > Security 

which python3: /usr/local/bin/python3

ln -s "$(which python3)" "$(dirname "$(which mrconvert)")/python":
(ln: /Users/pk218/mrtrix3/bin/python: File exists)

Mrtrix3 requires command line tools with python, but the MacOS does not allow python packages....

**Comment by jdtournier** [comment]
OK, great, it all makes sense. The symbolic link we initially created (with [these instructions](https://github.com/MRtrix3/mrtrix3/issues/2539#issuecomment-1344469693)) was pointing to a non-existent `python3` executable - it needs to point to `/usr/local/bin/python3` (which is odd, that's not where I would have expected a _system_ executable to reside, but hey). The second attempt failed because the symbolic link we initially created is still there, and it won't just overwrite it. All you need to do is remove it first:
```
rm /Users/pk218/mrtrix3/bin/python
```
then try again with the later command (in [this post](https://github.com/MRtrix3/mrtrix3/issues/2539#issuecomment-1348176283)):
```
ln -s "$(which python3)" "$(dirname "$(which mrconvert)")/python"
```

**Comment by pkashya** [comment]
Amazing, it works!!
I should've removed the old link.
Its all running now, thanks for all your help:)

Really appreciate it!

I'm running into some issue with 5ttgen now, will try to debug it myself or will post another request here...
