### ISSUE TITLE
mrview: automatically save generated image

### ISSUE THREAD

**Issue by lizannea** [MRtrix3/mrtrix3#2563]
Dear MRTrix experts, 

I’m using MRtrix 3.0.3 to create a connectome through a scripts that loops through a large number of participants. To be able to go through the QC more sufficient, I was wondering if it is possible to automatically save an image created by mrview. If this is a possibility, what would this command line be? 

It would be very useful to include the mrview command and a command that would rewrite the mrview generated image to a file. 
Thank you!

@civier

**Comment by bjeurissen** [comment]
Yes, this is possible through the combination of the ``-capture.*`` options and the ``-exit`` option from the ``mrview`` command, e.g.

 ```
mrview <options to load images and set things up> -capture.folder <output folder> -capture.prefix <output prefix> -capture.grab -exit
```

Consult ``mrview -help`` for more details.

Please repost your question on the community forum @ https://community.mrtrix.org/ where all users can see it and users/developers will be able to answer in more detail.

**Comment by Lestropie** [comment]
The catch here is that not every single interactive control in `mrview` has a corresponding command-line option. Ideally we would change the implementation so that this is always the case (#1438). But if there are isolated functionalities that you need for a specific project, we can potentially provide assistance regarding how to implement just those.

**Comment by lizannea** [comment]
Thank you for your response! I'll repost my question in the community forum with your responses and the needed functionalities.
