### ISSUE TITLE
Use Eigen classes for the interpolators

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#262]
This will only be relevant when #225 is merged - this is just me making sure I don't forget...

Most interpolators perform a number of multiply-add operators per `value()` call (8 for trilinear, 64/84 for cubic - depends how it's done). If we use Eigen's vector dot product, there is scope for speeding this up, since Eigen will vectorise these operations using SSE instructions if available (which will be the case on any vaguely recent CPU). This could potentially benefit interpolation-heavy applications (tckgen in particular). Worth looking into...

**Comment by draffelt** [comment]
Good for registration too

**Comment by Lestropie** [comment]
This was done a while ago for the cubic interpolator. Not bothering to do it for sinc since it's rarely used. Unfortunately the change for the linear interpolator gives no improvement for 3D sampling, and only maybe ~10% improvement for 4D sampling using `row()`. Though someone else might envisage a better implementation...?
