### ISSUE TITLE
MRView : ODF Tool : Lazily compute interp. values

### ISSUE THREAD

**Issue by rtabbara** [MRtrix3/mrtrix3#268]
It appears that the ODF Tool is recomputing interpolated values *every* draw call, irrespective of whether or not there has been a change in the underlying image/projection. Might be worth caching the interpolated values in a buffer, and then using a flag (.e.g <code>bool interp_values_dirty</code>) to trigger when an update should be performed ?

**Comment by jdtournier** [comment]
Well that depends what you mean. The ODF values themselves (i.e. their SH coefficients) are really cheap to fetch compared to the computation that's about to take place on them. What happens then is a large matrix multiply that'll amplify the amount of data massively, from ~45 coefficients to several hundred (potentially several thousand) vertices. We could buffer that, but then on a large FoV (when buffering would be most interesting), this could turn out to be quite a chunk of RAM. For instance, when fully zoomed out with the HCP data, you'd be talking about caching several kilobytes for each of the ~200×200 voxels, which would come out at ~100MB. I guess that's not really prohibitive, but the point is under certain circumstances that might be an issue.

These vertices are then fed through to the GPU, which then has to do a bit more work to compute surface normals, etc. It would be interesting to know whether that's the bottleneck or whether it's the previous CPU-side computations that slow things down. I guess buffering the results is actually the easiest way to find out...

Finally, I'm not sure how much difference this would make in actual use. This would help when changing the crosshair position or windowing the main image, but any other operation would modify the view, where you couldn't use the buffering. We had a discussion recently about speeding up the CPU-side computation with @lestropie (can't find it now), I reckon this would be more beneficial in general. That said, I'd like to see the buffering implemented if only to find out where the bottleneck is: if you get a substantial speedup, it's worth trying to speed up the CPU-side computations, using larger matrix-matrix operations (especially using Eigen when it comes in) and multi-threading. Otherwise, it's all GPU-bound anyway, so not point in either buffering or trying to speed things up any other way...

**Comment by rtabbara** [comment]
<blockquote>
This would help when changing the crosshair position or windowing the main image, but any other operation would modify the view, where you couldn't use the buffering
</blockquote>

Might be the graphics card that I have, but I was encountering quite a bit of lag even when doing this. The actual use case was that I had the ODF preview up and was just clicking to cycle through different voxels.

Just quickly profiling the ODF tool to look at CPU computations, I found: 

* about 40% of time (frac. of total CPU instructions performed) was attributed to <code>DWI::Renderer::compute_r_del_daz</code>
* but a whopping 48% was attributed to <code>ODF::get_values</code>

So I'm wondering even though you're probably (i.e. almost surely) right in that the bottleneck is GPU-bound, we could at least cache the interpolated SH coefficients for a relatively low-cost vs. reward?

**Comment by jdtournier** [comment]
@rtabbara: OK, these numbers are indeed quite striking... Can I just check: these timings were produced with a release build, right? Debug builds tend to slow down drastically for the image fetch calls, I don't think they get optimised away (at least not to the same extent).

The other thing to rule out is that these calls all relate to the ODF tool particularly, and don't have anything to do with fetching values for the main image or anything. And that this has nothing to do with disk IO latency because these data haven't been cached in RAM yet.

But assuming these numbers are representative, this would indeed be worth looking into. Happy for you to have a go, shouldn't be a great deal of work, and it'll give us a more definite idea of where the bottlenecks are. I guess you could try caching the FOD coefficients first, see what difference that makes, then try caching the computed vertex values, and we'll compare all that with the current performance.

**Comment by rtabbara** [comment]
@jdtournier Yep, using release build. Just gave this a whirl and found that while caching the SH coeff. did help, it's only until the we cache the vertices that a substantial speed-up is observed. It definitely helps, but I agree that for such a narrow use-case, the benefit probably doesn't outweigh the large memory cost.

**Comment by jdtournier** [comment]
That's great to hear. So we know the CPU is a bottleneck, and it would be worth accelerating the SH coefficients -> vertices computations at some point in the future. And I'm assuming you're still using the standard-issue Quadro card? So it's not a case of your GPU being super-fast. That's useful information to have. We might revisit how to make the CPU stuff faster in future. I'll create a new wishlist issue for that, and we'll close this one off...
