### ISSUE TITLE
MRView: shview menubar not showing when compiling against Qt 5.2

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#272]
This is a bit of a problem since that's the version that ships with Ubuntu 14.04...

**Comment by thijsdhollander** [comment]
Suggestion: if a "fundamental" solution to this problem is infeasible, avoid the problem altogether by doing away with the menu, but including the small set of options in the window itself; i.e. a bit like how the ODF preview tool in mrview looks now (but with the slightly extended set of controls needed for all of shview's functionality).
For most functions/options, this would then even result in them being accessible without that one extra mouse click to open the menu. :smirk:  ...and shview's use would simply be that little bit more straightforward/intuitive for those used to working with mrview.

**Comment by jdtournier** [comment]
Well, let's just double-check whether the shview menu worked before all the changes for the ODF preview. If it worked before, we should figure out what screwed it up and fix it, that'll probably be much less work. Unless you're really keen on doing this - and you have a lot more time on your hands than I do...

Remember this is only an issues with Qt 5.2 - might even be specific to Ubuntu 14.04, for all I know. I don't think we need to redesign the whole thing just to get around a bug in a specific version of a specific distro...

**Comment by thijsdhollander** [comment]
Fully agree.  The suggestion was only meant to cater for the case where we somehow really can't figure out the fundamental issue at hand.  Otherwise, it can be considered a wish list item, but nothing currently spend time on really...

**Comment by thijsdhollander** [comment]
So after upgrading to Ubuntu 16.04, and `mrview` mentioning that Qt 5.5.1 is being used, the problem is effectively gone.

**Comment by jdtournier** [comment]
Guess we should close this off as `wontfix` then...
