### ISSUE TITLE
Python imp module is now deprecated

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#2731]
According to the [documentation for the `imp` module](https://docs.python.org/3.11/library/imp.html), it is now deprecated:

>Deprecated since version 3.4, will be removed in version 3.12: The [imp](https://docs.python.org/3.11/library/imp.html#module-imp) module is deprecated in favor of [importlib](https://docs.python.org/3.11/library/importlib.html#module-importlib).

This is used in the `mrtrix3.py` module to locate and load the main `mrtrix3` module. Already [causing trouble on the forum](https://community.mrtrix.org/t/batman-tutorial-step-2-4-zsh-command-not-found-dwipreproc/7035/5?u=jdtournier). We need to fix this asap...

**Comment by Lestropie** [comment]
[Looks](https://docs.python.org/2.7/library/importlib.html) to me like `importlib` does not have the requisite functionality in Python 2, which is still supported on `master`. So need to choose between:

-   Embed logic in `bin/mrtrix3.py` to use `importlib` in Python3 and `imp` in Python2
-   Drop Python2 support on `master` and tag `3.0.5`.

Can change separately on `dev` since Python2 support has already been dropped there (#2215 pending check in #2534).

**Comment by jdtournier** [comment]
I reckon we'll need to support both versions for some time. I've had a crack at doing this in #2735, and it's too ugly. I would vastly prefer it if they didn't keep changing things, but there we are...

I'll close this for now, we can discuss on #2735
