### ISSUE TITLE
tck2connectome with -metric meanlength option

### ISSUE THREAD

**Issue by timpx** [MRtrix3/mrtrix3#274]
meanlength option gives the mean of the length of the tracks between two regions, right? When I am using this option, the highest value of the matrix is 241 (mm?), while I performed the tckgen with a maxlength of 150mm, confirmed when doing tckstats on the .tck file

**Comment by jdtournier** [comment]
Funny you should ask - [the same question was asked a few days ago on the MRtrix3 forum](https://plus.google.com/110457254861589783699/posts/Vs4cvEowft6). Looking at the code, it looks like you actually get the average number of vertices in the streamlines, rather than the length as such. Should be a simple matter of multiplying by the step size, but I do agree that this probably needs to be fixed...

**Comment by timpx** [comment]
Ah you're right, indeed 241*0.625 (step size) = 150mm. Thanks, a little doc on this would be welcome. I let you close if you want to.

**Comment by jdtournier** [comment]
Good to hear. I'll leave it open - I think this needs to work as advertised...

**Comment by Lestropie** [comment]
Yeah I need to bring #93 forward.

I should also add a median length option.

**Comment by Lestropie** [comment]
OK, `tck2connectome` with the `meanlength` contrast should hopefully behave as expected if you check out the `streamline_length` branch. Needs some testing before I merge it, just thought I'd let you know immediately.

**Comment by Lestropie** [comment]
Closed by #288.
