### ISSUE TITLE
"intersection" of clip planes (in addition to union)

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#290]
Background: mrview doesn't have that typical "3 perpendicular slices/planes in 3D" view that you sometimes see in other viewers.  I just wanted to hack myself something like that using the clip planes.  So I started off by creating 2 axial clip planes, and moving them a bit apart.  Playing with the invert settings for both of them, with the intention of getting a "slab" in between both planes, I suddenly realised it couldn't be done.

The thing: when adding multiple clip planes, you basically get the "union" of the volumes that are left over after cutting of each of the clip planes separately.  So after the first clip plane, by adding additional ones, you can only add "volume"; not chisel off volume.  Yet another way to put it: you can only make concave cuts (like dents) in the volume.  Or also: you can not cut off the top of the brain as well as the side.  I hope it's a bit clear what I'm trying to describe here... :smile:

**Comment by jdtournier** [comment]
Yes, this was a question that I faced when designing this feature. I figured the most useful scenario would almost invariably be what you call the 'union', so that the objects you're trying to view can be seen in as much context as possible. I thought about doing something like what you suggest, but with an arbitrary number of clip planes, it gets _really_ messy if you want to support all the different combinations possible... Personally I don't see much point in it, but if you have a solid use case, we may need to think about this some more.

As to the 3 orthogonal planes view, you really don't want to use the volume render for that, it's a sledgehammer to crack a poppy seed... There's a full-blown whole-volume ray-trace going on in there. All you want is to use the already existing slice render backend, and just modify the positions of the corners for each texture. But that assumes you really think this view mode is useful... I had that implemented in a precursor to MRView (way back circa ~2003...), but never bothered reimplementing it for later versions - I've never missed it much...

**Comment by jdtournier** [comment]
Yes, this was a question that I faced when designing this feature. I figured the most useful scenario would almost invariably be what you call the 'union', so that the objects you're trying to view can be seen in as much context as possible. I thought about doing something like what you suggest, but with an arbitrary number of clip planes, it gets _really_ messy if you want to support all the different combinations possible... Personally I don't see much point in it, but if you have a solid use case, we may need to think about this some more.

As to the 3 orthogonal planes view, you really don't want to use the volume render for that, it's a sledgehammer to crack a poppy seed... There's a full-blown whole-volume ray-trace going on in there. All you want is to use the already existing slice render backend, and just modify the positions of the corners for each texture. But that assumes you really think this view mode is useful... I had that implemented in a precursor to MRView (way back circa ~2003...), but never bothered reimplementing it for later versions - I've never missed it much...

**Comment by thijsdhollander** [comment]
So first things first: I'm definitely not rallying to have the (subset of) 3 orthogonal planes as a viewing mode in there.  I should probably be a bit more clear on what I meant by "hack myself...": I didn't mean actually implementing (or even looking for a good strategy to do so); rather checking if something resembling that "use case" could be achieved using the current viewer as-is.  If something "like that" could be done in a sufficiently easy manner in the existing viewer, there's definitely no need for extra features.  Experimenting with this in the actual viewer, however, made me realise the (theoretical) limitations of the clip planes as they are now offered.

So for the clip planes: yes, I realise that providing a mix of "unions" as well as "intersections" would be a mess, since brackets/ordering of those operations matter.  It's always been (and mostly still is / will be) my opinion that providing the most common use cases should never (or at least not too much) be sacrificed in favour of an overzealous offering of incomprehensible features.  So I agree on keeping things as simple as possible.  Also, in making the choice between offering either "unions" or "intersections", I agree as well that the best choice has been made.  "Cut outs" in bigger volumes make the most sense for the majority of use cases.  The clip planes offer this functionality in an amazingly intuitive manner.

...but sometimes, it seems handy to be able to show an (even thick) slab type of volume.  E.g. let's say you're looking at the corticospinal tract, and you want to show how it cuts through a reasonable "axial" slab at a certain level.  Or let's say you're interested in a volume render of a region/structure somewhere in the middle of the brain, and how tracks pass near or even through it (the alpha adjustment combined with the thresholds works wonders here): you'd want a cubic (or other convex kind of) geometry, cutting away most of the outside.  I think that in most of these *extra* use cases, you *only* need the "intersection" behaviour; i.e. *you don't need a mix*.  So from a user interface point of view, this might boil down to a single button/switch/checkbox that toggles between the global behaviour of "union" vs "intersection".  Or in other words: the "equivalent" of the invert button that exists now for individual clip planes, but acting on the geometry caused by the clip planes *as a whole*.

I have to admit though: I have no idea of how the volume render and clip planes are currently implemented; and more importantly, if that makes such a "simple" extension possible in an easy or at least elegant manner...
It's definitely not a major use case or missing feature (but would still be nice to have); so I wouldn't put in a huge effort... it could just as well linger around in the wish list for a while. :smile:

**Comment by jdtournier** [comment]
Ok, I get where you're coming from - no worries. I reckon you're right, if all we need is a tick box to say 'AND/OR' for the clip plane behaviour, that would actually be pretty easy. It's all handled in the fragment shader, which gets recompiled at runtime as soon as any features change (for example, changing the colourmap or adding a clip plane). You should have no trouble following the logic for the clip planes by running MRView with the `-debug ` flag, you'll see all the shader code every time it gets recompiled (useful when debugging too). You just need to skip if _any_ of the clip tests fail, rather than all. So you'd need to go through the function responsible for generating the fragment shader source, and modify it to do that.

By the way, the shader code for the volume render might be a bit daunting at first - just bear in mind that it iterates over a ray through the volume away from the viewer, accumulates colours, and stops as soon as the current fragment is opaque enough. So you'd need to modify the bit deep in the inner loop, which you'd have no trouble locating by adding and removing clip planes and inspecting the generated shader code.

**Comment by thijsdhollander** [comment]
...almost forgot to post back: I tested this offline somewhere last week, and it's indeed much simpler than I anticipated.  Made myself an mrview that behaved with the "intersection" logic by 3 minuscule edits (changing a true to a false, a false to a true, and a > to a <).

It works like a charm, and provides a lot of fun.  What I didn't anticipate, though, is its interactive usability.  The "union" logic is easy to interact with, because each clip plane fully neighbours a visible part of the volume; i.e. the highlight of the actual clip plane is always there (as long as it intersects the original volume).  With the "intersection" logic, that is not necessarily true.  Even making a simple slab-type of volume by combining 2 parallel clip planes, is a bit confusing at first.  If they aren't positioned where you expect them to be, and the correct "invert" switches have not been set, you may see nothing at all... which makes it a bit tricky to interact with until you get that right.  Even when you are working on a shape (by basically chiselling off edges and corners), adding a fresh clip plane has a good chance of hiding everything, until you invert it.

So yeah, I'll see if I happen to think of a better way to visualise this during the interaction/highlighting stage (I've got a few alternatives in mind, but it's not obvious if all/some/any of them will work well in practice).  Up until then, it's safe to leave this one on the virtual wish list; it's definitely not a priority.

**Comment by jdtournier** [comment]
Yes, I can see this would be a problem. One option is to change the way the clip plane modifies the volume. Currently, all that happens is that locations within some distance of the clip planes have some extra red added to their colour. It should be trivial to add a little bit of extra alpha component, which would give it non-zero opacity - and hence make it visible even when it's outside the renderer volume. Do you want to give that a shot? It might be worth doing even for the current implementation...

**Comment by thijsdhollander** [comment]
I'm giving it a shot!  Basically going for the intersection type of mode, and I'll also try to include something to switch on/off the highlighting of the selected planes (currently the red does hide the actual intensities of the clipped plane; it's handy to have it as a hint, but sometimes you might rather want to see how it will look after deselecting the plane, but while the plane is still selected so you can move it around).

**Comment by thijsdhollander** [comment]
Ok... it should be workable and bug free.  Intersection mode is indeed only for very specific use cases where you know what you're after.  Making a thick slab (or even cube), turning highlighting off, selecting all clip planes and then dragging/rotating around is big fun though.

I'm off till after the weekend (epilepsy retreat fun); whoever wants to play around with it in the mean time: it sits in the `clipplane_interaction` branch at least until then.

**Comment by jdtournier** [comment]
Just had a brief go with this - the intersection mode works well, and it's not at all intrusive. Definitely a keeper. Not so sure about the highlighting in this mode though, something looks off. What I had in mind was that the plane itself would be visible, but not a lot else. As things stand though, everything behind the clip planes is shown, although with reduced opacity. It actually makes it quite difficult to see what's going on. Not sure what's going on exactly, I'll take a closer look when I have a minute, see if I can get it to do what I had in mind...

**Comment by thijsdhollander** [comment]
Yeah, I agree it's not at its best with that approach (yet).  So, given intersection mode, I definitely wanted the whole plane-volume intersection to be highlighted when selected (i.e. the red slice if you will).
But what I was also thinking of, was to have a hint as to "which side" of that plane was the volume that would intersect with the others.  It's exactly this that is never really a problem for the "union" mode (because the volume on that side is always entirely shown, highlight or not), but becomes tricky for the intersection one.  Hence the reduced opacity volume that is shown to give the hint.  It works well some times, but less well in other cases.  Where I find it gives the best hints as to what is happening in the intersection mode is in e.g. this scenario: (1) add 2 perpendicular clip planes (e.g. axial and coronal), (2) select intersection mode and leave highlights on, (3) select *both* planes in the list.  It now becomes very easy to see how things are actually intersected, and manipulating that combination of planes as a whole is quite intuitive.
...but adding lots more planes and selecting certain subsets of them, or individually manipulating some, can sometimes lead to a confusing view.  Switching off highlighting works better to do certain manipulations for more complex volumes (but then every hint as to what is selected is gone of course).

Definitely go ahead and try some other approaches to see what works best.  To get rid of the reduced opacity ghost, you'll find that it might be easiest to work from the point right *before* the last commit I made in this branch.  That one is the most straight forward combination of highlight and intersection, but that has the "issue" of having no highlight hint when the selected clip plane's volume is not intersecting with any other clip planes' volumes.

I find that a good set of "usability tests" for the intersection mode consists of these 3 scenarios:

1) try to "chisel" off different parts of a volume (e.g. cut off a small part of the top of the head, and a small part at a side, and one diagonally connecting both)... i.e. the "sculpting scenario"
2) try to make a fat slab in some orientation.  It's cool that once you have a slab, you can select both clip planes and manipulate the slab as a whole (while the planes stay parallel).  I find this simple scenario can be tricky/confusing, as you need to invert one of the planes and move it to the right side of the other one.  Here, the highlight mechanism of choice is crucial...
3) basically beyond scenario (2): try to cut out a geometry in the middle of a volume (e.g. a cube), and optionally further chisel it off.  It's almost like delineating a volume in the volume, using planes.  The ultimate test to see if the highlighting assists the user in establishing this...

Now that I think of it... maybe an idea is to have a limited ghost hint.  Not the *whole* volume at the relevant side of the clip plane, but just a limited slab that fades out (a bit like how the actual red planes are done now, but then just a bit thicker...  That would actually also not be bad for the "union" mode.  You kind of sometimes (but not often) have the opposite problem there: when there's no cut out to be found, but you only see the red slices through the volume, and you're wondering which one needs to be inverted.

**Comment by thijsdhollander** [comment]
Just to illustrate what I meant by...

>Where I find it gives the best hints as to what is happening in the intersection mode is in e.g. this scenario: (1) add 2 perpendicular clip planes (e.g. axial and coronal), (2) select intersection mode and leave highlights on, (3) select both planes in the list. It now becomes very easy to see how things are actually intersected, and manipulating that combination of planes as a whole is quite intuitive.

I did rotate the planes individually at a different angle beforehand though:

![screenshot from 2015-07-30 11 08 33](https://cloud.githubusercontent.com/assets/11952694/8973711/8cd1d51c-36ab-11e5-9d3f-e6d59a266083.png)

But beyond this simple scenario, the highlight "ghosts" can become more intrusive.  Although, creating and manipulating slab-type of intersections is also quite easy in this manner:

![screenshot from 2015-07-30 11 13 07](https://cloud.githubusercontent.com/assets/11952694/8973748/3638efd2-36ac-11e5-9559-c3a510c9149b.png)

But it's still definitely worth a few other attempts to see if there's better highlighting mechanisms to support the user in such a task...

**Comment by jdtournier** [comment]
OK, I see the rationale - looks pretty cute, but I think it can get rapidly overwhelming...

I've had a go at a few more modifications more in line with what I had in mind. Less sexy, but probably more functional - see what you think... I've made a pull request for this branch (#309), let's carry on the discussion over there. I'll close this off for now.
