### ISSUE TITLE
ROI tool: Race condition on load

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#293]
Well, at least that's what I think it is... Can only do it on Farnoosh's computer, and only in release mode.

Open the viewer, load three ROIs (very high resolution, so slow load); only the latter two are visible. Most of the time. Will try to get access to the system and throw some TRACE calls in there, but thought I'd put up here in case anyone has any ideas. I did notice that I can still apply updates to the GL window while the ROIs are loading...

**Comment by jdtournier** [comment]
Crap, yes I think I know what's going on here... The issue is that the progressbar _display_ (which only kicks in after 0.5s) invokes a global refresh and processing of events. This maycall the main window's `paintGL()` method, which will change the state of the GL - in particular, it will most likely bind different textures, meaning the subsequent `gl::TextSubImage()` data upload will go to some other texture than that intended. It's actually worse than that with Qt >= 5.4, since the main GUI elements are themselves drawn using OpenGL with the same context as the primary GL window - so any update to the UI will likely affect the state of our GL context, even if our `Window::paintGL()` itself is not invoked. 

This was already an issue for the simple reason that a progressbar update would often cause an update event for the main GL window, and more often than not the progressbar is actually being used while in `Window::paintGL()` (since data get loaded on demand at that point). In Qt5.4, this produces a `recursive paintGL() call detected` warning at runtime...

I'm not sure how best to handle this. The simplest thing is to just prevent the progressbar from displaying anything (comment out the annoying bits in `src/gui/dialog/progress.cpp` - that should at least confirm whether this is the problem. Longer term, we'd need to reassess how we handle progressbar updates - most of the time we'll be doing slow OpenGL operations, which means we'll face these kinds of conflicts no matter what we do. Initially, I thought we'd need to move the texture upload calls outside of `paintGL()`, and somehow figure out when they need to be triggered. But I have a feeling this will no longer be sufficient, especially with Qt 5.4. We need a radical rethink, but right now the cleanest thing I can think of is simply disabling (or at least not using) the progressbar... which isn't a great solution UI-wise.

Suggestions welcome...

**Comment by jdtournier** [comment]
please try with the latest commit on master (a8a7202), see if that fixes it...

**Comment by jdtournier** [comment]
@Lestropie, do the latest changes on master (4fb229b) fix this issue...?

**Comment by Lestropie** [comment]
Reported fixed; probably with a8a7202 rather than 4fb229b.
