### ISSUE TITLE
MRView vector tool: thresholds applied after scaling

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#302]
If I display a msf file and apply a threshold, then change to scale by fixel value, the fixels shown change. In fact I can go from lots of fixels to nothing shown at all just by changing this option. I'm guessing this is not the desired behaviour - thresholding should be performed on the raw fixel values, before any scaling is applied?

**Comment by Lestropie** [comment]
Yes, I'd say that the threshold should apply to the fixel associated value, regardless of what parameter is being used to scale the fixel lengths.

Also noticed that the thresholds are being applied in the fragment shader; no reason why this can't occur in the geometry shader.

**Comment by Lestropie** [comment]
@jdtournier Give the `fixel_tool_threshold_fix` branch a try.

@draffelt Confirm that this is the intended behaviour, and what Donald observed wasn't deliberate?

PS. Another benefit of changing the vector plot tool to a style similar to the connectome tool, ie. have 'Set fixel (length / colour / threshold) according to (nothing / fixel size / fixel value / external data)'. Full control, no ambiguity. Would also be further enhanced by use of the `FixelIndex` class :-P (but could make it work without it)

**Comment by jdtournier** [comment]
Agree that geometry shader is the right place to apply the threshold, now that the implementation allows it. Should be a trivial fix, if someone wants to take this on?

As to the interface, I'm not sure what you mean by the changes you're suggesting (maybe I need to take a closer look at the connectome tool again...). The interface seemed fine to me, I didn't see any need to change it... 

I notice you mention the fixel size & value as distinct entities - I remember we'd discussed this a while back, although I can't find the thread. Didn't we come to a consensus that having separate size & value fields per fixel was unnecessary? I thought we were getting rid of one of them, since it's currently unused (as far as I know?). What are the use cases where we need the additional entry? And are they common enough to warrant adding UI controls for them (along with a good deal of confusion)? Personally I think this needs to be kept as simple as possible, we can always revisit later if we come up with a killer app that needs it - and if and when we do, we'd probably need to come up with a better/cleaner way to handle these data UI-wise...

Not sure I get the reference to the `FixelClass` - what's the idea there?

**Comment by jdtournier** [comment]
@lestropie, sorry, didn't spot you'd already done this... I'll give it a crack next week - won't be at my desk for a while...

**Comment by jdtournier** [comment]
@Lestropie, can't find the `fixel_tool_threshold_fix` branch anywhere... Did you push it?

**Comment by Lestropie** [comment]
... OK, I must be going mad. I swear I wrote this code... now I can't find the branch on any system :-/

**Comment by jdtournier** [comment]
Yeah, I find kids have that effect on me... Maybe you stashed it...?

**Comment by Lestropie** [comment]
... Found it!
https://github.com/MRtrix3/mrtrix3/tree/fixel_tool_threshold_fix

**Comment by draffelt** [comment]
With respect to @jdtournier's comment. At risk of sounding like a broken 
record, other than a direction, I think a fixel should only ever have one 
value. I'm not convinced viewing two things by both length and colour is 
needed, when switching between two files with colour maps would be more 
informative. In fact, I think viewing anything quantitative by length is 
not ideal since most fixel directions are out of plane anyway. On that 
note, I also feel [scaling the length by the value sqrt](
https://github.com/MRtrix3/mrtrix3/issues/118) just to 'help' visualise 
values that end up rendering with drastically different lengths is a bit of 
a hack, mis-informative, and provides UI clutter. 

>From a UI perspective, I think it's confusing for 99% of users to keep both 
fixel size and associated value it in the vector plot tool. Especially when 
peaks or eigenvector files don't have two values.

My opinion is what makes a fixel different from another fixel is it's 
location and a direction only. Fibre density (ala intra-axonal volume...or 
in MRview 'size') is just one possible value a fixel can have and should 
not be treated special. 

I know a previous reason for keeping it was that it might be handy to have 
both density (size) and spread for future applications as tractography. 
However, I think in this use case, the user can just input two images to 
the command. 

Having just one value also makes it clear what is being operated on in 
commands like fixelcalc. 

If we are going to remove the size field, we should do it before release 
since files will not be backward compatible.

**Comment by Lestropie** [comment]
> At risk of sounding like a broken record, other than a direction, I think a fixel should only ever have one value. I'm not convinced viewing two things by both length and colour is needed, when switching between two files with colour maps would be more informative.

And again, if you're only ever dealing with clean group average data, displaying every fixel with the same length may make sense; but with noisy single-subject data it looks horrible. So you scale the length by the fixel size (but that hides a lot of smaller fixels, hence the sqrt() suggestion). If you remove the fixel size data field, and force the user to import a sparse file with the associated value being the fixel density so that they can scale the length by such, they are then prohibited from visualising any other interesting per-fixel parameter, as the 'value' field is occupied by the fixel size.

... Unless they explicitly import multiple fixel images, with one being the fixel image being displayed and others being there just to pull their associated data to control a particular visual property (and the underlying fixels are required to be precisely identical), which is all just clunky and inconsistent.

> From a UI perspective, I think it's confusing for 99% of users to keep both fixel size and associated value it in the vector plot tool. Especially when peaks or eigenvector files don't have two values.

This comes back again to my ideas for orientation overlays where the visible UI elements depend on the selected image. If the imported image is an XYZ image rather than a sparse fixel image, options to set thresholding / colour / size by 'associated value' should be hidden from the user, with only the size (as inferred from the vector length) available.

> I know a previous reason for keeping it was that it might be handy to have both density (size) and spread for future applications as tractography. However, I think in this use case, the user can just input two images to the command.

This logic still completely baffles me. You want to remove a field to reduce the per-fixel storage from 20 to 16 bytes, yet want the user to then have to store and manage and pass around multiple fixel images, despite 75% of the data being common between each of those images. This would infuriate me as a user. Plus the combination of size and value is already being used; see below.

> Having just one value also makes it clear what is being operated on in commands like fixelcalc.

`fixelcalc` (if we end up requiring such a thing) should operate on the associated value. The size is essentially a weighting parameter. Check out `fixel2voxel`. For instance, say you want to calculate the mean value for two fixels within a voxel. You have two options: you can either average the two fixel values, or you can take a weighted mean with weights according to the relative sizes of the two fixels.

But since we're sounding like broken records...

### FixelIndex class

* Create a FixelIndex class, which stores XYZ direction, fixel size, and a unique integer identifier for each fixel. When performing FOD segmentation on the group template, output one of these.
  * Note that per-subject fixel images _remain_ using FixelMetric; after all, we're after some metric of interest in each fixel per subject.

* When writing output files from fixel stats, instead of writing a series of fixel images where each contains precisely the same underlying fixels, write a series of .csv's, containing the value of each parameter of interest for each fixel in the template. The integer variable stored for each fixel refers to an index in the data files.

* When opening a fixel image in mrview, change the available UI elements depending on what type of fixel image is opened:
  * If the type is FixelMetric, keep the current available settings, i.e. threshold by size / value, colour by direction / size / value, length by unity / size / value.
  * If the type is FixelIndex, allow threshold / colour / size to be determined by an imported .csv file. That way you can threshold by one parameter (e.g. p-value) and colour by another (e.g. effect size) without resorting to importing multiple fixel images (which intrinsically depends on having redundant data between images). See the connectome tool for examples: it's about deciding what data should be used to determine each visual property.
  * Any advanced mathematical operations (e.g. to calculate effect sizes) can be done using any software that can read a .csv. Which may include MRtrix in the near future.
  * Likely no need for a fixelcalc command; any advanced calculations on fixel images are likely to be as the result of group statistics.

This doesn't break any existing data, doesn't break any existing command functionalities, and I'm yet to see a solid argument against it. The sparse image format was designed around a templated fixel class; if you don't want to constrain a fixel class to store a particular set of parameters following statistical analysis, outsourcing that data to external files is the logical solution.

**Comment by draffelt** [comment]
On Tue, Aug 4, 2015 at 7:00 PM, Robert Smith <notifications@github.com>
wrote:

> At risk of sounding like a broken record, other than a direction, I think
> a fixel should only ever have one value. I'm not convinced viewing two
> things by both length and colour is needed, when switching between two
> files with colour maps would be more informative.
>
> And again, if you're only ever dealing with clean group average data,
> displaying every fixel with the same length may make sense; but with noisy
> single-subject data it looks horrible. So you scale the length by the fixel
> size (but that hides a lot of smaller fixels, hence the sqrt() suggestion).
> If you remove the fixel size data field, and force the user to import a
> sparse file with the associated value being the fixel density so that they
> can scale the length by such, they are then prohibited from visualising any
> other interesting per-fixel parameter, as the 'value' field is occupied by
> the fixel size.
>
Ok, so what you are arguing for is something similar to a FA-weighted
eigenvector map. Where, the colour is down weighted by FA so as not to
distract the user in noisy grey matter regions. While I'm not opposed to
this function being handled in the viewer, my preference for a simple fixel
class and UI, and fixelcalc command means that I would be happy to forfeit
this feature (see below). Also, multi-shell data will clean these
directions up in the future.

... Unless they explicitly import multiple fixel images, with one being the
> fixel image being displayed and others being there just to pull their
> associated data to control a particular visual property (and the underlying
> fixels are required to be precisely identical), which is all just clunky
> and inconsistent.
>
I agree, loading multiple images is clunky (clicky?) and annoying. Bare
this in mind for my response to your FixelIndex suggestion below.


From a UI perspective, I think it's confusing for 99% of users to keep both
> fixel size and associated value it in the vector plot tool. Especially when
> peaks or eigenvector files don't have two values.
>
> This comes back again to my ideas for orientation overlays where the
> visible UI elements depend on the selected image. If the imported image is
> an XYZ image rather than a sparse fixel image, options to set thresholding
> / colour / size by 'associated value' should be hidden from the user, with
> only the size (as inferred from the vector length) available.
>
> I know a previous reason for keeping it was that it might be handy to have
> both density (size) and spread for future applications as tractography.
> However, I think in this use case, the user can just input two images to
> the command.
>
> This logic still completely baffles me. You want to remove a field to
> reduce the per-fixel storage from 20 to 16 bytes, yet want the user to then
> have to store and manage and pass around multiple fixel images, despite 75%
> of the data being common between each of those images. This would infuriate
> me as a user. Plus the combination of size and value is already being used;
> see below.
>

I guess it depends on how often we envision commands using both density and
some other measure at the same time. Again, I still think simplicity for
95% of the use cases, and ability to have a fixelcalc command is my
preference.  As we have discussed before, I'm not that fussed about storage
given an upsampled fixel image is only 40Mb. Agreed, passing around
multiple files is annoying (also bare this in mind in my response below).



Having just one value also makes it clear what is being operated on in
> commands like fixelcalc.
>
> fixelcalc (if we end up requiring such a thing) should operate on the
> associated value. The size is essentially a weighting parameter. Check out
> fixel2voxel. For instance, say you want to calculate the mean value for
> two fixels within a voxel. You have two options: you can either average the
> two fixel values, or you can take a weighted mean with weights according to
> the relative sizes of the two fixels.
>

In fixel2voxel, if a user wants to weight each fixel value by the fibre
density, you could always just pass in this image when using the -weighted
option.




> But since we're sounding like broken records...
> FixelIndex class
>
>    -
>
>    Create a FixelIndex class, which stores XYZ direction, fixel size, and
>    a unique integer identifier for each fixel. When performing FOD
>    segmentation on the group template, output one of these.
>    - Note that per-subject fixel images *remain* using FixelMetric; after
>       all, we're after some metric of interest in each fixel per subject.
>    -
>
>    When writing output files from fixel stats, instead of writing a
>    series of fixel images where each contains precisely the same underlying
>    fixels, write a series of .csv's, containing the value of each parameter of
>    interest for each fixel in the template. The integer variable stored for
>    each fixel refers to an index in the data files.
>    -
>
>    When opening a fixel image in mrview, change the available UI elements
>    depending on what type of fixel image is opened:
>    - If the type is FixelMetric, keep the current available settings,
>       i.e. threshold by size / value, colour by direction / size / value, length
>       by unity / size / value.
>       - If the type is FixelIndex, allow threshold / colour / size to be
>       determined by an imported .csv file. That way you can threshold by one
>       parameter (e.g. p-value) and colour by another (e.g. effect size) without
>       resorting to importing multiple fixel images (which intrinsically depends
>       on having redundant data between images). See the connectome tool for
>       examples: it's about deciding what data should be used to determine each
>       visual property.
>       - Any advanced mathematical operations (e.g. to calculate effect
>       sizes) can be done using any software that can read a .csv. Which may
>       include MRtrix in the near future.
>       - Likely no need for a fixelcalc command; any advanced calculations
>       on fixel images are likely to be as the result of group statistics.
>
> This doesn't break any existing data, doesn't break any existing command
> functionalities, and I'm yet to see a solid argument against it. The sparse
> image format was designed around a templated fixel class; if you don't want
> to constrain a fixel class to store a particular set of parameters
> following statistical analysis, outsourcing that data to external files is
> the logical solution.
>



I'm not a fan of a FixelIndex class for viewing statistical results for
several reasons:

   - The main one being usability. In a recent study, we had 6 different
   statistical comparisons (where different groups and subgroups were defined
   by various gene mutations, seizure foci, relatives etc). Each of these had
   a fibre density, cross-section and combined analysis. So that's 18 results,
   each with pvalue (pos and neg), effect, stdev, betas etc etc. I want to be
   able to quickly load each pvalue file for all results, then select all and
   threshold. It would be a headache to load each index file, then for each
   one load the pvalue file to colour, then load it again to threshold.
   - In the relatively rare event a user wants to threshold by one file
   then colour by another (for example generating figures for a paper), then
   the fixelcalc command would handle this. Just like how a user would need to
   do this for a 3D image result using the image overlay tool. In the
   particular use case of effect size results, a user will already need to use
   fixelcalc to generate the effect size map (percentage decrease wrt
   controls), since only they know what group is what.
   - If you are worried about size, then storing an index and value as
   ascii text will take up a lot more space.


Clearly we both have different ideas based on our own experience and
possible use cases. I guess at this stage we probably need to hear what
others think in case we both have our blinkers on.

**Comment by Lestropie** [comment]
> While I'm not opposed to this function being handled in the viewer, my preference for a simple fixel class and UI, and fixelcalc command means that I would be happy to forfeit this feature

You don't remove a functionality just because one particular user doesn't use it...?

> Also, multi-shell data will clean these directions up in the future.

You want to _remove_ a functionality that's _necessary_ to visualize current data, on the premise that _in the future_ that functionality won't be _as necessary_? Baffled.

> I guess it depends on how often we envision commands using both density and some other measure at the same time. Again, I still think simplicity for 95% of the use cases, and ability to have a fixelcalc command is my preference.  As we have discussed before, I'm not that fussed about storage given an upsampled fixel image is only 40Mb.

There's already a command in there using it, and I have had other use cases in my head from the outset of implementing the sparse storage class. For instance: more robust subject-to-template fixel matching, accounting for the potential for one-to-many and many-to-one relationships. If the extra data field is otherwise non-intrusive, and as you say storage size is not a problem, why handicap those current and future capabilities? Also, keeping the size field in no way precludes the ability to have a fixelcalc command.

> In fixel2voxel, if a user wants to weight each fixel value by the fibre density, you could always just pass in this image when using the -weighted option.

Again, this premise is based on importing multiple images _designed for sparse storage_, yet by necessity must have _75-80% shared information_. Completely counter-intuitive; I'd feel ridiculous instructing a new user how to do this.

>  I want to be able to quickly load each pvalue file for all results, then select all and threshold.

The moment we have more than one fixel class, a `fixelconvert` command becomes a necessity. If `FixelIndex` were implemented, this would allow to convert from `FixelIndex` to `FixelMetric` by providing the data file to be imported to specify the relevant associated value for each fixel. You get exactly the same data as you have now.

> In the relatively rare event a user wants to threshold by one file then colour by another (for example generating figures for a paper), then the fixelcalc command would handle this.

Yes, but it wouldn't allow dynamic user interaction with those two variables at once. Furthermore, with the FixelIndex class they could also be pre-computed; just that this pre-computation would occur in CSV files (which can be handled using a range of software) rather than `fixelcalc`.

> If you are worried about size, then storing an index and value as ascii text will take up a lot more space.

Neither of us are worried about storage size. But that's one less reason to remove the `size` field, not a reason to _not_ use `FixelIndex`.

### Fixel size

Since storage isn't an issue, the only justifications I can see for removing the size field are:

* Peak images don't have size and associated values, only size, which conflicts with the available UI: Solved by not presenting the options to set visual properties by associated value when the selected image is a peak image.

* Philosophical ('I think a fixel should only ever have one value'): Fixels represent an atomic fibre population element. Almost every single crossing-fibre diffusion model out there will attribute some form of 'density' / 'volume fraction' to each fibre population in a voxel. This is an intrinsic property of the fixel that comes from the diffusion model, independently of any other parameter that may be investigated. If the parameter of interest happens to _be_ the fixel size, so be it: that redundancy makes sense. But no matter what processing you apply to your fixels, there will always be some underlying measure of density associated with each; it's as fundamental as the direction.

The arguments for keeping it are:

* It's already in use (`fixel2voxel`). Removing it would then require counter-intuitively passing multiple 'sparse' images that contain vast amounts of redundant information to the command, as well as explicitly verifying said redundancy.

* It has future use cases. Removing it would make all of those future uses equally counter-intuitive.

* Its removal would break compatibility with existing images.

* Its removal would make visualization of per-subject fixel images, where the parameter of interest is anything other than the fixel size, almost impossible.

* Status quo. I thought long and hard about this when I implemented the sparse image format, it's there for a reason.

**Comment by draffelt** [comment]
You raise some good points (though I don't agree with many). Both approaches have some benefits. It's just not how I would have implemented it. I'm happy to go with the consensus. I don't feel that passionate about it.

I think status quo is not a good reason to keep things as they are. I'm sure Tony Abbott thinks long and hard about his captains choices. But it doesn't mean I agree with them, or think his policies should remain once he is ousted. Perhaps an open discussion on the Fixel format before implementation might have been useful.

**Comment by thijsdhollander** [comment]
Hey guys.  So I created this separate issue #317 , because this important discussion should not get lost in this only-semi-related issue.

**Comment by Lestropie** [comment]
Solved in #313.
