### ISSUE TITLE
mrconnect: move to maskfilter

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#304]
Since this command doesn't include support for dixel-based connectivity, this functionality probably belongs in `maskfilter` (where there's already a largest-connected-component filter). Only requirement would be to branch as the output of this filter will be a label image rather than a mask.

**Comment by draffelt** [comment]
Agreed, it could replace the LCC option since these do the same thing if
the -largest option is used.

I think all 4 methods should have a separate branch anyway. I think it's
probably over kill to have separate functions in maskfilter to create each
filter, just to do a dynamic cast back to Filter::Base. Seems to me like
there is a bunch of extra code and jumping around, just so you can have a
single line of code for opening and creating an image.

I came across the same issue in mrfilter when updating the syntax. Checkout
mrfilter in the updated syntax branch, it's now 2/3 of the size of the
mrfilter in master.  FFT was already treated as a separate branch in master
anyway.

**Comment by Lestropie** [comment]
Yeah the idea when I did all that gymnastics was to have the code mimic the intent of the command in terms of applying a filter to a mask image, but once all was said and done the code came out kind of retarded.

**Comment by draffelt** [comment]
Hmm...I was going to suggest that you should have just done this in the updated_syntax branch.

**Comment by draffelt** [comment]
Actually, sorry maskfilter is not yet updated

**Comment by Lestropie** [comment]
Yeah, probably should. Need to get my hands dirty with it. But I've been ticking off some old issues so wanted to keep the ball rolling.
