### ISSUE TITLE
QSpinBox double slot invocation

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#306]
I've noticed this from time to time, particularly on the LOD selector in the ODF tool but am now seeing it in another context with a QSpinBox.

If you click one of the up/down arrows on the spin box, sometimes the slot function is called twice, so you get a double increment / decrement. It's caused by a timer throwing an event that is processed as a mouse button hold, _before_ the mouse button release event is received, in cases where the value change causes heavy processing.

This is relevant reading:
https://bugreports.qt.io/browse/QTBUG-33128

It's possible to get around, but not without disabling having the increment/decrement controls repeatedly engage on mouse button hold. Are there cases where this capability should / should not be permitted, or should this become the default behaviour for all spin boxes in MRview?

**Comment by jdtournier** [comment]
Finally got round to having a quick look into this. I wouldn't have a problem with disabling the increment/decrement controls for _some_ of the spin boxes, but there are cases where that would not be great. For instance, the volume index control on the view tool - you might want to press and hold to cycle through volumes (although you could achieve the same thing by pressing the arrow keys). So I don't think we necessarily want to globally disable the autorepeat for all spinboxes. 

That said, I think this is going to be a problem for all of those spinboxes - anything that involves a potentially slow redraw is likely to exhibit this behaviour at some point. The problem is that there is no simple solution that I can think of that wouldn't involve grabbing event timestamps _as they occur_, which would need to happen deep within Qt or the window manager code... So not sure what to do with this one...

**Comment by Lestropie** [comment]
The generally-accepted way around this is to make the updates asynchronous; spawn a thread to do the heavy lifting, and notify the main thread when it's done. But that's not of much use if the heavy lifting is a texture upload.

You can get around it without too much drama: just inherit from QSpinBox, customise the function that receives the timeout event, flag the event as accepted but do nothing. But if as you say, it's not appropriate in all cases, we need to look at them individually. Having said that, your example was the volume index control: the one that was giving me the irrits recently was the volume index control in the overlay tool (while in volume render mode)... :-/

**Comment by jdtournier** [comment]
Yes, I saw that 'fix' for this issue. Maybe we could try a different approach: inherit from QSpinBox, and reimplement its `timerEvent()` method to check the status of the mouse buttons using [QApplication::mouseButtons()](http://doc.qt.io/qt-4.8/qapplication.html#mouseButtons), and invoke the original implementation of the `timerEvent()` if the mouse buttons genuinely are still depressed. Although I'm guessing this won't work as-is without some trickery, if the mouse button status only gets updated in some other callback that might be invoked _after_ the timer event, but then a judicious `qApp->processEvents()` would probably sort that out...

**Comment by jdtournier** [comment]
For future reference: pull request in #321.
