### ISSUE TITLE
Change gcc version minimum requirement to 4.8

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#333]
Given that 4.7 is not fully [C++11 compliant](https://gcc.gnu.org/gcc-4.7/cxx0x_status.html), we should change the configure script to require at least 4.8.

Erik just tried to build with 4.7. Configure ran fine, but compile errors were found.

**Comment by chunhungyeh** [comment]
Funny that...I just had similar experience when I was helping my friends to install MRtrix3 on their computers yesterday. The difference is that they have a CentOS 6.7 system and want to keep it for FSL with a Son Grid Engine (SGE) computing cluster (see the bottom part of http://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation). I think this might also be the case for some other users so I just want to share my little experience here:
*  In CentOS 6, the default python version is 2.6 but MRtrix3 needs at least 2.7. Simply installing python 2.7 may cause problem since some commands in CentOS 6 (e.g. yum) require python2.6. Here is a possible solution to have both python 2.6 & 2.7 without breaking the system: https://github.com/h2oai/h2o-2/wiki/Installing-python-2.7-on-centos-6.3.-Follow-this-sequence-exactly-for-centos-machine-only
* The g++ was 4.4 and Qt was 4.6 on their computers; apparently they were not good for MRtrix3... So after a number of trial and error, I found this post from the Qt website quite helpful: https://wiki.qt.io/How-to-Install-Qt-5-and-Qwt-on-CentOS-6.

So finally MRtrix has been successfully complied on their computers. :relieved:

Anyway, this might not be very relevant to this post (sorry about that); but hopefully it could be useful whenever any CentOS6 users raise similar issue again in the future.

**Comment by jdtournier** [comment]
Technically, the compiler test never tested for any particular version of GCC - and I'd like to keri it that way, otherwise we'd need these tests to be specific to the particular compiler used. We'd need to detect whether we're using GCC or clang (or maybe even something else), and tailor the tests to that particular compiler. If rather we tested for the particular features we know will cause issues, which in this case is constructor inheritance. It would be trivial to modify the code segment used to test the compiler by adding in a really simple case of constructor inheritance, and that would make g++ 4.7 fail...

As to the CentOS case, this is going to be a problem common to a lot of other older systems. Personally, I think the simplest is to use the standalone installation instructions already provided in the wiki, and eventually we'll provide static binaries for point releases that should cover those cases.
