### ISSUE TITLE
NIfTI intensities shown wrong in volume render and light box

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#335]
Just encountered a strange bug.  I opened a NIfTI image in mrview, and switched to volume render.  Suddenly the intensities shown where much darker (as in: lower on the colour scale), but the colour bar was not affected.  Hence, I thought I'd done something wrong, so I cranked up the brightness.  However, switching back to single slice, everything was way to bright.  After investigating a little further, I noticed it was not just the volume render affected by the "too dark" intensities, but also the light box (but not the ortho view).  See the example below for a better description.  I opened a NIfTI of a T1 image, and set the colour scale to jet (so it's easier to see where we are on the colour scale); also adjusted the range a little bit for better contrast.  I overlaid a T2 (using the overlay tool), and set that one's colour scale to gray scale (this is not essential for the bug to happen, but it does show that the overlay is not affected by it); finally set the overlay opacity to about 50%.

Here's single slice:
![singleslice](https://cloud.githubusercontent.com/assets/11952694/9570876/4cdca626-4fd8-11e5-9ee0-6964e5a315b5.png)

Here's light box (basically just hit F4, nothing else):
![lightbox](https://cloud.githubusercontent.com/assets/11952694/9570880/642693b4-4fd8-11e5-80cf-459366f4da0d.png)

Ortho view is consistent with the single slice; volume render is equivalent to the light box.  The latter two are clearly the bugged ones, as found by comparing with the colour bars.

`mrinfo` yields:

```
************************************************
Image:               "T1_TRA_aniso.nii"
************************************************
  Format:            NIfTI-1.1
  Dimensions:        256 x 256 x 60
  Voxel size:        0.976563 x 0.976563 x 3
  Data type:         signed 16 bit integer (little endian)
  Data strides:      [ -1 2 3 ]
  Intensity scaling: offset = 0, multiplier = 6.19194
  Comments:          ?TR:9.705 TE:4.60
  Transform:               0.9998     0.01776   -0.007681      -119.8
                         -0.01622      0.9856      0.1686      -116.6
                          0.01056     -0.1684      0.9857      -15.49
                                0           0           0           1
```

After converting the NIfTI to a .mif using `mrconvert` (no extra options specified), the problem is gone (when opening the .mif in the viewer instead).

`mrinfo` of the .mif yields:

```
************************************************
Image:               "T1_TRA_aniso.mif"
************************************************
  Format:            MRtrix
  Dimensions:        256 x 256 x 60
  Voxel size:        0.976563 x 0.976563 x 3
  Data type:         signed 16 bit integer (little endian)
  Data strides:      [ -1 2 3 ]
  Intensity scaling: offset = 0, multiplier = 1
  Comments:          ?TR:9.705 TE:4.60
  Properties:
    mrtrix_version: 0.3.12-935-g7d3d8ba3
  Transform:               0.9998     0.01776   -0.007681      -119.8
                         -0.01622      0.9856      0.1686      -116.6
                          0.01056     -0.1684      0.9857      -15.49
                                0           0           0           1
```

Comparing both `mrinfo` outputs, my eye caught the multiplier 6.19194 in the NIfTI's header... that's quite likely about the factor that the intensities are off in the bugged modes...

**Comment by jdtournier** [comment]
OK, the difference between the slice mode and the volume render/lightbox modes is that the former copies the data for the current slice into a 2D texture using float32 format , while the other copies the data for the current _volume_ into a 3D texture using the closest datatype to the original that it can find (to try to limit RAM usage on the GPU). The problem is that this these values are scaled differently once they get to the shader: floating-point types are left as-is, but integers types are scaled so that the maximum value that can be represented is 1 (i.e. uint8 types are divided by 256 when accessed as floats in the shader). So there is a rescaling factor that gets set when the 3D texture is updated, based on the data type used (this is handled in `src/gui/mrview/volume.cpp`), which needs to be passed to the `Displayable::start()` method (which sets up the shader uniform variables). If this isn't happening, then that would manifest as incorrect scaling - but it would be so far off as to make the data impossible to view. 

The issue is probably more likely to do with the data scaling values (as shown in the header), but I can't figure out why it would be different between the two modes... I'll have a closer look when I have a minute.

**Comment by jdtournier** [comment]
OK, replicated using the .mih format and playing around with the `scaling` entry... I'll take a closer look.

**Comment by jdtournier** [comment]
Well that was a bit of fun hunting that one down! Guess this shouldn't be a problem with the updated syntax...

**Comment by Lestropie** [comment]
... Dayum.
