### ISSUE TITLE
Show argument descriptions when options have multiple arguments

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#336]
I was just using mrcrop and trying to make sense of the help, when I realised the description is missing for the multiple arguments of the -axis option.

**Comment by Lestropie** [comment]
#132 

Should definitely fix this one up...

**Comment by Lestropie** [comment]
.. Apologies, completely mis-read that one. 132 is only mildly related.

**Comment by jdtournier** [comment]
As I mentioned in #132, I _don't_ think this is the right way to go - _particularly_ when options have multiple arguments. I almost invariably find that the best way to describe the arguments is as part of the description for the parent option...

**Comment by jdtournier** [comment]
_Just thought I'd copy/paste what I'd said in #132 for completeness - it might not have been terribly obvious that I was actually talking about this issue..._


This used to be how it was done in older versions (just check out the help page for any command in the 0.2.x version). In MRtrix3, these are explicitly ignored - it's not a bug (although this clearly could do with being documented). The reason for this is that in pretty much all cases, this introduces pointless redundancy in the help page, making the help page needlessly longer and more verbose, and forcing developers to write essentially the same information twice. For example:

~~~
+ Option ("-lmax", "specify maximum harmonic degree to use in reconstruction")
+   Argument ("value", "the maximum harmonic degree to use").type_integer (2, 8, 1e6);
~~~

Clearly, the description of the `value` argument is completely redundant, given that it's explained perfectly clearly in the Option description. This type of repetition happens pretty much every time - at least it happened enough that I decided it was better to ignore these fields for Options and just make sure the Option itself documented its arguments clearly. In practice, I found it much more natural to describe all these arguments there anyway, since they naturally make more sense in the context of the option they relate to.

What I might do is update the documentation to clearly indicate that the description field of Arguments to Option is ignored, these should be documented in the Option description. Could also add an `assert()` to catch these cases and alert the developer earlier...?

Note this is also an example where setting a default value is actually ill-defined (I'm talking about #334 here): in many cases, the default `lmax` used would depend on the input data. So it's another good reason to ditch these default values...
