### ISSUE TITLE
GUI: ROI tool change copy slice behaviour

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#345]
It might be worth changing the "copy slice" behaviour to pushing rather than pulling:

If one draws a ROI in a single slice and presses "copy slice:" "Above" or "Below" the ROI gets deleted. It is not obvious that one has to change the viewer first by one slice. I would suggest to change the text to "Copy to slice" "Above" and "Below". Pressing the button I would change the viewer focus to the new slice and then copy the ROI from the previous slice. Just a minor improvement but it would have saved today two people 5 minutes of their lives.

**Comment by thijsdhollander** [comment]
Not sure... I must admit the current logic worked better in my head (but it's a personal thing probably).  I think it's because my intuition always was/is that all of the ROI tools act on (as in: modify) the current slice.  For drawing/erasing, it's of course common sense; but somehow that logic extended (for me) to other functionalities as well: so I naturally expected the copy slice behaviour to work as it does.  In most copy scenarios, you'd probably use that function as an "initialisation" of the next slice anyway right?  I mean, you'd always end up switching to that slice to at least check it, an probably further edit it as well?

Either way, it's always worth making the label more explicit though: "copy to slice" if you'd prefer the push behaviour, or "copy from slice" if the pull behaviour were to remain.

**Comment by Lestropie** [comment]
Yeah it was difficult to decide on this one. Went with the existing behaviour because:

* If the 'copy slice from above/below' erroneously clears the current slice, the old data is only one undo button press away. Or if 'above' was selected instead of 'below' or vice-versa, you just click the other one.
* With pushing the current slice data to an adjacent slice, you then have to navigate up/down to verify whether the slice was pushed in the correct direction. If it was not, the 'undo' button can undo the write, but you're no longer in precisely the same state as you were before the error occurred (the focus has likely changed).
* Thijs's point RE: all 'edit' functionalities operating on the current slice.

Ultimately I don't think either is going to 'feel' correct for all users. And I didn't think having four buttons was going to work. If as you say it's been a stumbling block, we could potentially have a config file entry controlling whether it pushes or pulls; but that doesn't solve the problem of default behaviour.

**Comment by maxpietsch** [comment]
From a workflow perspective, if one wants to copy a ROI to many slices I would prefer the "change slice and then pull the ROI" behaviour as it does not require repeated clicking and slice changing. That the undo only the last step is a lesser evel I think. 
I wouldn't add 2 more buttons. We could maybe add a checkbox allowing to auto advance to the next slice before copying the ROI? This keeps the logic of all edit functions working on the current slide and allows for fast copying of the ROI to multiple slices. 
But in any case, I agree that "copy from slice" would prevent the initial confusion we had.

**Comment by jdtournier** [comment]
Just thought I'd throw my opinion in there, for what it's worth...

What I struggle with is which is the slice above/below if we're not projecting axial? And even in the axial case, it's not always easy to remember which way we just moved in the slice stack, and so which of the two is the right one... Early onset dementia, I suppose...

So how about a more overt copy/paste...? With corresponding Ctrl+C / Ctrl-V keyboard shortcuts? You'd only need to note the projection and slice number, and you could then replicate it ad nauseam... Only thing that would need special handling would be what happens if you switch to a different projection (I'd say paste shouldn't work in that case), and what happens if the slice to be copied is further modified before pasting (choices are to invalidate the paste buffer, or make a proper copy of the slice at copy time). Thoughts...?

**Comment by maxpietsch** [comment]
> it's not always easy to remember which way we just moved in the slice stack

Isn't "above" and "below" the same as the directions the arrow keys or mouse wheel change slices in the viewer? Not sure if I understand what the problem is especially if we use the auto advance feature to actively change the slice before copying the ROI.

I think invalidating the paste buffer could equally cause confusion. And my guess is that most people want to copy a ROI only to adjacent slices most of the time, modify it in the new slice if necessary and repeat. So I am not sure how useful a copy/paste feature is if you annotate anatomy that is not rectangular.

**Comment by maxpietsch** [comment]
And as a side note: I just played a bit with the Egyptian god of the dead and ImageJ. Their ROI copy features are not exaclty elegant...

**Comment by jdtournier** [comment]
> Isn't "above" and "below" the same as the directions the arrow keys or mouse wheel change slices in the viewer? 

Should be. Doesn't mean I don't have senior moments from time to time, since in my head above/below refers to anatomical superior/inferior, so I have to mentally maps that to arrow up/down to whichever I'd just pressed. Not a big deal by any stretch...

> Not sure if I understand what the problem is especially if we use the auto advance feature to actively change the slice before copying the ROI.

I'm not I'd be comfortable with that idea - the problem is you don't get to see what the slice was before it gets modified. If you're editing a high-res T1, it's not always obvious to figure out which way the slice just moved, and you might end up modifying the slice you just edited _before_ the last one - if that makes any sense. In other words, if you're editing slice 56, you copy over to slice 57, edit that, then press the wrong button and copy your edited slice 57 back down to slice 56, you might not notice you've gone the wrong way if it's set to auto-advance - you'll just see the copied slice as expected, and the T1 slice will be a bit different, again as expected, but you'll be going over the same slice again... And don't underestimate how easily this can happen - I've done that plenty of times... This wouldn't be an issue with the copy_from approach - it would be obvious that you've already gone over the slice youI think invalidating the paste buffer could equally cause confusion. 're about to overwrite. 

> I think invalidating the paste buffer could equally cause confusion. 

Agreed, which is why I reckon it would be better to grab the whole slice into the paste buffer at copy time - if we did agree to go with that plan, that is...

> And my guess is that most people want to copy a ROI only to adjacent slices most of the time, modify it in the new slice if necessary and repeat. So I am not sure how useful a copy/paste feature is if you annotate anatomy that is not rectangular.

Also agree with all of this. What's attractive about this approach would be that everyone is familiar with copy/paste. And it makes it very clear which slice is being copied to which slice, in a very visual and immediate way. I'd probably feel more comfortable using an approach like that for that reason alone - no need to remember whether I'd moved up or down the stack, just grab that one and paste it here...

**Comment by jdtournier** [comment]
> I just played a bit with the Egyptian god of the dead and ImageJ. Their ROI copy features are not exaclty elegant...

I've never used them... How do they work and what's the problem with them...?

**Comment by thijsdhollander** [comment]
> What's attractive about this approach would be that everyone is familiar with copy/paste. And it makes it very clear which slice is being copied to which slice, in a very visual and immediate way. I'd probably feel more comfortable using an approach like that for that reason alone - no need to remember whether I'd moved up or down the stack, just grab that one and paste it here...

I was actually thinking about a traditional copy/paste feature when I was typing my initial response.  Even started typing about that as well, but deleted it again because I thought it was a bit overkill (and indeed given that in practice you will typically only copy/paste to neighbouring slices, which the current functionality perfectly caters for).  But I agree that it would (also to me) feel much more natural if I could ctrl-c ctrl-v with a touch of the scroll wheel in between.  And I'd never end up ctrl-v'ing on the wrong slice that way (hence not needing to undo: better to prevent than to fix!).

From a practical point of view: I reckon it should be a copy of what was there at copy-time (that's the intuition that most software uses for copying and pasting information).  And there should indeed be a limitation that you can not paste on slices along other dimensions (there's no well defined behaviour for that I can think of... unless you paste everything in relation to the focus, itself in relation to the focus when it was copied; ok, that already confuses me as I'm trying to explain it; probably not a good idea).

As a side note: I'm also not very keen on extending the current functionality by having it automatically advance a slice (not even if optional I think).  Not sure if I'm susceptible to the same early onset dementia as @jdtournier , but I reckon I'd also be very easily confused by such a behaviour myself...  Now that I think of it, the above/below terminology is also a little bit confusing for me as well (I also have the reflex of reasoning in anatomical terms about them).  Would "previous / next slice" be a better (more general) labelling..?  It isn't much more clear I must admit; but maybe it's less suggestive of other (anatomical) interpretations...?

**Comment by maxpietsch** [comment]
Back in the day when I used to segment images I always had the 3 projections viewer open and moved from one slice to the next. That way you see immediately whether you moved in the wrong direction. But this has the disadvantage that one limits screen space for the editing view. And repeatedly pressing the above or below button but not mixing them seems like a manageable cognitive challenge even when segmenting images with a glass of :wine_glass:. But I agree, if copy and paste works in all cases, then it's definitvely intuitive. The question is what you want to do when the projection has changed. One could sample the ROI again in the original position (using the ROI's centre of mass) with the new projection and copy that to the new projection. But that might be more confusing than simply not allowing it.

Osirix has a propagate to current slice button and hidden in the menu a feature to propagate it to the whole image or alternatively up to a certain slice number. If the slice thickness is constant, one can use the "generate missing ROIs" feature which interpolates the ROI for slices where it is still missing. This takes about 30s on my Macbook air for a simple polygon ROI for a few slices in a T2 image. (What is nice though is that one can edit ROIs by draging their corners. And the polygon (Bezier?) feature is neat as it creates smooth curves through arbitrary control points.)

With ImageJ's ROI manger you can copy and paste ROIs but it also copies the content of the ROI. And I think each ROI belongs to a certain slice only. By selecting two manually drawn ROIs, one can (crudely) interpolate between these via right click "interpolate ROIs". An alternative is the Segmentation Editor plugin <http://fiji.sc/File:SegmentationEditor.flv> which basically does the same but allows to group ROIs. It interpolates between multiple slices but one still has to draw them manually. (I might be biased as my master thesis was motivated by a deep aversion against using ImageJ's 2D ROI tools.)

But then again. I would be happy with a simple addition of "from" in the GUI to clarify what it does.

**Comment by Lestropie** [comment]
Think I'm agreeing that an auto-advance on slice copy may cause more problems than it solves. Could change the GUI text to something like '_Import from_ slice: Above/below' to be even more explicit. Longer-term I think the copy/paste approach is perhaps better; going to be a while before it gets to the top of the priority list though.

**Comment by jdtournier** [comment]
Yup, agreed. Simplest 'fix' for now is adding that 'from'  on the button. I don't think 'import' makes much of a difference, if anything I think 'copy' is simpler & clearer. We can revisit the copy/paste idea singer other time. Maybe create a separate wishlist issue for it....
