### ISSUE TITLE
ROI tool: Off-axis draw bug

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#372]
My prior modifications to the ROI line drawing has unearthed a problem with the way the ROI tool snaps the window orientation to the ROI being modified.

`mouse_press_event()` calls `window().set_orientation()` based on the ROI transform and selection of the nearest axis, which is fine. But `mouse_move_event()` uses `window().get_current_mode()->get_current_projection()`, and this is _not_ updated. The scannerspace position under the cursor is therefore wrong, and the calculations performed to force the focus point to stay precisely on the snapped axis result in a voxel position that's _way_ outside the FoV.

In previous code it would have just seemed as though the first mouse click snaps the view and draws under the click point, but mouse movements wouldn't work until you click the mouse a second time. But with my line-drawing code, the program hangs as it performs a ray-trace / cylinder draw between these two points.

**Comment by Lestropie** [comment]
So looking into a solution for this is raising a few eyebrows due to #162. It doesn't seem to account for the fact that different ROIs being drawn to may have different transforms.

- Currently, the code for fixing the camera view to the ROI image axes is executing for _every selected ROI_; which probably means that the view will end up locked to the _last_ selected ROI rather than the first.

- The `ROI` class contains `current_axis` and `current_slice` members, for remembering these properties between mouse click and button release. However these may differ for different ROIs.

- The code responsible for altering the depth of the focus point so that it lies on the slice of interest (and won't break the draw functions) may break down if the selected ROIs have different transforms, since they depend on the camera projection (and there can only be one of those).

So I think there's two options here:

1. It should be possible to snap the camera to the first ROI selected only, store a slice/axis for each ROI independently, and force the focus point onto the appropriate slice for each ROI independently. It would mean that if drawing to ROIs with different transforms, the 'effective' focus for each may change depth as you move the mouse, depending on the slice angulation of each ROI relative to the first ROI selected.

2. Only permit drawing to multiple ROIs at once if the rotation component of the transforms match. They could have different FoVs / voxel sizes, but it'd guarantee that snapping to the axes of one ROI would be equivalent to any of the others.

3. 3D undo stack :-/

Need input before I progress with this.

**Comment by jdtournier** [comment]
Ah crap...

So relating to your options:

1. I don't think that'll solve the issues that the snap to axes thing was designed to remedy: drawing off-axis is going to lead to weird-looking ROIs, with unexpected holes in them, or other strange effects, particularly for non-brush type interactions. For instance, drawing a rectangle currently works  because it's very clear which voxels are included when the corner voxels both lie within the same slice - it's almost impossible to do this well if they're not. And if the axes don't match between ROIs, all you can guarantee is that the start voxels are in the expected location, or the end voxels are in the expected position - but not both. The start and end positions that define your rectangle lie on different slices of the different ROIs. Even the axes that define the directions for the edges of your rectangle might differ, in which case the rectangles themselves might be completely different...
  
  One solution is to somehow figure out how to render a rectangle onto a 3D volume when that rectangle is oriented arbitrarily - then we wouldn't need to snap to axes at all. But that's a hard rendering problem, and I don't think we will ever come up with a solution that behaves intuitively and accurately. And imagine if you have to support the fill function in this situation... 

2. That's what I would recommend. I was also thinking that we should get feedback about the use cases that actually motivated this change in the first place. I can understand if you want to set the opacity of all ROIs identically, which would require multiple selection, but I'm struggling to see the use case for actually _drawing_ these ROIs simultaneously. The original feature request (#162) from @fsadeghian didn't address this, it might be that multi-draw was never actually necessary...?

3. ? That would imply we can support drawing on arbitrary planes in the first place, which we can't - unless I'm missing something?

**Comment by thijsdhollander** [comment]
I don't think we should actually be supporting multi-*drawing*.  When multiple ROIs are selected in the list, drawing should simply be disabled, I reckon.  We could still add an informative dialog / pop-up if a user tries to activate drawing while multiple ROIs are selected (just so they know why it's not working, and get information on how to proceed, i.e., select only a single ROI from the list).

...and of course, never, ever, proceed anywhere near allowing drawing on arbitrary planes.  That's just bound to open up a babouchka-style box of Pandora.  That would haunt us for many not-so-beautiful years to come. :smiling_imp:

**Comment by maxpietsch** [comment]
I implemented multiple drawing to be as consistent as possible between single ROI and multiple ROI selection. But I am not too sure how useful this is in practice. I was admittedly not aware of the problems this causes if ROIs have different transformations. I think it might be confusing to the user if  drawing if multiple ROIs are selected works for some ROIs but not for others. So I am in favour of removing this feature unless it is actually useful.

**Comment by Lestropie** [comment]
> The original feature request (#162) from @fsadeghian didn't address this, it might be that multi-draw was never actually necessary...?

I'll ask before making a decision on how to proceed. Missed her today.

> > 3D undo stack :-/

> ? That would imply we can support drawing on arbitrary planes in the first place, which we can't - unless I'm missing something?

If the whole tool were built around 3D drawing, then drawing onto two ROIs with different transforms wouldn't matter - each would just have a 3D brush applied independently based on the mouse path (though rectangle and fill operations would have to be more stringent). It's the fact that we snap to the ROI axis and exclusively permit single-slice draw operations that makes this a problem.

> I think it might be confusing to the user if drawing if multiple ROIs are selected works for some ROIs but not for others.

Could certainly have an informative error message pop up if the user tries to activate draw mode / commence a draw operation, but the current ROI selection isn't compatible. Indeed, if it's only multi-selection for changing e.g. opacity that's required, and multi-ROI drawing isn't, then you just disable that button when multiple ROIs are selected and change the tooltip.

**Comment by thijsdhollander** [comment]
I think, worst case, multiple drawing could actually lead to mistakes that easily go unnoticed.  For many existing region drawing scenarios (not all, but a lot of existing realistic ones), you're looking at regions that don't overlap.  In a lot of these cases an opacity change is not required to do a good job.  But if you accidentally select multiple ROIs in the list, and start multi-drawing, you might not even know you're multi-drawing (as only the top ROI colour will show when you draw).  If you then select just the second one and draw your real second ROI, you might be left with that second ROI image also containing the first ROI, without you being really aware at that stage.  This would happen because (and I think this is quite realistic) you might not expect a multi-drawing feature (it's not very common in existing software?).

This is a worst case scenario, but not an unrealistic one.  The most common scenario for most users will still be drawing ROIs on the same grids (same transforms).  Specifically here, from a technical point of view, it's easy to allow multi-drawing; but also specifically here, from a GUI point of view, the main risk of mistakes exists when allowing multi-drawing...

So, just in my opinion/view, multi-drawing is a very advanced feature that only pays off in a limited specific use case.  I reckon, for these scenarios where you want to go for 2 or more regions that share extensive parts (that you wouldn't want to draw manually twice), a user could simply draw that big shared part, and then make a copy of that ROI file; and work further from the 2 ROI files for the parts that are to be customised separately.  Or maybe create 3 ROI files out of the box; of which one is for the shared part, and sum that shared one afterwards with both other files that have the unique parts.

So all in all, it feels to me the benefits of multi-drawing as a feature are a bit limited compared to both the risks of user-made mistakes; and technical hurdles (as well as unforeseen mistakes) on our end.

**Comment by jdtournier** [comment]
> multiple drawing could actually lead to mistakes that easily go unnoticed

Fully agree. The more I think about this, the less I like the idea of multi-draw... As far as I can tell, the only sensible reason for multi-_selection_ is to allow setting the opacity identically for all ROIs. I have to admit, I can't think of a good reason why you'd ever want the opacities set differently per ROI. So maybe the best thing to do is revert to single draw, single selection, and have the opacity slider apply to all ROIs...?

**Comment by maxpietsch** [comment]
Agreed. I asked a few clinicians whether they would want the multi-ROI draw feature and all I received was confused faces...

**Comment by Lestropie** [comment]
Just asked Farnoosh: She doesn't recall what study it was for, why she wanted it, or whether / how she used it. So I reckon we remove the feature altogether. Then once that's done I still need to figure out a solution for the line search infinite loop; though hopefully my learnings from #424 will help.
