### ISSUE TITLE
mrfilter removes gradient table

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#375]
Filtering a DWI image removes the gradient table from the header which prevents subsequent analysis.

**Comment by jdtournier** [comment]
I'm assuming this is using the version on `master`?  Chances are the `updated_syntax` version will leave it as-is (since there is no implicit parsing of the DW gradient table any more, it's just treated as a generic header entry). If not, then we'd need to check which `Header` is used as the template for the output image.

**Comment by bjeurissen** [comment]
Indeed using `master`

**Comment by jdtournier** [comment]
Sorry, could you confirm whether `updated_syntax` is affected...?

**Comment by thijsdhollander** [comment]
Slightly in this context: some commands that take a DWI dataset and output "something else" (tensors, FODs, ...) do keep the gradient table.  Does this make sense?

**Comment by thijsdhollander** [comment]
> Sorry, could you confirm whether `updated_syntax` is affected...?

Did a quick check using `mrfilter` with a smoothing filter and all default values.  The gradient table is preserved in `updated_syntax` in this scenario.

**Comment by Lestropie** [comment]
> Slightly in this context: some commands that take a DWI dataset and output "something else" (tensors, FODs, ...) do keep the gradient table. Does this make sense?

We had this argument somewhere (can't find it). I thought not. I lost :-(

**Comment by draffelt** [comment]
> Slightly in this context: some commands that take a DWI dataset and output "something else" (tensors, FODs, ...) do keep the gradient table. Does this make sense?

My preference would be to not include the gradient table in the FODs or tensor files. Mainly because I don't see any benefit of having them there, but also because it gets a little confusing performing downstream operations. 

For example, what if you want to truncate the SH series? Currently `mrconvert -coord 3 0:14` will automatically truncate the DW directions (assuming it is a DWI). 

Also, what do we do when transforming FOD images. Apply the same linear affine transform (which will be the wrong thing to do if the transform is non-rigid)? Remove the gradients directions since they are definitely not related to the reoriented FOD images? Or just ignore them.

**Comment by jdtournier** [comment]
I have a feeling I'm about to lose again - not sure I like this democracy thing...

So yes, we did have that argument a while back, and my opinion was that I'd prefer to keep that information in the header for processed data too, since it may come in handy later on when trying to figure out what happened (e.g. someone sends you their FA map asking why it looks all wrong). My point of view was that if it doesn't hurt to preserve the information, then why go out of your way to remove it? It's pretty obvious when the image isn't a DWI, and that in this case the DW gradient table relates to the DWI that the image was presumably derived from.

But I agree there are edge cases in the various apps that try to handle the DW gradient table if present, that result in less than optimal outcomes... That said, I don't think it would too hard for mrconvert to only modify the gradient table if the number of entries matches the number of volumes (in which case there's a very good chance the image was the DWI, and you do want to make sure the directions still match afterwards) - otherwise, you'd treat the DW gradient table just like any other generic entry: it's there for information. 

As to transforming FODs, I don't think you'd ever want to touch the DW gradient table - if it's in the header, it's there for information about the original acquisition, there would be no reason to modify it.

But if people feel strongly that it should be stripped out, I don't have any major objections. Like I said, the only reason I felt it should stay is because there's no harm in keeping it... And you'd actually need to go out of your way to explicitly strip it out in the relevant apps - that includes related apps like `mrmath` - if averaging  along a non-spatial axis - and probably others too. I just feel it's simpler to leave it in for information - doesn't hurt, and might come in handy from time to time...

**Comment by thijsdhollander** [comment]
So, overall, I do fully agree that keeping information in the header if it doesn't hurt is a good thing.  I'd be silly to explicitly go out of our way to strip it if there's no harm in keeping it (and occasionally it might just happen to figure out what went wrong along a pipeline or something).  That's definitely a principle I took into account when questioning the presence of the gradient table in non-dwi files further down the pipeline track.
Another "principle" (let's call it a guideline, principle sounds a bit too strong maybe) I try to take into account when possible is that information (in a header) should not be "wrong" in relation to the data.  I intentionally say "wrong" in the "..."-way there, because it's very much open to interpretation.  I wouldn't necessarily call a gradient table in the header of an FA file wrong, because there's no way to misinterpret that situation: the gradient table will in any realistic scenario have more than 1 entry, and the FA file is just a 3D scalar map.  Let's say I'd use mrtransform thereafter to rigidly rotate the FA map, I'd say it starts to approach the boundary of "wrong"-land (even poking into it, I'd personally say).  It'd still be okay-ish if mrtransform adds information to the header about the rotation that took place (so there's a way of making a consistent reconstruction about how the gradient table in there actually relates to the image(space) at hand); or if mrtransform in that case would actually rotate the gradient orientations as well... but if not... I'm starting to doubt the usefulness of the gradient table in there, up to the point where I might question whether it's actually not misleading or "wrong".  So yeah, information is better than no information IF the information doesn't hurt or is wrong (misinterpretable in any way).  But information that has (even just) the potential to be wrong.. I wouldn't say that is to be preferred over no information, necessarily, at all times.
But I think what made me question it the most, is in the case where the gradient table comes along in 4D images.  And admittedly, those are quite (if not the most) central concepts in MRtrix' processing pipelines: the models (tensors, FODs, other SH fits, ...).  I wouldn't even say it's *that* unlikely that, e.g., someone feeds a single shell (no b0's) DWI dataset with 45 measurements (because they read in some obscure ISMRM abstract or NeuroImage paper that that is the minimum needed amount of directions for HARDI at b=3000 :wink: ) into dwi2fod, obtaining a 45 SH-coefficient FOD file; and in the current state of things it would come with a 45 entry gradient table.  That's definitely a scenario that's (trying to) invade "wrong"-land there, and it will lead to all sorts of quirky behaviour along the further pipeline.

Or let me even put it the other way around, as to possible advantages of making sure that a tensor/FOD/... file doesn't pack a gradient table: just as an example, mrtransform being able to rely on such a property, would empower it to see that certain 6, 15, 28, 45, ... 4th dimension sized images are *not* FOD files (but DWI files, because (only) they pack a gradient table), so they should not (automatically) be subjected to FOD reorientation.

Dave's example:
> For example, what if you want to truncate the SH series? Currently mrconvert -coord 3 0:14 will automatically truncate the DW directions (assuming it is a DWI). 

...actually shows that certain apps already make this assumption (even though it currently does not hold).

I do admit that realistic scenarios where, in the current state, things go wrong *big time* and this also manages to slip under the radar of a reasonable user are probably sparse (and this is a bit of a discussion about a first world problem in that sense), but still I feel that the potential inconveniences are a little bit bigger that the potential advantages to be gained by keeping the gradient table in the header.  As Dave's example shows, it's not unrealistic for the gradient table to be essentially broken along a pipeline anyway. :wink: So in a better world where democracy allows for voting on scales of 1 to 10, I'd say I vote a 6.5 to not keep the gradient table in (at least) a tensor/FOD/SH file's header. :-)

**Comment by jdtournier** [comment]
OK, just one little comment after reading through your post (took a while...): there's a suggestion that if we remove the gradient table from processed files, we might be able to use its presence in the header to indicate that the image contains DWIs. I also had this thought, but I just can't see that we could ever _rely_ on this assumption, so I don't think that would be a good idea...

Anyway, if you all feel it would be better to strip the gradient table out of the header for obvious operations like `dwi2fod` or `dwi2tensor`, then feel free to do so. As @thijsdhollander says, there's arguments for and against, but really the only arguments for keeping the gradient table is that it _might_ potentially come in handy, and that it's easier just to keep it...

**Comment by bjeurissen** [comment]
I agree that it might potentially come in handy, but semantically I think it makes more sense to remove them for the output of operations like `dwi2tensor` and `dwi2fod`. As a user, I have always found it confusing.

**Comment by dchristiaens** [comment]
Just my two pennies worth, but @jdtournier once pointed me to The Art of UNIX Programming, and I believe one of their principles is that commands should ideally produce straightforward, predictable output. In that regard, I am also in favour of stripping the gradient table from the header in all `dwi2*` commands.

**Comment by draffelt** [comment]
I've recently come across a warning on several occasions complaining that my output file does not contain the same number of volumes as my DW scheme....when my output was not a DWI. I know what is going on, but it might be slightly confusing for most users.

**Comment by thijsdhollander** [comment]
Oh yeah, I get these all the time.  As I speak, there's a few

```
mrconvert: [WARNING] Diffusion encoding of input file does not match number of image volumes; omitting gradient information from output image
```

sitting in a terminal right next to this window.  The input to those `mrconvert`s being an FOD image, of which I just wanted to extract the first volume or so.

**Comment by jdtournier** [comment]
So should this warning be relegated to INFO or DEBUG level...?

**Comment by thijsdhollander** [comment]
That would probably be a good idea.  I'd be inclined to push it all the way down to DEBUG level... but it's tricky... for an actual DWI dataset, it's probably something users would want to be aware of.  So maybe INFO is a reasonable compromise...?

**Comment by Lestropie** [comment]
Random thought that may or may not satisfy both camps:

For any command that inputs DWIs and outputs non-DWIs, _move_ `dw_scheme` to a different key, e.g. `original_dw_scheme` / `basis_dw_scheme`. It's still there and can be extracted for Reasons, but doesn't get accessed by any command that compares the DW gradient table to the image volumes.

**Comment by draffelt** [comment]
I'd be happy with that

**Comment by jdtournier** [comment]
Yep, I can live with that, sounds good.

**Comment by thijsdhollander** [comment]
Sound good to me too!
