### ISSUE TITLE
Qt 5.2.1 on Mac OS X 10.9

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#38]
When installing on a new machine, following the exact Wiki instructions, the viewer and other Qt-based components won't build.

From what I figured out, the precompiled version of Qt 5.2.1 (the most recent version, hence the default install), is configured for mac 10.8, whereas some of it's components don't link under 10.9 unless you explicitly configure the correct path for the build. (See [this](http://jwintz.me/blog/2013/10/30/qmake-the-mavericks-case/) and [this](http://www.qtcentre.org/threads/58639-Problems-with-linker-after-updating-from-5-2-0-to-5-2-1-MacOSX) article)

The problem is easily fixed by opening up the config.default file and manually changing ".../.../MacOSX10.8.sdk" into ".../.../MacOSX10.9.sdk" in both the qt_cflags and qt_ldflags variables. However, I have no clue whatsoever on how to set this permanently (?).

Alternatively, users can work with Qt 5.2.0, in which the issue does not occur.

**Comment by will180576** [comment]
I'm having problems in OS X Yosemite, I have followed the instructions, I can even see the moc file in location  PATH=/path/to/Qt5/5.2.0/clang_64/bin:$PATH but it still gives me the error.  I have re-installed XCode and X11, still nothing.

**Comment by jdtournier** [comment]
Are you sure you're having the same issues Daan reported here? It doesn't look like it, since you're not running the version of Qt reported as problematic...

Are you simply having trouble with the installation? In that case, you'd be better off asking your question on the [MRtrix3 discussion forum on Google+](https://plus.google.com/u/0/b/110975114527807720518/communities/111072048088633408015), since the GitHub issue tracker is really only used for bug reports - most users are unlikely to be monitoring this...

For anyone to help you, you'll need to provide as much information as you can about the problem. Which stage is failing, `./configure` or `./build`? Can you post or attach the entire contents of the `configure.log` file and if you have it, the `build.log` file? If you have neither, then the complete copy/paste dump of your terminal session would help.

Cheers,
Donald
