### ISSUE TITLE
Change handling of OpenGL context 

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#392]
Currently the bulk heavy lifting of OpenGL context checking is done by `struct GUI::MRView::Window::GrabContext`. This is however not visible to the DWI renderer, which is used in both `mrview` and `shview`; also the renderer is used by both `MRView::Window` and `DWI::RenderFrame`. So this functionality probably needs to be shifted down to the `GUI` namespace.

Other possibility is having a separate context for the `RenderFrame`; but that may preclude the overlay functionality...? Haven't yet played with it enough to wrap my head around it fully.

**Comment by jdtournier** [comment]
I'm not sure this is necessary, since there is no scope for confusion between the different GL contexts in `shview` - unlike MRView, where things can get weird. That said, I might be wrong, given how recent versions of Qt work (see below) - maybe we should use that framework within `DWI::RenderFrame` too... Thankfully it is already available outside of MRView - it's in the `src/gui/gui.h` header, you'll find the `MRView::Window` version is a very thin wrapper around that.

Just to clarify things, `DWI::RenderFrame` will have its own context (it inherits from `GL::Area`). It's the `DWI::Renderer` that will be used for the overlay (using whichever context is current at the time). So the ODF preview window includes a `DWI::RenderFrame` with its own instance of `DWI::Renderer`, while the main ODF tool uses the main window's context and also has its own instance of `DWI::Renderer`. 

Things get weird in Qt>=5.4 since each top-level window has one single context - in previous versions you could have an OpenGL widget with its own independent context embedded within a larger top-level window. This makes things really complicated when docking and undocking: Qt>=5.4 will create or destroy the context, and all the GL initialisation has to be run again to set things up in the new context - but it's not obvious when that happens, and breaks the encapsulation for all the GL buffers and textures (since they get destroyed without invoking their destructor, but the objects IDs remain non-zero, so MRView thinks they're still active). Which is why we've make the ODF preview a separate, non-dockable window (as per #266)...

Anyway, that's probably more information than you wanted, I'll shut up now...

**Comment by Lestropie** [comment]
No, that's useful. Still a bit stuck with this though.

The `DWI::Renderer` needs to be able to set the context whenever it e.g. receives data. In `mrview` there's separate renderers for the preview tool and the overlay; so each instance of the renderer needs to save some reference to whichever context it needs to grab. But the current context handling is all based on statics.

Had a go at it, I'll find out tomorrow if it actually works.

**Comment by Lestropie** [comment]
OK, I think this is in control now (on the odf_dixel branch). Had to change the context management functions away from statics, but I can now open the ODF tool with preview and close on QT5.5.1 with no assertion failures.

**Comment by jdtournier** [comment]
Sorry, didn't have a chance to get back to you yesterday. Just had a quick look at your changes, I don't understand why you needed to move away from statics. The changes you've made to the context handling functions seem pretty superficial? Looks like you've moved them from being static members of the `App` class to standalone functions in the `Context` class? This wouldn't change much, you were already able to invoke these using e.g. `App::GrabContext()`. I guess `Context::grab()` is cleaner...? But it seems like there was something more fundamental here, what was the problem exactly?

**Comment by Lestropie** [comment]
Yeah the move out of the App class was not actually required, it's just where it ended up as I was mucking around. I think the main error it was spitting at me was that the static functions / structs wouldn't accept non-static parameters. Which is needed as the DWI renderer can exist in two different contexts. But now it's working I can attack it from the other direction and see where it snaps.
