### ISSUE TITLE
New binary: mrslice2image

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#4]
In some cases it is useful to output a slice of an image volume to an image file at native resolution, rather than using the `mrview` screenshot tool. This can also simplify ensuring that the intensity scaling between different images is consistent.

Desired features:
- Either receive a pre-cropped image from mrconvert, or user provides -coord options to specify where they want the slice(s) to be
- If input is 4D and the 4th axis has dimension 3, output as RGB colour image
- Option to manually specify minimum / maximum image intensity (useful for outputting multiple images that should have a common colour bar, even if they don't all have the same dynamic range). Otherwise the intensity range is determined from the image data.
- Output as .tga; this won't require any code dependencies, and should be supported by more software than .pgm & .ppm
- Apply colour bar mapping to image on output
- Options to flip / swap axes (maybe a comma-separated list providing x,y axes for output image as +/- input axis indices)

**Comment by jdtournier** [comment]
Just been thinking about this a bit, since I've recently had to implement some [TIFF import code](https://github.com/MRtrix3/mrtrix3/tree/tiff_image_format) (to support loading data from a confocal microscope). I reckon this would be best done by implementing dedicated `ImageIO` and `Formats` handlers, as is half-done for the TIFF case: it's read-only currently, but wouldn't be too hard to finish off to support output too. This works well combined with the [multi-file numbered image syntax](http://mrtrix.readthedocs.io/en/latest/getting_started/image_data.html#multi-file-numbered-image-support), which allows direct import and export _and_ slice/axis selection if required. One recent example using the TIFF import branch to load a set of numbered images into a 4D stack:

    mrconvert tiff/images-[].tif -axes 0,1,4,3 data-[].mif

where each TIFF was RGB. This splits each of the RGB channels into separate files, while concatenating the stack of images. The `-axes` option is required here since the numbered file handling will treat the numbering as an additional dimension, meaning the z-slices appear along the 5th dimension. 

Output could similarly be handled to produce e.g. a set of coronal slices for every 3rd slice of a dataset (3D in this case):

    mrconvert data.mif -coord 1 0:3:end -axes 0,2,1 slices-[].tif

Note that the tiff import also handles multi-page tiff images, loading them all up as a 3D stack. Would be good to support that for output also. 

If there is demand for similar functionality for PNG import/export, I guess it would be just as simple to support (simpler in fact since PNG doesn't support multi-page). Just requires someone to code it up...

**Comment by Lestropie** [comment]
If you're supporting TIFF as an image format rather than using an explicit conversion tool, then it might make sense to do the same with PNG (or just use TIFF to serve the purpose). The disadvantage is that if import / export were done using a dedicated command, you could have command-line options specific to such importing / exporting without affecting more general tools (e.g. see list in first post). I *think* the only one of those that wouldn't currently be achievable with existing tools is mapping to a colour bar; the others may require a bit of piping gymnastics, but should be possible.

So maybe have a "2D image type" format / handler that could conceivably branch on file import / export for different image formats, and create a new lightweight command to apply the in-built colour maps to greyscale data (possible since each colour map now has a C++ functor alongside the GLSL code)? Reckon that'd cover everything I want.

**Comment by jdtournier** [comment]
I'm closing this since I reckon it would all be better handled via #1032 & #1541
