### ISSUE TITLE
Resetting windowing (Esc) "lags behind"

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#405]
Cryptic title to basically describe this: when looking at a slice, then changing the slice direction (e.g. from axial to sagittal by pressing 's'), then hitting escape to min-max window... it uses the min and max of the slice before the slice direction was changed (e.g. the axial slice of my previous example, not the sagittal one).
To easily see this, scroll to, let's say, an axial slice near the top of a brain-masked T1 or something (i.e. where the intensity range shown is quite small), then switch to a coronal or sagittal slice by just hitting 'c' or 's' once, then pressing escape.  Given you set the "experiment" up as such, it will be quite obvious that the range is way to small for the coronal/sagittal slice shown.

This is using `mrview` in the updated syntax branch (haven't checked master).

**Comment by jdtournier** [comment]
OK, that probably shouldn't happen, the design should handle that. I'll give a bit of background about that, might help figure this out...

To figure out the min/max for the display, the approach used is to update the min & max values when the corresponding texture is updated. So it's done slice-wise when the update is for a single slice (the default at start up), which applies to slice, orthoview, and lightbox modes _if locked to axes_. As soon as the 3D texture is loaded, it'll compute the min & max for the whole volume and use that instead. Note that even if you go back to locked to images axes, it'll still use the 3D texture, since it's already been loaded into the GPU - why bother copying it over again? That means that the min & max values will no longer change after a load to 3D texture - as soon as you've hit that lock to axes button, or switched to volume render mode, the range is fixed. 

In case you're wondering why I'm using this approach: the idea is to support really fast command line use where possible by avoiding a full 3D load when slice-wise will do. If we wanted to set the range once for the whole volume, that's as bad as a full 3D load. So we set the range slice-wise to start with. Once we need to load to 3D texture, it's near impossible to figure out the right range for the slice displayed anyway - it'll be off-axis, and might involve several slices in different orientations anyway (think lightbox and orthoview modes), or the full volume for the volume render. And once it's fully loaded, there really shouldn't be any need to update the slice-wise textures, so we don't - but that means we can't figure out the min/max for that slice, so we keep using the 3D version.

What's strange here is that range should either be appropriate for the whole volume, or updated per slice, which clearly isn't happening. So something isn't working somewhere...

On a related note: I've been struggling a bit lately with some images with extreme values, which totally messes up the display (need to use the view tool to set the range), and also the brightness/contrast controls (since the rate of change is set based on the range). I've been thinking it would be better to use a more robust measure if we can - something like 2 × interquartile range or some similar rank-based measure. It wouldn't need to be perfectly accurate either, we could compute it based on every 10th value or something, which wouldn't require so much sorting, but would probably be close enough to the mark. Or better, use 10% of the data (with a low limit of ~1000 voxels), and figure out how many to skip based on that. I reckon that would make my life much better.

**Comment by thijsdhollander** [comment]
Ok, so through interaction I was (I think) able to define the behaviour potentially a little bit better: long story short, it feels like "the act" of changing (axis aligned) slice orientation by, e.g., pressing 'a', 'c' or 's' is not updating the computed/stored min and max values.  Changing a slice by, e.g., pressing up/down or using the scroll wheel *is* nicely updating the min/max values; i.e., that act is not "lagging behind".  More importantly, by initial implicit suggestion of a "lagging behind" kinda behaviour now seems to be a wrong one: it's definitely more about some actions updating the values, and others (that I would expect to also update them) not doing so.  I can for instance, do the experiment I described previously, and then I can *keep on* switching slice orientations (yet without up/down or scrolling in between): still the values won't update.  "Probing" the values can be done at any time by pressing 'Esc' (it also won't change them, but that indeed makes sense from how you just described the mechanism).

And last but not least, now that you brought up the 3D one: "the act" of switching to, e.g., the volume renderer, is *also* not updating the min/max.  So I can go to the aforementioned hypothetical slice that has a small range of values (making sure my last action is scrolling, so those min/max'es are captured), then switch to volume renderer, then hit 'Esc', and it will use that small range rather than the whole volume one's...  Note that in each of those cases, I don't *have to* press `Esc` before I switch slice orientations or to 3D mode (but I can if I want to).  'Esc' nicely plays its "role" of just probing min/max and showing/reporting that by updating the windowing range; nothing more (which by itself, again, is the expected role of that one).

The behaviour of min/max being fixed after a switch to 3D mode seems to be working correctly; but combined with the aforementioned behaviour where making the switch is not updating min/max, it means you can easily be "stuck" with a wrong min/max while in 3D mode.  And each time you press 'Esc' while in that mode... it reverts the windowing to that wrong min/max range. :sob: 

So what-was-supposed-to-be-a-short-story short: it essentially feels that the acts of switching slice orientations as well as switching to 3D mode, are not updating min/max as (at least I expect) they should.

Maybe a risky suggestion (I realise there's a potential plethora of arguments against this; feel free to shoot it down for those reasons :wink: ): how about always just go for a (3D) global min/max throughout the whole experience.  It would have to be computed only once (and therefore, it could/*should* be a robust definition, i.e., rather based on (but not perse equalling) quartiles, than an absolute min/max; to cope with those pesky extreme outliers).  But yeah, my spider-sense informs me that people probably won't like the idea of losing their slice-wise auto-rewindowing feature... so I do preemptively agree that's would be a major disadvantage...

**Comment by draffelt** [comment]
I think the main reason why it's not a good idea to use the 3D volume
min/max is because it would then require the whole dataset to be loaded,
which means we would lose the snappy-ness of MRview, and the ability to do
things like load 300 images simultaneously over a network.

On Wed, Nov 25, 2015 at 11:57 AM, Thijs Dhollander <notifications@github.com

**Comment by jdtournier** [comment]
Yes, as @draffelt says, the whole point is to avoid a full load from potentially very slow storage. Most of the time, MRtrix will memory-map the images and only pull the bits of data it actually needs. 

As to why things might be going wrong: I think the problem is that the min/max values are only computed on texture update (whether 2D or 3D), but the textures for the 3 planes are actually independent. So switching to sagittal from axial may not trigger a texture update if that texture is already up to date. 

So switching to sagittal the first time would trigger a texture update, and reset the min/max values. Switching back to axial may or may not trigger a texture update, but you can force one by changing slices. If you then switch back to sagittal so that the same slice as before is displayed, that won't force a texture update (and hence no reset of min/max values), and no amount of hitting Esc is going to change that - you'd need to change slice to trigger the update. 

The simplest way around this is to store the min/max values per texture object. Shouldn't be a big deal, but will require a bit of housekeeping to make sure everything works as expected. Do you want to give this a go...? :grin:

The other thing would be to incorporate a more robust windowing method. I reckon what I'd suggested before would be relatively straightforward, but it'll need someone to do it...

**Comment by jdtournier** [comment]
Sorry, one more thing; we might need to think about how to handle the multi-image displays (orthoview and lightbox). At the moment, the min/max values used would be those of the last texture to be updated, which is probably not ideal... It might be that we need to viewer modes to handle setting the min/max values themselves - at the moment, it's handled by the Image/Volume class, independently of how it's displayed.

**Comment by thijsdhollander** [comment]
Hey guys, if anyone feels like it, don't hesitate to take it on... I'm actually on holidays (or at least annual leave) at the moment (no nice Greek beaches though, just Belgian drizzle :sob: ), and will be greeted by quite a few heaps of work when I get back to my Florey desk in January...
