### ISSUE TITLE
problem with configure script on rehat linux installation

### ISSUE THREAD

**Issue by pmccolganni** [MRtrix3/mrtrix3#412]
Dear MRtrix team,

I get the following error when trying to install the latest version;

MRtrix build type requested: Traceback (most recent call last):
  File "./configure", line 174, in <module>
    MRtrix build type requested: """)
  File "./configure", line 164, in report
    logfile.write (('\nREPORT: ' + message.rstrip() + '\n').encode (errors='ignore'))
TypeError: encode() takes no keyword arguments

I have installed previous versions without problems.

I would be most grateful for your help.

Thanks

Peter

**Comment by jdtournier** [comment]
Not sure what's going on here... The last time this line was modified was in May. The error message suggests that your version of Python doesn't support the `errors` argument to the string's `encode()` method - this would make it older than 2.6, which is going back some (it was released in 2008)... I don't think you'd have been able to compile MRtrix at all with such an old version. You can check with:
~~~ShellSession
$ python --version
~~~
If you have a more recent version installed, try invoking it directly like so (edit as appropriate):
~~~ShellSession
$ python2.7 ./configure
$ python2.7 ./build
~~~
or maybe as a fully resolved path:
~~~ShellSession
$ /usr/local/bin/python ./configure
$ /usr/local/bin/python ./build
~~~
You should be able to run these scripts with any versions of Python since 2.6 (I think), definitely 2.7. They also work fine with Python 3.

**Comment by jdtournier** [comment]
@pmccolganni: any progress on this issue? Please close the issue if you've managed to fix the problem - and let us know whether there's anything we need to fix on our end...

**Comment by pmccolganni** [comment]
Thanks Donald, sorry I didn't get back to you sooner, I think it's a c++ complied problem that we are looking into.

I will close the issue.

Best wishes,

Peter

On 10 Dec 2015, at 21:18, J-Donald Tournier <notifications@github.com<mailto:notifications@github.com>> wrote:


@pmccolganni<https://github.com/pmccolganni>: any progress on this issue? Please close the issue if you've managed to fix the problem - and let us know whether there's anything we need to fix on our end...

-

**Comment by jdtournier** [comment]
Surprised to hear that would be a compiler issue - seems very Python-related to me... Feel free to close or post more information if you want to discuss.

**Comment by pmccolganni** [comment]
Initially it was a python problem which we managed to solve however we still had difficulty installing as our c++ complier is not up to date.

**Comment by mgstauffer** [comment]
I get the same error with python 2.6.6 (Centos 6.6).
Using Python 2.7.9 works. HTH.
