### ISSUE TITLE
Scripts: Renaming?

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#419]
Most of my scripts have kept their names from when I first wrote them for my own use, without really considering how they've evolved since then or how they fit in with the rest of the package. Initially I kind of liked the idea that the scripts used lots of underscores whereas none of the binaries have them any more; though now I'm not so convinced. Some of the names are also quite cumbersome, or either too specific or non-specific. So gauging people's thoughts on a batch rename before release.

These are what I've come up with, very much inviting other suggestions.

`act_anat_prepare_fsl -> 5ttgen_fsl`  (5ttgen binary is deprecated)
`act_anat_prepare_freesurfer -> 5ttgen_freesurfer`
`distcorr -> dwiprep_norpe`
`dwibiascorrect -> dwibiascorr` or leave
`fs_parc_replace_sgm_first -> labelsgmfix`
`revpe_distcorr -> dwiprep_rpepair`
`revpe_dwicombine -> dwiprep_allrpe`

**Comment by dchristiaens** [comment]
Personally, I would avoid all underscores, to make the syntax as consistent as possible with the commands. To the average user, it doesn't matter is something is implemented as a command or a script. I would hence suggest using options instead, e.g., `5ttgen -fsl` and `5ttgen -freesurfer`, and `dwiprep -rpe no`, `dwiprep -rpe pair` and `dwiprep -rpe all`. You might even choose a sensible default for these.

**Comment by jdtournier** [comment]
:+1: for @dchristiaens's suggestion. It does mean that scripts become a little bit more complex to handle all the branching, but at the same time I'm guessing it'll probably avoid a lot of duplication. The `dwiprep` scripts for example would probably involve almost identical steps for the most part, so merging them into one and handling the various options would probably make a lot of sense - not to mention that it makes for a much cleaner interface...

**Comment by dchristiaens** [comment]
On second thought, the name `dwiprep` might be a bit too general, given there's also `dwibiascorr` and `dwinormalise`. To avoid confusion, maybe `dwidistcorr` or `dwieddycorr` is more clear, don't you think?

**Comment by jdtournier** [comment]
I see what you mean. Nonetheless, I'd still be happy with `dwiprep`, since 99% of the time that's what new users will be looking for. `dwinormalise` and `dwibiascorr` are sufficiently specific to avoid confusion. Just my 2 cents...

**Comment by dchristiaens** [comment]
Fine with me. Let's hear what @Lestropie and the others think.

**Comment by Lestropie** [comment]
It would be difficult, though not impossible, to have all of the `dwiprep_*` scripts encapsulated as one. You'd either need to have separate `-rpe` options (as some require additional images while others do not), or you would need to require that the user manually concatenate all input images in the correct order beforehand (which is one more way for things to go wrong, and means you couldn't feed in the acquired DICOMS directly). It would also make the help page a lot more convoluted. Although there's a decent amount of duplicated _operations_ between the scripts, the implementations differ enough that it'd probably be more trouble to combine them than it's worth (e.g. git classified my modifications of `distcorr` as a 'rewrite', and that was _after_ Daan had stripped the reversed phase-encoding aspects).

I guess in that way the underscore serves as a 'do this operation, based on this set of inputs / configuration' argument branch, which is more amenable to future possibilities (e.g. dealing with 4 phase-encode directions) and will keep help pages cleaner. Also, I appreciate that both `5ttgen` scripts require just a single input; again, that may not be the case in the future, I feel like the underscore approach is a little more flexible.

For reference: `dwiprep_norpe` takes just a DWI series; `dwiprep_rpepair` takes an additional pair of input 3D volumes; `dwiprep_rpeall` takes _two_ DWI series.

Another option I've been considering is `dwipreproc` rather than `dwiprep`: 'pre-process' rather than 'prepare'; also reduces confusion with DTIprep.

**Comment by dchristiaens** [comment]
I appreciate the complexity of the different inputs, but many of these issues could be alleviated by using options rather than the fixed order of arguments. For example:
```
dwiprep -peaxis AP -norpe in.mif out.mif
dwiprep -peaxis AP -rpepair ap.mif pa.mif in.mif out.mif
dwiprep -peaxis AP -rpeall in2.mif in1.mif out.mif
```
The `-norpe`, `-rpepair`, and `-rpeall` options would be mutually exclusive and take 0, 2, and 1 option arguments respectively. Actually, `-norpe` is not even needed if we make it the default. The `-peaxis` option could default to AP, I guess.

**Comment by thijsdhollander** [comment]
I think it's indeed a matter of providing mutually exclusive options as much as possible; the nice thing is that it also makes the essentially blocks of code of the scripts mutually exclusive (if nicely written as such).  I feel an important part of the value of the scripts is that they provide easy access to even less technically inclined users (read: no C++) to see what is essentially happening; and even more importantly: a means for them to make specific changes if their weird scenario demands for it.  The most easy way to provide all of this, would indeed probably just be sticking with the "underscore-approach", but when providing those mutually exclusive options (to a single command) as an alternative, you can mostly keep all those benefits while still providing a cleaner and more compact interface.

As to defaults: I wouldn't go too far with that.  Sometimes it's better to "force" a user to see they have an important choice to make, rather than to risk hiding that choice for them.  This of course has to be evaluated for individual cases, but overall I'd take a careful approach there.  There is a good reason after all these scripts originally ended up being separate ones...

**Comment by Lestropie** [comment]
This has now all been done in `updated_syntax` - for my scripts, at least. People are more than welcome to try renaming other scripts / porting to the script API.

**Comment by Lestropie** [comment]
Hopefully everybody's content with how this turned out.
