### ISSUE TITLE
overwrite same image with mrconvert results in an empty image

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#433]
(the same for master and updated syntax branch)

`mrconvert -axes 0,1,2 image.mif image.mif -datatype float32 -force && mrview image.mif`

produces an empty image (all zero).

`mrconvert -axes 0,1,2 image.mif tmp.mif -datatype float32  && mrview tmp.mif`

works.

## before in-place mrconvert:

`mrinfo image.mif`

~~~~
  Format:            MRtrix
  Dimensions:        96 x 96 x 60 x 1
  Voxel size:        2.5 x 2.5 x 2.5 x 1
  Data type:         32 bit float (little endian)
  Data strides:      [ 1 3 4 2 ]
  Intensity scaling: offset = 0, multiplier = 1
~~~~

## after in-place conversion:

~~~~
  Format:            MRtrix
  Dimensions:        96 x 96 x 60
  Voxel size:        2.5 x 2.5 x 2.5
  Data type:         32 bit float (little endian)
  Data strides:      [ 1 2 3 ]
  Intensity scaling: offset = 0, multiplier = 1
 ~~~~

`mrstats image.mif`
~~~~
        channel         mean       median    std. dev.          min          max       count
         [ 0 ]             0            0            0            0            0       552960
~~~~

**Comment by jdtournier** [comment]
This is expected given how the backend handles images. The issue here is that MRtrix tries hard _not_ to explicitly load data to RAM if it can avoid it - it'll use memory-mapping when it can. With mif format, it almost always can, unless the app requests direct IO access and the datatype / strides don't match. The output image on the other hand is created immediately (i.e. in the `Image<>::create()` call), even if the data won't be written back until the destructor is invoked. One of the first things this call will do is create the output file, overwriting the original if `-force` is supplied - so that would immediately fill the _input_ image with zeros, before the copy has even started. What happens in practice given the memory-mapping depends on the kernel's policies as to how it handles an active memory mapping when the backing file has just been replaced - given your results, it looks like you get a mapping into the newly created file, rather than the kernel maintaining the original input file while it's opened by the application. In any event, it's safe to assume that the result will not be ideal...

While it would theoretically be possible to handle this, it would require one of two things: 

- avoid memory-mapping altogether, which would be a shame and potentially a serious performance regression in many use cases, since this would force an explicit load-to-RAM for the entire image every time;
- make sure the write-back for output images truly only happens when the destructor is invoked - i.e. do not try to create the output file until then. This again would introduce issues, since it wouldn't be possible for the app to abort early before a lengthy processing run when the output file can't be created due to e.g. permissions or lack of storage. 

So I don't think I want to be able to support this case - the simplest may be to try to detect such cases and abort with a helpful error message (which might actually be harder than it looks...), or just document that limitation on the wiki (much simpler fix, IMO :wink:).

**Comment by maxpietsch** [comment]
After some discussion we decided that the current back-end does not provide an easy way to detect all situations in which this is an issue and that it is not worth the effort changing it for now. So, a warning in the command line argument -force description it is.

**Comment by thijsdhollander** [comment]
Makes sense.  I can also see this happening (haven't tested though) for images supplied as arguments to certain options of certain commands.  And stuff segfaulting if the forcefully created output has a different size/strides of image grid compared to the supplied input, et...  So it's almost impossible to, in general, provide more specific information than "unexpected behaviour".
