### ISSUE TITLE
connectome2tck: segfault on the updated_syntax branch

### ISSUE THREAD

**Issue by chunhungyeh** [MRtrix3/mrtrix3#443]
Got segmentation fault running `connectome2tck` on the `updated_syntax` branch. The problem seems to be caused by adding `Tractography::TrackWeightsInOption` to `TrackWeightsOptions` in `connectome2tck.cpp`?

**Comment by Lestropie** [comment]
Reading up & testing a little, looks like this is the _static initialization order fiasco_ rearing its ugly head. In which case it's possible that there may be other cases lying around that haven't cropped up yet.

To me the simplest solution is: for any `cmd/` file that constructs an `OptionGroup`, which itself depends on the prior initialization of an `Option` or `OptionGroup` in some header file, the constructor should appear in the `usage()` function rather than as a global variable. But then, maybe all such definitions should be moved to the `usage()` function: there's no need for them to hang around for the entire runtime since they're being copy-constructed into `App::OPTIONS`, and it might prevent this problem from cropping up again. Any thoughts / objections? @jdtournier Looking at you.

**Comment by jdtournier** [comment]
Sounds totally sensible to me. You definitely can't rely on the order of initialisation for static variables, so you want to stick them in some function where you do have control over the order - `usage()` is clearly the most sensible place. Go for it.

**Comment by Lestropie** [comment]
The main question is whether _all_ OptionGroup definitions should go into `usage()`, even ones that don't depend on other statics. It'd reduce the chance of the problem occurring again (as people would compare to existing cmd/ files to decide where to put them in new commands), but might not look as neat.

**Comment by jdtournier** [comment]
Sure, we can do that if you want - it might as you say reduce the chances of these kinds of issues cropping up. Not sure how you'd enforce it thought - maybe the only thing we can do is document this 'policy' in the dev doc at the appropriate place, and hope developers stick to it. 

In terms of looking messy: in practice it just boils down to an extra set of brackets at the end of the option group, where it's used in the `usage()` call - really no difference at all. And the change to the declaration/definition of the OptionGroup itself is really minor as well. I already use that for a couple of options,  an added bonus is you can pass arguments to modify the OptionGroup if needed. I think the grad_import_options already uses that to disable one of the options in commands where it happens not to make sense...

**Comment by Lestropie** [comment]
Hmm. So, if the `const OptionGroup` definitions are moved into `usage()`, it makes sense for any `const char* []` definitions for `.type_choice()` arguments to move there as well. But that won't work, because the argument stores a pointer to the string list, which would then get freed at the end of `usage()`. So either these arguments need copy-construction of the strings, or it's going to be confusing as to why some const definitions are in the function and some aren't.

I think I might just fix this one case; it's a slightly weird use, and looks like a one-off.

**Comment by jdtournier** [comment]
I'm not sure why you want to move these `const char *` definitions into `usage()`, but if this to reduce runtime memory usage, don't bother, it can't make any difference. The data for the strings has to be stored somewhere in the executable, it makes no difference whether it's stored at global or function scope...

**Comment by Lestropie** [comment]
No no, it would just be strange if all `OptionGroup` definitions had to be within `usage()` to prevent this error, but all `const char*` definitions had to be outside of it to prevent an entirely similar error..

**Comment by jdtournier** [comment]
Ah, OK. You could just declare the array as `static`, then. That should guarantee its lifetime extends beyond the function call.

**Comment by Lestropie** [comment]
True. But it wasn't worth going through changing every cmd/ file just to achieve consistency with the one command that caused this problem, and being detrimental to code readability in the process.

**Comment by jdtournier** [comment]
Totally agree. Just thought I'd suggest the option in case you were hellbent on moving everything within function scope...
