### ISSUE TITLE
connection metrics

### ISSUE THREAD

**Issue by pmccolganni** [MRtrix3/mrtrix3#445]
Dear MRtrix3 team,

I was wondering what the metric options represent (and how their calculated) in tck2connectome and which would be the best metric to use. Is there any information available on this?

Thanks for your help.

Peter

**Comment by draffelt** [comment]
Hi Peter,
Hopefully @Lestropie (Rob) can provide some insight into these once he is back from vacation. We are currently revamping our user documentation for the new website and this is something we might want to explain in more detail.

If possible, can you please ask the question again on our [community forum](http://community.mrtrix.org/), since we mainly use the Github issue tracker to flag bugs and future developments. Posting it again on the forum will enable other users to see and benefit from the subsequent discussion, and it's more easily searchable in the future. 

Cheers!
Dave
