### ISSUE TITLE
mrmath product was doing a sum

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#448]
What the title says.  I quickly patched it up in f731f6711a88b4bc0d8b551f06d2e7c0f22c49ca .  Just highlighting it over here; is everyone happy with the actual behaviour of it?  One slightly weird case I could think of, is if every value fails `isfinite`, the result will be 1.  Feel free to change that if it would be considered not the correct/wanted behaviour for that scenario.

**Comment by jdtournier** [comment]
Well that's not great... How long has this been the case? I'm assuming this isn't being tested properly on TravisCI then? I hope it wasn't one of my sleep-deprived screwups... 

Otherwise, I'm thinking it might be worth having a `-finite_only` option or something to allow the user to decide how to treat inf and nan. In which case getting a 1 might not be so bad? Otherwise it is indeed quite tricky to catch that case efficiently...

**Comment by jdtournier** [comment]
Hehe... This wasn't my screwup - I feel better now... :+1:

**Comment by jdtournier** [comment]
Just had a thought about this issue when all volumes fail `isfinite()`. How about this approach: 
~~~
out = NaN;
for (auto in : incoming)
  if (isfinite (in))
    out = isfinite (out) ? out * in : in;
~~~

That should leave the value set to NaN if there genuinely weren't any finite values for all volumes for that voxel, and do the expected product otherwise. What do you reckon?

**Comment by thijsdhollander** [comment]
That probably makes the most sense indeed; better to highlight the meaninglessness of that case by a NaN, rather than a 1.

**Comment by thijsdhollander** [comment]
I'll quickly give it a fix.

**Comment by thijsdhollander** [comment]
Fixed it for now (as suggested above).  As mentioned in #509 , it might be worthwhile to check some of the other operators as well, as to what they yield for these special cases.
