### ISSUE TITLE
mrview: multi-image view mode

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#453]
I'm not yet convinced this is worth the effort or exactly how it would work so bare with me.

We have had multiple requests to be able to sync mrview across multiple instances. While this is possible, it is a fair amount of work to get right and support all platforms. 

Instead, could we have a mode that provides a user definable grid (like lightbox), which renders each image loaded in a separate grid element.  Obviously lock to axis would be turned off.

Currently in lightbox mode the cross-hair (focus) is set for only a single grid element only (which also defines the voxel information). We could still have this in multi-image mode, however also render additional cross-hairs (in a different colour) on top of all other images (grid elements). This would allow a user to click, and see the corresponding location in other images. 

One use case would be to check image registration. 

The main issue is how to deal with or render overlays (tracks, fixels, odfs) with multiple images.

**Comment by jdtournier** [comment]
Not sure about this - it sounds like a _lot_ more work that syncing across instances. Problem is that having two main images breaks a large chunk of the core API. The bulk of the MRView backend is really designed to display one image, any additional images should be handled by the relevant tools. I'd expect this would require changes in lots of unexpected places.

Syncing across instances should actually be that hard. We already manipulate the display programmatically in the screen capture tool, and it's not difficult. The interprocess communication is what sounds a lot harder, but Qt comes bundled with a full interprocess signal & slot mechanism, supported on all platforms. The main remaining difficulty is how do we manage the synchronisation from a UI point of view. I think we've already discussed this in #206...?

**Comment by draffelt** [comment]
Thought you might say this. It just popped up during a discussion of the 4d light box mode. I also forgot about the qt stuff. Let's close it for now.

**Comment by rtabbara** [comment]
Wait, let's not give up just yet...

Why can't we have *one* main image, but allow for multiple-image rendering? In other words, we would store the "context" of an image (i.e. image+tool overlays) and then allow for users to toggle to perform a context switch (e.g. via a shortcut)

So visually you would see multiple images, but only the main image's loaded overlays would be reflected in the tools as well as annotations/colourmaps etc.

To me, the `Window` class already has the beginnings of this setup given that a user can toggle between previous and next images. But we would be rejigging it so that a `Window` would maintain a list of `Modes` that correspond to each image and adjust the viewports accordingly so that a user could visualise them all concurrently.

And I think this would nicely handle the issues raised in #206 &mdash; namely how a user would specify what they wanted synchronised across multiple images. With this setup where everything is in the same viewer, we could simply have an additional tool GUI listing the available options.

**Comment by jdtournier** [comment]
Whoa, multiple modes... that sounds even heavier. If I understand right, you'd be talking about setting up another viewport next to the main one, to display the secondary image. I think if that's what we wanted to do, it would be _much_ easier to have a tool which basically takes the overlay tool, but displays its image to the side of the main image rather than on top of it - along with the corresponding crosshairs... Maybe we could even have a toggle on the overlay tool to do this (although it wouldn't be particularly obvious there). That would be a far simpler solution if we really wanted to go that way.

But realistically, it doesn't handle the issues in #206 any differently - we'd still need a UI listing the sync options, regardless of whether these are applied within the same instance or across instances. What I do think it does simplify is the issue of different window sizes: if both images are displayed side by side in the same viewport, they will be sized appropriately. That would be difficult to achieve on a different instance with a different window size, since everything is scaled to the FoV, which is proportional to the window size. But these days with snapping windows managers, I don't think this is a particularly problematic issue either...

On the other hand, it very much depends on what users want this for. If it's to check your registrations, personally I think the overlay tool is a much better fit for the job - or just switching between the images. If you want to display different types of images with different contrasts side by side, then this might start to make sense. But if you wanted to have for example one instance with the ODF overlay, while also displaying the tracts on top of the anatomical in a different viewport, and also have the T2 displayed with lesion ROIs overlaid alongside all of that... then this would only be possible with the multiple synchronised instances idea - that's the only option so far that has full versatility as to what is displayed where. So assuming we want to do anything about this, I vote for the multiple synchronised instances option...

**Comment by thijsdhollander** [comment]
>  If you want to display different types of images with different contrasts side by side, then this might start to make sense.

I think it was *mostly* this we were envisioning.

> But if you wanted to have for example one instance with the ODF overlay, while also displaying the tracts on top of the anatomical in a different viewport, and also have the T2 displayed with lesion ROIs overlaid alongside all of that...

We (I) weren't really thinking *that* far, but it'd of course be a nice bonus (as long as it remains user friendly).  In that case...

> I vote for the multiple synchronised instances option...

...this makes sense.

But, it'd become much more unwieldy (for a user) if all he wanted to do was -let's say- look at 4 or 5 different contrasts (and not care about different ODF/track/other overlay stuff), because he'd have an equal amount of full blown user interfaces open in separate windows (I agree though that the snapping functionality of most OSes may help a bit here).

So yeah, I guess it does still depend on what use case we value the most here...?

**Comment by thijsdhollander** [comment]
Small addition to this one maybe:

> If it's to check your registrations, personally I think the overlay tool is a much better fit for the job - or just switching between the images.

That's OK for 2 images, but another aspect that came up during the discussions was template building; i.e. where this might be ~ 20 images or so.  Although in both registration/template cases, all outcomes would typically be regridded to the same image space, so this could actually fit (a bit) in the 4D lightbox idea proposed in issue #451 ...

**Comment by jdtournier** [comment]
I think we'll really need to make a list of the most likely use cases, and see whether any of them really favour a particular solution over another.  Personally, I'm not convinced about the registration check use case. I can see that displaying 20 registered brains side by side sounds appealing, but realistically, would that really help you assess the quality of the registration? Clearly, really bad registrations would be obvious, but they would be equally obvious on a quick flick through the images. I'd expect subtle misregistrations would be much harder to spot using this approach, when they would be much more obvious just flicking through the images. Not that I have any experience with this - we don't have the capability - but just trying to picture what it would look like, spotting a minor misplacement of the temporal lobe of patient X in the second row of this 20 subject display seems like quite a tall order for your average visual system...

Which is why I think the more _useful_ use case is what I'd described earlier: displaying different types of images side by side, potentially with different types of information overlaid on top of them. To me, this argues for synchronisation between separate instances. I also think it's actually the simplest and cleanest to implement... If anyone else can think of other legitimation use cases, please let us know!
