### ISSUE TITLE
updated syntax mysys2 shared libraries error

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#461]
after a clean build of updated syntax in my virtualbox windows 7 following the instructions on the [wiki](https://github.com/MRtrix3/mrtrix3/wiki/Installing-on-Windows-using-MSYS2) I get the error 
~~~~
C:/msys64/home/User/mrtrix3/release/bin/mrconvert.exe: error while loading shared libraries: mrtrix-0.3.13.dll: cannot open shared object file: No such file or directory
~~~~
when trying to execute mrinfo, mrconvert, ...

[configure.log](https://github.com/MRtrix3/mrtrix3/files/170372/bug.txt)

**Comment by jdtournier** [comment]
That's probably a simple matter of either adding the `lib/` folder to the Windows PATH, or moving/copying `mrtrix-0.3.13.dll` from `lib/` to `bin/`. Maybe we should update the instructions if that wasn't clear? Or better still, change the build script so that the location of the DLL is the `bin/` folder...?

**Comment by Lestropie** [comment]
Windows needs the shared DLL to be in the PATH. You need to add `release/lib/` to the path rather than `lib/`. I think just update the instructions.

**Comment by Lestropie** [comment]
Pushed changes for this to the docs.

**Comment by maxpietsch** [comment]
Thanks, works. (Can't see the changes in the wiki yet.)
