### ISSUE TITLE
MRview: add voxel navigation to view tool

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#5]

**Comment by rtabbara** [comment]
I like seeing the milestone green bar fill up so I thought I would try to knock this one off as well. Please take a quick look to see if it's ok.

**Comment by jdtournier** [comment]
@rtabbara : almost... Only slight snag was that you'd passed the same Point as both source and destination arguments in the same `scanner2voxel()` call, and since they're passed by reference, the source ended up betting modified too. This made manual modifications to the voxel position end up somewhere other than what you'd typed in... 

Fixed in 64504e7

> I like seeing the milestone green bar fill up

Yes, there's something most satisfying about that...

**Comment by jdtournier** [comment]
By the way, while you're at it, it would be great to extend this with a 'volume' section that would allow setting the volume (i.e. any position along axes 3 and above) - something I'd mentioned in passing in issue #206. This would be slightly trickier, as it would need to dynamically adjust to the image displayed, so that switching from a 5D image to a 3D image doesn't crash the viewer...

No great rush, but it's another one that's been on the todo list for a while...

**Comment by rtabbara** [comment]
@jdtournier Volume section in View tool has been added in c1be32a0cf . Please check it out.

**Comment by jdtournier** [comment]
Just had a look - works fine. Happy with that.
Thanks!
