### ISSUE TITLE
full brain tractography possible but can't seed from a point? (ERROR numbers of volumes does not match...)

### ISSUE THREAD

**Issue by jhmeurgey** [MRtrix3/mrtrix3#508]
I've just finished generating a mask, response text file and an FOD, and am able to perform full brain tractography but I can't seem to seed (seed_sphere) from a specific point 

When I run the command 
`tckgen.exe final_dwi.mif -seed_sphere -11.5,41,29,3 -initdir 0,1,0 cingulum_L.tck`
I get 
`tckgen: [ERROR] number of volumes in input data does not match that expected for a SH dataset`

Any help?

**Comment by jdtournier** [comment]
The source image you're providing corresponds to the raw DWI - this should be the CSD output. Are you sure you were able to track full-brain _from this same image_ before...?

**Comment by thijsdhollander** [comment]
What I suspect is that tracking from this image worked before; but because it's the DWI image, it'll perform tensor tracking.  The specified command (with the `-seed_sphere`), does add an `-initdir` as well; but since the tensor tracking algorithm is deterministic, it's super fussy about what direction is valid for a specific position (just the exact principal eigenvector of the tensor at that location), it's not able to match that with the `-initdir` requirement.

@jhmeurgey : you need to supply the FOD file to the command.  Then, it'll automatically resort to a probabilistic FOD tractography algorithm (iFOD2 being the default in that case).  Since that allows to sample the FOD for a range of directions, it'll be much more likely to match that initial direction you requested.

**Comment by jhmeurgey** [comment]
Thank you, I just realized when I was looking through the full brain
tractography commands that I was actually using the FOD.mif file, which I
unthinkingly omitted for the seeded tractography. My bad.

**Comment by jdtournier** [comment]
Good to hear - I'll close this off.

For the record: @jhmeurgey, you'll probably want to ask on the [support forum](http://community.mrtrix.org) rather than the issue tracker the next time... :wink:

@thijsdhollander, pretty sure `tckgen` wouldn't just choose to do tensor tracking without the `-algo` option... And besides, the `-initdir` option is a lot more relaxed than that: for tensor tracking, it'll just pick whichever direction isn't going against the direction specified (at least, it did the last time I checked...).

**Comment by thijsdhollander** [comment]
Aha, yes; it still doesn't select the tensor tracking by default in that case.  I wasn't aware of the `-initdir` behaviour though, but now I see what it's rather intended for.
