### ISSUE TITLE
Overlay vector plots on images with different resolution and orientation

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#52]
The current vector plot only renders when snap-to-axes is on. This is because off axis rendering of fixels is not possible due to lack of interpolation.

If a vector/fixel image is overlaid on an image of different resolution or orientation, we currently get undesired results (since vector/fixel rendering is indexed by slice). 

Do we need to support the ability to overlay vector plots on other images?  Rendering on an image of different resolution is easy, however when the image has a different grid orientation it is problematic. 

One option would be to somehow have a snap-to-vector-image-grid option and interpolate the image underneath, however this might be a little unintuitive to use. 

I guess if people really want to overlay vectors on another image, then they could just regrid that image at the vector image resolution.

Any thoughts?

**Comment by rtabbara** [comment]
Proposed fix for this is in branch <code>vec_plot_interp</code>. Please check it out. 

As suggested, nearest-neighbour interpolation is being used when rendering off-axis. When cropping to a slice, rendering no longer relies on the current axis/slice index, meaning that we now handle the case when there is a mismatch between the fixel and underlying image resolutions.

**Comment by thijsdhollander** [comment]
Okay, at first sight, it looks good (the fact that it's nearest neighbour is actually much less noticeable than I thought!).  Testing this did bring up 2 very different (interesting) findings though.  My testing scenario was an anatomical image (1mm isotropic) as main image, and a vector plot (2.5mm isotropic) with a differently orientated grid.  

- About the vector plot itself: everything seems all right at first sight, but things do "change" when simply panning the image (using middle mouse button)... which seems a bit odd?  Also, depending on the orientation of the grids in relation to each other, I sometimes see "gaps" in the plot (i.e. single vectors missing out in certain locations).  It's quite hard to explain in a way that makes sense; it's probably easier to just show it at work. :-)

- Because I tried to make sense of the above, I thought I'd simply overlay an ODF image as well, using the ODF display tool.  To make things comparable, I switched off the "interpolation" option, while keeping the "lock to grid" on, and the "use main grid" off.  Intuitively, I thought this would result in the same overlay grid locations as the new vector plot ones... but it didn't.  The issue not so much being with the vector plot, but more with the ODF display... I think.  The ODF overlay actually showed things on a grid that was *aligned* with the anatomical image, but just using the lower 2.5mm resolution of the diffusion data.  I never noticed this before... but does this make sense?  I thought not using the "main grid", it would use the ODF image's grid (*including its orientation*), and then subsequently using interpolation (or nearest, if switched off) to get samples in the main image's plane.

**Comment by jdtournier** [comment]
Ah, yes, the ODF tool... Not hugely surprised you're getting a touch confused with its implementation, but I'll explain the rationale behind all of these decisions, it might make things clearer... 

First though: the fact that the vectors displayed change when panning is due to the way the grid is 'anchored' (the same issue is also present with the ODF tool, was discussed extensively in #194). Basically, the approach is to take the _target_ point (which is the centre of the image display - in orthoview, it's the point at the centre of each pane), project it to the same depth as the _focus_ point (the latter corresponding to the crosshairs, which is not in general the same as the target point) since the depth of the focus determines which slice gets rendered, then find the nearest voxel centre in the image grid you're interested in, and use that as the 'anchor' for your grid. Basically, that point becomes one of your grid points, and all the others grid points are then determined by appropriate x & y direction increments (in screen coordinates). So as you pan around the image, if the screen axes aren't perfectly aligned with the overlay grid, the location of the grid anchor can change as the target moves with respect to the overlay grid. That's basically what you're seeing.

As to gaps in the overlay, I'm guessing that'll be down to having a threshold on how far from the slice the overlaid grid centre is allowed to be. Not sure about that, haven't looked at the code to check...

Back to the rationale: the problem of identifying a regular grid onto which to overlay the glyphs when the grid plane is not aligned with the overlay axes is actually far from trivial. In general, the projection of your overlay axes onto the slice displayed will not be orthogonal when off-axis. Also, a small rotation may cause a switch from one pair of axes to another, for example if the grid currently uses the projection of the x-y plane, and the slice plane is rotated, the x-z plane might become a closer match to the slice plane, which would cause the grid to suddenly change. So I don't see how we can use the overlay's axes in a well-behaved way when rendering off axis.

The approach taken for the ODF tool is to ensure that the behaviour matches expectations when it can. It will reduce to locking to voxel centres of the overlay when the overlay's axes match the screen's axes - this is guaranteed by locking the grid anchor to the nearest voxel centre (when 'lock to grid' is ticked), and using the screen's axes to generate the grid around that anchor. As soon as there is an in-plane rotation, I agree that we _could_ use the overlay's axes to guarantee that the glyphs are still rendered at voxel centres. The problem is that as soon as the rotation goes out of plane, there is no way to provide that guarantee any more. If we allowed the grid to follow the overlay axes when they remain in-plane, and switch to a different grid-generating approach as soon as they move out of plane, we'd end up with a sudden change in the location of the rendered glyphs. 

There is also the option of not locking to the overlay grid, at which point the grid is generated around the target point as-is. This looks a bit weird when panning and rotating, since the glyphs no longer move on-screen, they gradually 'morph' as the underlying overlay changes... But it has the advantage that the location the glyphs are interpolated from are precisely at the same _depth_ as the slice displayed - whereas the 'lock to grid' will lock to the depth of the nearest voxel centre. So again, there are pro's & con's...

So as you can see, this is a really hard problem to get 'right' - personally I don't think we'll be able to come up with a solution that works intuitively and without funny 'glitches' 100% of the time, it's just not possible. What I tried to achieve was at least something that was relatively predictable (minimal sudden changes in the grid, or at least in its orientation), and _by default_ behaved in a totally intuitive way in the right conditions (overlay glyphs on image with identical orientation, main view locked to axis), which I'm hoping is how _most_ people will use the tool _most_ of the time...

The situation is a bit more complicated for the vector tool since interpolation is ill-defined in that domain - which is why we're resorting to nearest-neighbour. Again, the hope is that this will behave as expected most of the time - as long as users don't start tilting and/or overlaying on differently oriented images. And when these conditions are not met, that it at least behaves sensibly enough - hopefully the reason behind the 'funny' behaviour will be apparent to users if they think about it (although I'm not sure about that, given that you've clearly found this confusing...). Maybe we should find a way to pop up a disclaimer, detailing these issues and at least mentioning what conditions are necessary for these tools to behave 'as expected'... Not sure how to do this without it being intrusive though, maybe a wiki entry is the best way to tackle it?

**Comment by jdtournier** [comment]
@rtabbara : the issue with some fixels not displaying when rotating is most likely due to your `voxel_to_indices_map` taking a `Point<float>` as its index - it should really be a `Point<int>` to avoid rounding errors. Bear in mind the `std::round()` call returns a float, but is probably still prone to some slight rounding discrepancies depending on the input. For instance, I wouldn't be surprised if it returned `0` or `-0` depending on exactly which side of zero you were rounding from, and these would not provide a binary match if used as the index to the map...

**Comment by thijsdhollander** [comment]
Ok, big thanks for the in-depth explanation!  The way I now ended up allowing my brain to deal with this logic, is splitting the whole thing in 2 sequential problems/questions that demand a (separate) solution/answer:

1) Given the different orientation (in full 3D) of an overlay, determine a grid -or in general even just positions in the plane currently shown- to render whatever you're overlaying (be it ODFs, vectors/fixels, ...).
2) Assuming an answer/output to (1), determine how to render at those positions.  This is basically the interpolation question.

For (2), we're indeed limited to a nearest neighbour logic in the case of vectors/fixels; whereas linear (or anything else) is an option for the ODFs.

For (1), however, it's probably best (?) to establish a single unified answer amongst different overlays, such as the ODF and vector plot tools.  The most obvious use case where this matters is when overlaying both at the same time (e.g. comparing some freshly segmented fixels to the ODFs they originated from).  In this case, a reasonably insightful user would then also switch off the interpolation option on the ODF tool's end.  At first I found it more difficult to (mentally) deal with the current ODF tool's logic for (1), but the way you explained it now allowed me to see how it starts to matter more in the stranger cases where the orientation of the plane is really different from the overlay's grid.  Forcing the current vector tool in those scenarios indeed yields a bit of a funky outcome at times.  Here's just a random example where I rotated stuff way off axis:

![vecs](https://cloud.githubusercontent.com/assets/11952694/8198223/ba0f00ae-14e6-11e5-8c2f-31db52395e40.png)
(it's just a simple FEV field, coloured by orientation, scaled by FA)

What ends up being possibly quite confusing here is the middle and middle-bottom regions.  Where the original vector field was quite continuous, 2 continua start to "interdigitate" over a rather large area.  This could easily change an observer's appreciation of the global qualities/properties of the vector field.  But what ends up being extra confusing is that this actual pattern changes quite drastically while panning...  All of this to conclude that I indeed see more merit now in the ODF tool's approach to (1). :-)

**Comment by jdtournier** [comment]
@thijsdhollander: glad I've got your seal of approval... :wink:

@rtabbara: I didn't realise the fixels kept their location... We need to use the grid location itself, for the reasons Thijs highlighted - even if it could be considered misleading with the nearest-neighbour interpolation. I think it's important that the glyphs remain on a regular grid on the display, and that this grid matches between tools as much as is practical... How difficult would that be given your current implementation?

**Comment by draffelt** [comment]
Rami is already onto it

**Comment by rtabbara** [comment]
@jdtournier Yep, talked to @draffelt and @thijsdhollander today about this issue and that's the game plan. Shouldn't be too difficult to refactor.

Don't want to get too side-tracked, but @thijsdhollander also made me conscious of the impact of this change in the instance where we have multiple projections (i.e. ortho or light-box view).

Off-axis rendering is currently handled by maintaining another index buffer that point to the *projected* voxel centres. This index buffer is lazily updated when an orientation, pan etc. event is triggered. However, the problem is that this isn't nicely setup to render into multiple projections concurrently, because we would have to recreate this index buffer every draw call for each of the distinct projections. We could certainly do that as with the ODF tool &mdash; for the ortho view it shouldn't be too bad, however I am worried that there would be a considerable performance drop when using the light-box view.

If it's the case that the most common use-case of the vector tool is to overlay onto a single slice, then one possibility is to make use of <code>Mode::Base::get_current_projection</code> and only overlay on the current "in-focus" projection?

**Comment by jdtournier** [comment]
Glad to hear it. As to your question about the index buffer: first problem is going to be that the changes required will probably mean that you can't use an index buffer anymore - the positions will have to be updated to those of the grid rather than the original overlay voxel centres. It would probably be pretty messy to try to maintain an index buffer for the directions and a separate normal buffer for their rendered positions, so probably simplest just to write everything to a normal buffer.,, Although since you've already preloaded the fixels onto the GPU, it might be just as easy to keep using an index buffer - up to you. 

I appreciate your concerns regarding performance, but I don't think you need to worry about that at all. The amount of data we're talking about updating per draw call is relatively small, I doubt you'd notice much difference in performance - especially if we start rendering other features such as ODFs or streamlines at the same time. I don't see a problem with re-generating a fresh buffer per draw call, it won't add a great deal to the overall performance. This would also avoid any issues with using this tool in multi-pane display modes, And there is nothing unexpected about it being slower in lightbox mode, I wouldn't worry about it - it would be impossible to discern anything meaningful unless you zoom right in anyway, which would speed up the render again anyway. 

So in short, I think you can ditch the lazy update, it causes issues and probably doesn't have a huge impact on performance. We can always revisit if we find performance is unacceptable, but I don't think it'll be an issue. 

>If it's the case that the most common use-case of the vector tool is to overlay onto a single slice, then one possibility is to make use of Mode::Base::get_current_projection and only overlay on the current "in-focus" projection?

I'm not sure what you mean here, but I'm guessing you're suggesting rendering only on the pane that currently has focus when in a multi-pane mode (lightbox & orthoview)? I guess my comments above already deal with that, I would support the full render on all panes, but not worry about the performance at this stage - it's a low use case, and will probably only ever be used by people when they're preparing a figure or something (and even then, I'm not sure there'd be much use in that).

**Comment by rtabbara** [comment]
Ok, updated this in <code>vec_plot_interp</code> to be more in-line with the ODF tool. Please take a look. 

There's similarly the option to toggle grid locking, and hopefully overlaying corresponding ODF and Vector images should coincide.

As recommended, when cropping to slice, we no longer lazily update the buffer, but instead it is recreated each draw call to allow us to support rendering into multiple panes. 

There's also a few cosmetic changes with respect to the default line thickness as well as making it clear that the vector tool supports both sparse and standard vector images when opening a file.

**Comment by thijsdhollander** [comment]
Just gave it a thorough test, and I'm happy to announce I'm unable to break stuff this time. :smile:
If interpolation is switched off in the ODF overlay, things indeed behave exactly the same in the ODF overlay and Vector plot tools.  My fixel image was exactly matched with the ODFs at all times, even overlaid on a (different resolution) anatomical image, and rotating stuff through every possible orientation.  Performance is also great by the way: doing a lightbox with (only) the vector overlay, and even cranking up the number of individual slices shown in the lightbox grid, things still run fully interactively without any noticeable slowdown whatsoever!

(very) minor niggles:
- The "lock to grid" checkbox is initially on, but the actual settings seems to be off.  To switch it on (only initially), I had to click the checkbox twice.  (basically switching it off and on again; the solution to all of life's computer problems :grin: )
- The (single slice) vector overlay also shows in the volume render.  This is actually not bad (I think it even behaves as expected over there).  I only noticed the ODF overlay doesn't do this.  So if anything, it could be a feature-to-be-added in the ODF overlay at some point or something...

**Comment by rtabbara** [comment]
@thijsdhollander Awesome, thanks for testing this out. The lock to grid issue should now be sorted.

**Comment by jdtournier** [comment]
Good to hear. 

@thijsdhollander: Not too sure about allowing display in the volume render, I can't see how that would be useful or even intuitive (?). The slice displayed would presumably be that which faces the user square-on, at the level of the focus - which would not match any of the clip planes. I'd find that a bit weird... But if you think it makes sense, why don't you give it a shot for the ODF tool as well, it would a simple matter of commenting out the bit where it checks what mode it's running in. Happy to reassess if people think it works...

**Comment by thijsdhollander** [comment]
Hmm, you're right indeed about the clip planes being a strange combination with the screen-plane rendering of other things.  I quite often use the volume render with a low alpha value (and possibly a lower threshold as well) to get a "cloudy" contextual hint of anatomy surrounding other things (overlays, tracks, ...), but in that case more often without the clip planes.  In that context, it still seemed to be a reasonable thing to do, but in other ones it's indeed less appropriate.  Maybe in the (far) future, a more sensible way to overlay ODFs/vectors in a volume render, is to actually make use of the clip planes present.  But that again opens up pandora's box of degrees of freedom in terms of defining how it could/would/should behave.  I'll let the idea linger somewhere in the back of my head for now... :smile: 

But in the mean time, it would in that case probably be more sensible to disable the vector plot in volume render mode (if the "crop to slice" option is on; it makes good sense otherwise of course).

**Comment by draffelt** [comment]
I've used this a recently and it all seems to work well.  I think this can be closed off.
