### ISSUE TITLE
mrview: Change tensor glyphs

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#593]
Rather than needing a second set of eyes to verify that my math is correct in generating tensor glyphs, I think it needs to be switched to setting the amplitude according to the ADC, rather than the mean particle displacement. Currently some can look very thin perpendicular to the principal eigenvector. From memory the main hurdle I had with this was deriving an expression for the normals.

If possible Alan would like a couple of new images generated for his ISMRM Siemens talk.

**Comment by jdtournier** [comment]
Is the idea to get 'proper' tensor ellipsoids...? I think all you need is to take the incoming unit vectors and multiply by the tensor - i.e. don't preserve the direction. The normals are a touch trickier to figure out, but not outrageously so. Do you want me to have a go at figuring them out? I've got a couple of hours to kill before boarding my flight...

**Comment by jdtournier** [comment]
OK, had a go with this. I reckon points on surface get transformed from uniform sphere to D*x, and normals are then inv(D)*x. See my musing below, if that helps...

![media-20160507](https://cloud.githubusercontent.com/assets/3221000/15093252/d87ef54c-1479-11e6-886a-e3c731b9fe33.jpg)

**Comment by thijsdhollander** [comment]
@Lestropie : not 100% sure what you are after...?

When you say: "setting the amplitude according to the ADC", it sounds (to me) like you're after the ADC "peanuts"?  That would just mean evaluating the tensor to ADC values: (x^T)Dx , which yields a scalar, and multiply this scalar with the unit vector to rescale it.

If you're after the proper *ellipsoids*, which half-axes that scale according to the eigenvalues (which, I reckon, is the most preferrable and universally accepted way of visualising tensors in the domain), then you'll indeed need Donald's equations.  But the challenge then also becomes that you'll get less angular samples for orientations along the "sides" of the tensor, because the vectors themselves also get transformed.  However, now that I think of it, that's actually a good thing: you'll need more samples along the orientations close to the peak, to nicely render the sharper curvature of the ellipsoid surface there. :-)

**Comment by thijsdhollander** [comment]
This page also has some of the equations for the latter one: http://mysite.du.edu/~jcalvert/phys/ellipso.htm

**Comment by Lestropie** [comment]
>  not 100% sure what you are after...?

Particularly for Alan's talk, looking for tensor glyphs that _don't_ look out-of-the-ordinary, and therefore potentially attract criticism that our tensor calculation / visualization is wrong. Long-term, probably just want something that's consistent with what everybody else is doing. But I'm having trouble figuring out what is 'standard' in this respect. Basser1994 plotted mean particle displacement, which I think is what I have right now; but they look very 'skinny' in high FA areas: the 'equator' is not actually the 'widest' point.

Donald's solution 'looks right' to me.
