### ISSUE TITLE
mrview: No QT icons on Windows

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#594]
Still haven't resolved this yet, need to dig further.

**Comment by jdtournier** [comment]
Check whether the SVG module is installed and available...

**Comment by Lestropie** [comment]
Not so simple unfortunately. All seems to be there. I even deleted and rebuilt mrview's icons.cpp file on the same machine.

**Comment by Lestropie** [comment]
OK, this one's officially got me stumped. Fresh installs using the up-to-date instructions, all the same packages: Icons on my Win7 desktop, no icons on my Win8.1 laptop :confused:. Config files are even identical between the two, excluding irrelevant stuff in `PATH`.

**Comment by Lestropie** [comment]
... and guess who uninstalled `msys2` forgetting about the uncommitted branch overhauling the mesh code with ~5k line changes :angry:

**Comment by jdtournier** [comment]
Ouch. That's not going to help the migraines...

**Comment by jdtournier** [comment]
Coming back to the original issue: have you tried copying the executables across systems, to check whether the problems are specific to the MRtrix3 executables? Could also try copying the whole msys2 folder over, just to check whether it's something with Qt or something...

**Comment by Lestropie** [comment]
> ... and guess who uninstalled msys2 forgetting about the uncommitted branch overhauling the mesh code with ~5k line changes :angry:

Got as far as running a deep filesystem file recovery and dumping git tree file contents... no avail :cry: 

> Coming back to the original issue: have you tried copying the executables across systems, to check whether the problems are specific to the MRtrix3 executables? Could also try copying the whole msys2 folder over, just to check whether it's something with Qt or something...

Either executable / dll running within the Win7 msys2 installation has icons. Either executable / dll running within the Win8.1 installation has no icons. There's clearly differences in the msys installation between the two: One has a `/bin/` directory, the other doesn't. So there must be an error in how Qt5 installs on Win8.1 (no separate svg package, it all comes bundled). Ideally I want to figure out how to fix it, users might not have a second Windows box with a different version in order to swap files.

**Comment by Lestropie** [comment]
In case anybody else encounters this: The only solution I've been able to find thus far is to downgrade from Qt5 to Qt4.

**Comment by jdtournier** [comment]
I should also add that the original issue related purely to an MSYS2 installation on Windows 8.1 - we don't see any such issues on Windows 10 or 11. Moreover, running a singularity container on WSL sounds like it's going to cause headaches - WSL2 relies on virtualisation (it's essentially a VM), and running another layer of virtualisation (singularity) within that is likely to come with significant drawbacks. For instance, I can't run mrview on WSL2 within my Windows 11 VM on Linux, because the nested virtualisation means certain features are unavailable within the VM (can't remember which now...). 

Note that this applies to displaying using the Wayland protocol with WSL2 on a Windows 11 host. Things might be different with the original WSL. And things might be different if you're using a 3rd party X11 solution (but then you don't get hardware acceleration). There's quite a few moving parts in this kind of situation... 

One final note: at the very least, for the icons to display correctly with Qt5, you'll need to have the Qt5 SVG module installed _in the singularity container itself_ (I expect it makes no difference if it's installed on the base WSL installation). Just in case that's what the problem is...

**Comment by Lestropie** [comment]
Worth noting that the original issue here is many years old; the system on which the problem was occurring is probably gone, and the patch solution at the time is no longer applicable. In addition your issue is using a Singularity container, where GUI handling has its own set of problems. So it might be better to close this issue and shift your issue to a new thread.

**Comment by jdtournier** [comment]
> So it might be better to close this issue and shift your issue to a new thread.

:+1:
