### ISSUE TITLE
MRinfo wrong extraction of bvecs/bvals

### ISSUE THREAD

**Issue by arnaudbore** [MRtrix3/mrtrix3#598]
I try to extract bvecs/bvals using two different ways:

1 - mrconvert from dicom file (mrconvert dcmFolder -export_grad_fsl bvecs bvals)
2 - mrinfo using previously extracted dwi and .b files (mrinfo dwi.nii.gz -grad file.b -export_grad fsl bvecs bvals)

Then I reconstructed tensors using dtifit. 
Solution 1 - works perfectely
Solution 2 - tensors flipped in x direction

**Comment by jdtournier** [comment]
Yes, that would be due to us fixing our incorrect bvecs handling, as [recently announced in this blog post](http://www.mrtrix.org/2016/04/15/bug-in-fsl-bvecs-handling/)... Sorry.

**Comment by arnaudbore** [comment]
Yeap, I've read this but I'm little bit confuse about why we have a different behaviors using mrconvert or mrinfo. Does that mean that once we've converted DICOM -> NIFTI we lose information about the coordinate system and then mrinfo is not able to convert correctly .b file into bvec bval files ?

**Comment by jdtournier** [comment]
Sorry, should've read your post more closely... I'm at the ISMRM, not a lot of time to look into things right now. I had a quick go, but I can't reproduce this with the up to date code. However, it so happens that the first data set I tried this with did have an old `grad.b` file lying around, and that was flipped along the x axis relative to what was in the corresponding `dwi.mif` headers (no DICOM lying around to check the import, but the headers seem correct for tensor tracking, the existing `grad.b` file clearly isn't). So I have a feeling this may have been caused by an old bug in the code when that `grad.b` file was created. Can you confirm whether your `file.b` is recent? Does it match what `mrinfo dcmFolder -export_grad_mrtrix newfile.b` produces...?

**Comment by Lestropie** [comment]
Just in case it's relevant:

Bear in mind that the directions specified within a `bvecs` file are with respect to the order in which the axes data are stored within the associated image. Therefore, if you first export the gradient table in `bvecs/bvals` format, then subsequently convert the image to a different image format with different strides, there's a good chance that those vectors will not be appropriate for the second image. `bvecs/bvals` files need to be managed very carefully with respect to the image they are to be associated with.

In hunting down the source of your problem, avoid using previously generated data wherever possible; _especially_ with gradient table data, given both the aforementioned issue and the prior *MRtrix3* issue with `bvecs` support. Try to produce a set of commands by which you can get from a DICOM image to an erroneous result, consistently and reproducibly; that then allows us to try to reproduce the problem at our end, rather than supposing that the issue may be present in your data prior to the steps being described.

Furthermore: If you happen to be running a Debian machine, you need to check your gradient tables by performing some tractography, rather than visualising the eigenvectors in `fslview`.

Cheers
Rob

**Comment by arnaudbore** [comment]
You're right I was mixing older version grad.b file with new MRtrix version. 

Because I work with MRtrix / FSL / Dipy I've seen that this problem has been fixed in MRtrix and FSL but now it propagates trough dipy as well: https://github.com/nipy/dipy/issues/1047.

I think we can close this issue since it's not a problem anymore.

**Comment by jdtournier** [comment]
Cool, good to hear. Thanks for feeding back.
