### ISSUE TITLE
dwi2fod: Algorithm options

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#604]
Following discussion at ISMRM2016.

- Merge `msdwi2fod` functionality into `dwi2fod`.
- Make algorithm selection a compulsory command-line option.
- Provide interface for a single-shell CSD algorithm that actually runs MSMT with 1 shell, 1 tissue, hard constraint. Sounds like this should also be the default?
- Original soft-constraint CSD to be provided as a 'legacy' algorithm.

**Comment by thijsdhollander** [comment]
As we discussed at ISMRM: it's best to have *no defaults* (as to algorithm selection) at all for this command, but rather an extra parameter (that *always* has to explicitly be specified) for each algorithm.  Automatic selections or defaults are too risky for something as crucial as the CSD step: users should make a conscious and well defined choice based upon their own requirements.

Also, as @jdtournier mentioned at ISMRM, it'd be good to hold off on including a hard constrained CSD until we've written something up on it.  I've been collaborating with Donald and Dave on this since quite a while ago, and recently included @bjeurissen in the loop at ISMRM (since he's obviously also been involved with a CSD variant).  I'll probably do a technical note soon (or an article, depending on what we envision putting in).  For now, people can just use MSMT-CSD for this purpose.  The "soft" CSD as well as the "hard" CSD may each have their own merits, so for that reason, it's probably also best to not push one algorithm as some sort of default.

So, for the release milestone, I'd not go any further than merging the "plain" (soft) CSD and the MSMT-CSD into a single command.  It's probably best @jdtournier and @bjeurissen look into this together; since they're both most involved with their own algorithms, and ensure everything is carefully ported into the single command.

The interface could become `dwi2fod ALGO dwi.mif response.txt odf.mif [ response.txt odf.mif ... ]`.  The `ALGO` always being explicitly requested (not optional, no default), and obviously each CSD variant needs a dwi image as input.  All algorithms will typically also require at least one response and odf pair, but multiple ones can be allowed (as the `msdwi2fod` does at the moment).

As to algorithm naming: I would suggest the "soft" CSD is currently ported unmodified and named simply "CSD", and MSMT-CSD is named... well, MSMT-CSD probably...  When we do include the "hard" CSD, we can still change the algorithm name of "CSD" to both "soft-CSD" and "hard-CSD" (or something other/better along those lines); so the change is clearly highlighted and users can rethink their choices if desired.

**Comment by Lestropie** [comment]
> > Sounds like this should also be the default?

> As we discussed at ISMRM: it's best to have no defaults (as to algorithm selection) at all for this command, ...

Whoops, yep. Never mind me, still recovering :-/

> it'd be good to hold off on including a hard constrained CSD until we've written something up on it.

OK good to know, I must have missed / forgotten that bit.
