### ISSUE TITLE
dwi2mask improvements

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#615]
A lot of people still encounter grief at this step; particularly as they fail to check their data.

One option that @draffelt posed was to do a non-linear registration to a manually masked template _b=0_ image, then propagate the mask back to subject space. Would take longer (seem to recall ~30s being quoted), and would only work for human images, but might be fairly robust.

There are various other ideas that could be tried, but this one could potentially be done for release.

**Comment by thijsdhollander** [comment]
I actually find it works fairly well, but provided the data have been corrected for bias fields (sometimes makes quite a big difference).  Overall, I never really see gaps in or bites out of the intended mask.  The only "fails" are mostly added pieces (but only when there's an artefact outside of the brain having high intensities) or an eye (or two :-)).

The thing with the registration approach is, for it to actually work robustly (with this very application in mind), you need... a decent brain mask. *rimshot* :smile:

I still think, all in all, the current approach is most likely to give the best boundary definition for most of the brain's circumference...  But maybe we need to document the fact that bias field correction is of key importance, and those occasional added pieces are a thing.  For group wise analyses, using the cross section of masks (when building templates, but also for other steps thereafter) basically tackles this particular issue.

Actually, now that I'm thinking of it, to get rid of the bulk of those annoying added pieces, that are connected via that typically "thin bridge" to the actual mask, couldn't we do something like (everyone switch on your sense of appreciation for ad hoc strategies at this stage):

1. erode the mask by an **extent**
2. select all components but the biggest one
3. dilate these components again by the **extent** of (1)
4. remove the voxels outputted by step (3) from the *original* mask
5. select the biggest component from the output of step (4) ... this because the erosion followed by dilation is still a morphological opening operator, and will leave a bit of extra voxels.

The challenge here is a good default for "**extent**".  Probably a very small number is more than enough.  If the bridge is too wide, it also indicates a wide bridge of high intensities, so the registration strategy would probably fail miserably anyway, due to the lack of a (good) mask.

I might give this a shot when I find a bit of time... I'll self-assign for now.

**Comment by thijsdhollander** [comment]
Ok, I was feeling rather inventive today, so I modified and extended elements of the aforementioned approach to a fast iterative multi-bridge multi-crap-to-bridge-ratio multi-crap-scale crap-removal algorithm.

Here's a typical `dwi2mask` output (multiple angles of the same thing): the complete thing was the original output, the darker thing is what remains after cleanup .  The bright orange things are the crap that got cleaned up. :smile: 

![screenshot0000](https://cloud.githubusercontent.com/assets/11952694/15315439/fb1e2ce2-1c5a-11e6-8479-30d0e6e3739c.png)
![screenshot0001](https://cloud.githubusercontent.com/assets/11952694/15315502/5365fa38-1c5b-11e6-8615-efa6e7163cef.png)
![screenshot0002](https://cloud.githubusercontent.com/assets/11952694/15315510/5e1957e0-1c5b-11e6-8b2f-3f4e00986e0e.png)
![screenshot0003](https://cloud.githubusercontent.com/assets/11952694/15315514/624473c2-1c5b-11e6-809b-377677f6fe64.png)

It can work fully automated, with a single parameter that relates to the maximal bridge width that one would reasonably expect.

When I find some more time (may not be this week, but soon), I might give it a shot of implementing it as an option to the `DWIBrainMask` filter.

Also, I can no longer look at these images without seeing this guy.

![squidward-head-full](https://cloud.githubusercontent.com/assets/11952694/15315669/6c70c3fe-1c5c-11e6-9858-be8f3b3bb2ce.png)

What has been seen, can not be unseen. :see_no_evil:

**Comment by draffelt** [comment]
Thijs, I think your crap removal algorithm looks like it could help. However it would be good to test on some more data to check the extent is good. I have some on beast that is problematic if you have time to try.  `dwi2mask` is already ad hoc enough, why not ad some more hoc. 

On the topic of a registration based method. I think once we have normalised cross-correlation metric. Registering b=0 images (without bias field or intensity normalisation) should be robust enough to propagate a mask. Maybe taking the intersection of dwi2mask and a registration-based method could work. Though I admit that restricting it to human brains is not ideal.

**Comment by thijsdhollander** [comment]
> However it would be good to test on some more data to check the extent is good.

Yep, definitely.  It's typically a fairly conservative approach still: it never ends up removing anything beyond what's attached to the "bridges".  The "bridges" themselves are never removed: they're quite hard to reliably detect, and might actually still represent a certain extent of the ("true") brain mask; so eating away at them any further wouldn't be a safe approach.
The example shown above was actually one of the `dwi2mask` outcomes on one of our old Trio controls.

I think when I get round to finding the time, I might potentially add it as a separate filter; it could then quite easily be included as an option (e.g., "`-cleanup`") to `dwi2mask`, but maybe also as an actual filter in `maskfilter`, so we can easily test its effect on a range of existing masks.

On the registration approach: a cross-correlation metric would indeed already go a very long way towards making such an approach much more robust.  The challenge (but maybe still pretty easy) would then become finding good default parameters for the regularization, so it can easily deal with a decent range of brain shapes (and indeed, there will be a practical restriction to anything at least reasonably close to a human brain shape; but that's probably ok for the majority of users).  I do like the idea of taking an intersection between both approaches' outcomes as well; as long as they're both acting in a "conservative" manner (the one based on the registration could, e.g., be dilated by 1 voxel, so slight subvoxel mismatches don't lead to potential exclusion of important edge voxels).

**Comment by draffelt** [comment]
Dilating by 1 voxel may be ideal for some downstream applications, since including CSF can give spuriously high FA voxels (Ben recently ran into an issue with dwiintensitynorm due to this).  Agreed, that it may be hard for a registration approach to beat the current one in terms of getting the edge just right.

**Comment by thijsdhollander** [comment]
This got partially addressed in #769 ; I'll close this one for now.  If we've got robust cross-correlation and a good human template and/or atlas in the future, we can always revisit; but that's currently not likely to happen *very* soon...
