### ISSUE TITLE
Facilities for multi-shell responses

### ISSUE THREAD

**Issue by thijsdhollander** [MRtrix3/mrtrix3#619]
Now that multi-shell response function files are becoming (or will quickly become) relatively common, we maybe need to make sure some of the obvious scripts/apps interacting with responses don't trip up.  The most obvious ones that come to mind are `shview` and the `average_response` script.  Sadly, I don't have the time to look into it any time soon, but just putting it here for reference...

**Comment by jdtournier** [comment]
Well, `shview` already does support multi-shell responses - always did... You can supply a matrix instead of a row vector, and each row will be interpreted as a vector of coefficients. Use the arrows to navigate. 

The one thing I would like to change in `shview` though is the normalisation option. Currently, normalisation is either on or off, and when it's on, each ODF/response is normalised to 'unit' l=0. I think it would be better to have a 'rescale' action (Esc key for example) that would apply that normalisation on the currently displayed ODF/response, and the scaling would be maintained between ODF/responses. I think this would make more sense in general...

I guess the `average_response` script might need to be modified - but we have discussed in the past the possibility of adding an app to handle matrix operations, this might be a good use case for this...

**Comment by thijsdhollander** [comment]
Hmm, just tested a multi-shell response with `shview`: it just showed the first shell (which happened to be the b=0 one), and the arrows didn't seem to have an effect.  I also noticed I'm still missing the menu bar in `shview` (reported somewhere in a much older issue, but I can't seem to find it at the moment).  Also, it seems for something like a CSF or other isotropic multi-shell response, `shview` interprets the file as a column vector (as if it were just a single shell with as many coefficients as there are actual shells).

**Comment by jdtournier** [comment]
Ok, the left/you arrows not working is most likely related to the menubar not showing. That's been an issue on 14.04 for a while. But only on Qt 5, right?

The interpretation of a column vector as a single response is an issue though. The vector is actually explicitly transposed if it's a row vector, to allow more flexibility in how the response is specified. I'm happy to get rid of that, and mandate that the response must be a row vector. 

To display multi-shell, l=0 responses sensibly though, we'll really need to modify the way the normalisation is handled as I'd suggested above. Otherwise all shells will come out looking identical by default...

**Comment by thijsdhollander** [comment]
So, related to #272 : upgrading to Ubuntu 16.04 also fixed the left/right arrows, so that specific aspect is no longer an issue.

**Comment by thijsdhollander** [comment]
The `average_response` script was updated by @draffelt in #779 , using a not very pythonic style of coding that does the job anyway (and doesn't require numpy!).  This probably ticks off the last thing I can think of in this issue's list; so I'll close it. 👍

**Comment by thijsdhollander** [comment]
As reported on the community forum at http://community.mrtrix.org/t/strange-dwi2response-results/539 , I've overlooked the fact that we forgot about `shview` treating multi-shell responses containing only b=0 shells as if they're single-shell: i.e., it read the text file as a column SH vector, rather than rows with only 1 entry...

**Comment by Lestropie** [comment]
The normalisation probably needs to be looked at too; flicking between _b_value shells should reflect the relative sizes of the response function rows. Maybe normalise to _l_=0 of the first row, regardless of which row is being viewed?

**Comment by thijsdhollander** [comment]
What I think would actually be quite nice (but read this as a feature request with low priority): a visualisation that shows all shells at once.  This could be in separate panels or "voxels/pixels", i.e., next to each other; but another option could be showing them all at once and making the surfaces partially transparent.  That immediately also shows people if their shells' responses are strictly decaying, etc...

Well, just an idea for a utopian future. ;-)

**Comment by jdtournier** [comment]
Weird that this got closed off, there were lots of unfinished issues here. From my previous posts:

The normalisation issue:

> The one thing I would like to change in shview though is the normalisation option. Currently, normalisation is either on or off, and when it's on, each ODF/response is normalised to 'unit' l=0. I think it would be better to have a 'rescale' action (Esc key for example) that would apply that normalisation on the currently displayed ODF/response, and the scaling would be maintained between ODF/responses. I think this would make more sense in general...

The isotropic response issue:

> The interpretation of a column vector as a single response is an issue though. The vector is actually explicitly transposed if it's a row vector, to allow more flexibility in how the response is specified. I'm happy to get rid of that, and mandate that the response must be a row vector.

**Comment by jdtournier** [comment]
Just one more comment:

> another option could be showing them all at once and making the surfaces partially transparent. 

That would be cool. But hard to do in OpenGL: transparency requires rendering in strict depth order. Very hard problem to solve. There are some order-independent transparency rendering techniques out there, but they're pretty hardcore...

**Comment by Lestropie** [comment]
Transparency = probably not worth the trouble. I thought about suggesting showing the responses for all shells side-by-side, but it'd take a bit of somebody's time to do, and RFs can be more difficult to compare side-by-side than flicking between; also the 'multi-shell' capability in `shview` may alternatively be used to look at response functions across subjects. So my only (feasible) suggestion would be to add overlay text (or change the window name) indicating which line number is currently being displayed from the input file.

**Comment by jdtournier** [comment]
All good points.

> So my only (feasible) suggestion would be to add overlay text (or change the window name) indicating which line number is currently being displayed from the input file.

Good suggestion. I might add that changing the window name is _much_ easier to do than overlaying text in the OpenGL window...

**Comment by thijsdhollander** [comment]
The isotropic multi-shell case got fixed (and lmax=0 in general supported) in #885.  Also, a bug that rendered everything initially as lmax=8 upon loading got fixed.  I stumbled upon the latter one since the changes related to the response function estimation resulted in myself working with lmax=10 responses now all the time.

As to this issue in general, what remains are mostly wish list items (not actual bugs):

1. normalisation options / defaults
2. better visualisation of the multi-shell aspect of responses; taking into account that a file could also contain other multi-SH things (not per se related to b-shells)

**Comment by jdtournier** [comment]
Thanks for tackling this with #885. However, as you mentioned, a few issues remain...

The first is reporting to the user which shell is being displayed. Currently, the titlebar will display the row number in square brackets. But this really doesn't help much here, one because the titlebar isn't obvious, and two because it's not displaying the actual b-value. 

So there's a couple of problems here: one is that the file format of the response function doesn't include the b-value. Changing that might be a bit tricky, and require some thought. The simplest would be to include a comment in the current response file formatted in a recognisable way ([backend currently ignores anything following a `#`](https://github.com/MRtrix3/mrtrix3/blob/master/lib/math/math.h#L127)), and simply listing the b-values that each row corresponds to. That would have the advantage of being entirely compatible with the existing codebase, and all we'd need to do is to allow the comments to be retrieved when [reading in a matrix file](https://github.com/MRtrix3/mrtrix3/blob/master/lib/math/math.h#L156), and then see if any of them match a format like `b-values: ` or something. But that would allow `shview` to read in the b-values if they're available, and display those. It would also remain compatible with current data, and also still allow uses that I sometimes make of it, like concatenating a bunch of responses or full SH vectors derived from different algorithms / debug runs, and displaying them together. 

The next issue is whether we need to do better than simply updating the titlebar. On my system, I can't even see the row number in the titlebar, the window starts out too small, and all I see is the start of the filename - and it was only `sh.txt`... The best thing would be to do the font rendering on the viewport itself, as is done in MRView. It's not difficult _per se_ - most of the difficult stuff is already dealt with - but will require some effort to get right. Mostly about setting the OpenGL viewport & projection matrices, and setting the right flags before doing the rendering proper. 

The normalisation issue is also one I'd like to have sorted out, and thankfully should be much easier to deal with - no OpenGL programming required. I reckon the suggestion I'd made in my earlier post is probably still sensible:

> The one thing I would like to change in `shview` though is the normalisation option. Currently, normalisation is either on or off, and when it's on, each ODF/response is normalised to 'unit' l=0. I think it would be better to have a 'rescale' action (Esc key for example) that would apply that normalisation on the currently displayed ODF/response, and the scaling would be maintained between ODF/responses. I think this would make more sense in general...

If everyone agrees, we should try to add this in too, it shouldn't take a lot of effort to get right?

**Comment by Lestropie** [comment]
Pretty sure this is all dealt with in #886 and merged in #785.
