### ISSUE TITLE
MinGW object section limit

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#655]
Going to raise this so that people can post an opinion if they have one.

Object files on Windows are limited to 32766 sections. I've been unable to compile a few commands in debug mode for a while now, and since registration was pushed I've been unable to compile the library in debug mode. We now have a user who can't compile in release mode due to this limitation. And it doesn't look like a MinGW solution is going to appear overnight.

So the question is:
Do we endeavour to move code from header files to .cpp files, and/or sub-divide .cpp files, to try to keep compilation working on Windows? This will likely incur performance penalties in certain instances. And if so, do we just try to keep release compilation working, or debug as well?

**Comment by jdtournier** [comment]
Yes, I already got @maxpietsch to try this out for `mrregister` a few weeks ago, but it wasn't clear there was an advantage. The issue was each cpp compile job was taking up almost as much RAM anyway, and now you had a whole stack of them filling up your RAM... and it didn't compile significantly faster either. Hopefully I've got the details right here - @maxpietsch, feel free to add anything if I'm talking BS.

This was just a quick crack at splitting up `mrregister`, maybe we didn't do it quite right. You really need to reduce the number of header files included in any one cpp file to the absolute minimum if this is going to have any impact, so it's quite a bit of work to do this right. Happy to revisit though, this does look like it's rapidly turning into a problem.

**Comment by Lestropie** [comment]
Not really about RAM usage or compilation time; you can always cap the number of processors if RAM usage is a problem, and there's always more time. It's about minimizing the amount of 'raw code' necessary to compile any particular object file, so the damned thing doesn't hit integer overflow. Which means shifting header code into `.cpp` files, so that use of those functionalities in subsequent headers / commands is dealt with by the linker rather than the compiler. But I can't say that I understand the concept of 'sections' in the compiler fully.

In the latest example it's `tckgen` that fails, because each individual algorithm is entirely header; moving each `init()` and `next()` function to a `.cpp` would probably do the trick, but then you've got function call overhead.

**Comment by maxpietsch** [comment]
I did split some classes into .h and .cpp files (affine and rigid transformations for instance) which also helps in developing as compiling them is much much quicker. Is there a disadvantage in doing this?

But when I tried to replace the templated function `run_masked`, which is the main function in the linear registration code, with multiple functions with manually declared types in separate .cpp files, compilation took more than 24GB RAM (8 cores) and did not feel any faster. 

Might be worth looking at [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use)?

**Comment by jdtournier** [comment]
> It's about minimizing the amount of 'raw code' necessary to compile any particular object file, so the damned thing doesn't hit integer overflow.

:astonished: really?!? Wow, I hadn't realised we'd written _so much_ code... 

- First option: add `-Wa,-mbig-obj` as per [this StackOverflow post](http://stackoverflow.com/a/28372660) (reported as working with MinGW64 in one of the follow-on comments). 

- Second option (which we might want to use anyway) is to use [C++11 extern templates](http://stackoverflow.com/a/8131212): put _all_ the code currently in the algorithm headers into a corresponding cpp file, leaving only declarations of the type (might need a bit of work to get it to work):
  ~~~C++
  class iFOD2;
  extern template void Exec<iFOD2>::run (const std::string& diff_path, const std::string& destination, DWI::Tractography::Properties& properties);
  ~~~
  In the cpp file, we'd also need to add the instantiation of that `Exec<>::run()` call:
  ~~~C++
  template void Exec<iFOD2>::run (const std::string& diff_path, const std::string& destination, DWI::Tractography::Properties& properties);
  ~~~
  i.e. same as for header, minus the `extern` specifier. So that would leave very little within the `tckgen.o` object itself, moving all the per-algorithm code within its own object file. No impact on performance whatsoever, this only affects the overall entry point... 

---

> I did split some classes into .h and .cpp files (affine and rigid transformations for instance) which also helps in developing as compiling them is much much quicker. Is there a disadvantage in doing this?

Only if the functions you're invoking are sufficiently lightweight and performance-critical that the overhead associated with the function call might be expected to impact performance. Not an issue for outer loops, etc., but potentially a problem for small chunks of code run within very tight loops. 

> But when I tried to replace the templated function run_masked, which is the main function in the linear registration code, with multiple functions with manually declared types in separate .cpp files, compilation took more than 24GB RAM (8 cores) and did not feel any faster.

So this is where it might be worth double-checking whether we had properly stripped each cpp file to the bone, in terms of headers included. It might very well be that each of these actually needs to include pretty much all of the headers anyway, in which case there would indeed be very little point...

**Comment by Lestropie** [comment]
> First option: add `-Wa,-mbig-obj` as per this StackOverflow post (reported as working with MinGW64 in one of the follow-on comments). 

*hits head on desk*

Saw that this morning and tried it with no success. But just now realized that that's a _single_ command-line option, _not_ two (the '`-Wa`' passes the subsequent option down to the assembler).

That results in a few cases of:

```
ERROR: ( 1/97) [CC] debug/cmd/mrtransform.o

g++ -c -std=c++11 -pthread -DMRTRIX_WINDOWS -mms-bitfields -march=native -DMRTRIX_WORD64 -isystem /mingw64/include/eigen3 -Wall -O0 -g -D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1 -Wa,-mbig-obj -Isrc -Icmd -I./lib -Icmd -isystem /mingw64/include/eigen3 cmd/mrtransform.cpp -o debug/cmd/mrtransform.o

failed with output

C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/as.exe: debug/cmd/mrtransform.o: section .debug_frame$_ZNK5Eigen12CwiseUnaryOpINS_8internal13scalar_abs_opIdEEKNS_5BlockINS4_INS_6MatrixIdLi2ELi2ELi0ELi2ELi2EEELi2ELi1ELb1EEELin1ELi1ELb0EEEE7functorEv: string table overflow at offset 10000132
C:\msys64\tmp\ccU4ycRv.s: Assembler messages:
C:\msys64\tmp\ccU4ycRv.s: Fatal error: can't close debug/cmd/mrtransform.o: File too big
```

_Almost_ got around that by changing `-O0` to `-Og`, which is [probably a good change anyways](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html).

Final remaining error:
```
ERROR: ( 1/2) [CC] debug/cmd/mrregister.o

g++ -c -std=c++11 -pthread -DMRTRIX_WINDOWS -mms-bitfields -march=native -DMRTRIX_WORD64 -isystem /mingw64/include/eigen3 -Wall -Og -g -D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1 -Wa,-mbig-obj -Isrc -Icmd -I./lib -Icmd -isystem /mingw64/include/eigen3 cmd/mrregister.cpp -o debug/cmd/mrregister.o

failed with output

In file included from ./lib/algo/loop.h:20:0,
                 from ./lib/algo/copy.h:20,
                 from ./lib/image.h:28,
                 from cmd/mrregister.cpp:17:
./lib/progressbar.h: In constructor 'MR::ProgressInfo::ProgressInfo(const string&, std::size_t)':
./lib/progressbar.h:283:81: internal compiler error: Segmentation fault
             prog = std::unique_ptr<ProgressInfo> (new ProgressInfo (text, target));
                                                                                 ^
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://sourceforge.net/projects/msys2> for instructions.
```

Kicked in when RAM usage hit 4GB. Hopefully OK on release though (testing now).

Also: Would be cool if we could catch any todo list entries that failed due to running out of RAM, re-run those single-threaded after everything else that can be run has been run, and repeat.
