### ISSUE TITLE
port sample_tracks & resample_tracks from previous version

### ISSUE THREAD

**Issue by jdtournier** [MRtrix3/mrtrix3#67]
I'm getting some requests for these commands...

**Comment by jdtournier** [comment]
Should be addressed with commit 1d570e9 - needs further testing before closing off.

**Comment by Lestropie** [comment]
Should also give `tcksample` the capability to output a .tsf file; as has been pointed out to me twice today, TSFs are all over the documentation but there isn't actually any way for users to generate them...

**Comment by jdtournier** [comment]
Good call! 

I also need to add the option to output the resampled tracks if the `-resample` option was used - especially if we add an option to output a TSF file...

**Comment by Lestropie** [comment]
From memory I wanted some of this to piggyback off some of the TWI code; e.g. may want to calculate the mean value of a scalar image along each streamline and output a vector file, rather than having multiple samples per streamline. (MRview will happily colour streamlines by such a file rather than a TSF).

**Comment by dchristiaens** [comment]
Created new issue for TSF support. Closing this one.
