### ISSUE TITLE
Extract additional data from DICOM and export to JSON file

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#725]
In the BIDS standard, each image (or image series) is generally expected to have an associated JSON file, containing various information about the acquisition. This plays essentially the same role as the key-value pairs in the MRtrix image format header. However to fully conform to BIDS, we will need to support this format.

So this issue actually has two components:
- Support exporting image header key-value pairs to JSON format - not sure where to put the functionality though (e.g. option in `mrconvert`, or dedicated command?).
  - Could be also possible to _import_ such information from a JSON file into an image header; would have to limit the functionality to e.g. `mrconvert` only.
- Extract additional acquisition information from DICOM (e.g. effective echo spacing, TE, TR, PE direction, slice direction), and store in either image header or JSON file.
  - This information could be used to better automate `dwipreproc`.
  - Should we _always_ grab this information and store in the header, or should an extra flag be required? Or should it be moved to e.g. `dcminfo` rather than being automatically grabbed by the DICOM handler?

Listing here and flagging with the coding sprint preparation milestone in case people want to express opinions on how this should all be handled before it happens. But given this is more specific to the goals of the sprint, it will likely be done as part of the sprint rather than beforehand.

**Comment by jdtournier** [comment]
OK, this is going to require some effort... 

My first thought is that if we are going to modify the DICOM handling code in any way to grab this information, it'll probably have to be done while reading the full image, to ensure all the relevant data have been captured. `dmcinfo` only scans through a single DICOM file, which won't be guaranteed to contain all the information needed (different slices may have different parameters, e.g. PE direction). So that strongly argues for modifying the DICOM image handling code itself, rather than rely on `dcminfo`. 

If we do that, then there's a good argument for including all of that information in the image header directly - it may prove useful in other applications (like `dwipreproc`, as Rob mentioned). It would be a bit daft to go to the effort of reading all these data from the DICOM and _not_ make it available more generally. 

Producing a JSON file is relatively trivial, and won't need a lot of work. That would best be served by an additional option to `mrinfo`, to essentially dump the header contents to a JSON file. Presumably that can be done in a way that is fully compatible with the BIDS standard, yet includes all the information stored in our header (although there will no doubt be exceptions, our strides for example are likely to be more general than supported in their standard - haven't checked). 

Importing a JSON header will be a lot harder. We would need to support JSON parsing, which is not trivial if it's going to be robust. I recommend we use a 3rd party library for this, such as the [JSON for Modern C++](https://github.com/nlohmann/json) library: it looks solid and fully tested, it's C++11, header-only, and MIT licensed. But it's still going to require some head-scratching to figure how to handle a JSON import: does this mean we literally replace the entire header with the contents of the JSON file, or should we restrict that to the case where the image dimensions match? Or any other checks and balances? Should we simply run a few checks and warn the user that things don't match and the output image might consequently be garbage? A few issues there, but probably nothing we can't work out a sensible solution for. I'd agree that `mrconvert` would be the right place for that.

**Comment by Lestropie** [comment]
Agree with 1, 2 and 3. For 1 I'll focus on grabbing the DICOM fields that I need / other packages are grabbing, we can always expand the list / verify support for data from other vendors down the track.

For 4 I'm tempted to go for a simple custom parser for importing rather than introducing another dependency. I don't think we need to try to achieve bullet-proof JSON support, we just need to be able to import the kind of information that BIDS-compliant databases are going to include in such a file; and from _all_ of the examples I've seen, it's literally just key-value pairs, they're not storing any hierarchical data. Also, they're basically using these files to store anything that doesn't go into the NIfTI header - which means it should be possible to just import them into header key-value pairs, we shouldn't have to worry about conflicts with 'critical' header fields (at least for now), or when to convert from strings to other types.

I've got experience with parsing various types of file formats, so I'm confident I can make it throw a meaningful error if it encounters something that's permitted in the standard but the parser is not capable of handling.

**Comment by jdtournier** [comment]
> For 4 I'm tempted to go for a simple custom parser for importing rather than introducing another dependency. 

I'd have to disagree here. If there is a fully compatible open-source header-only library that we can simply drop into the MRtrix `src/` tree, I really don't see why we should avoid it. This is also how the OpenGL calls are handled, by the way: through a (slightly modified) third party library (albeit a code _generator_ rather than a static set of files). If the licence allows us to include the code wholesale, the fact that it's technically a dependency shouldn't be a problem at all. 

How we might do this is up for grabs. One simple option is to have it as a submodule, and ensure `./configure` or `./build` brings the submodule up to date (as the `./run_tests` script does for the `test_data` repo). This would make future upgrades slightly easier than the alternative, which would be a wholesale dump of the relevant code directly into `src/`, making it an integral part of the _MRtrix3_ codebase. I'm not too fussed either way, but I would tend to prefer the clean separation of a git submodule - that's actually _exactly_ what they're for. 

On that note, we could also manage the installation of Eigen that way. Only snag is that it's hosted via mercurial, but there's nothing stopping us from cloning it using [`git-hg`](https://github.com/offbytwo/git-hg) into a git repo hosted within the [_MRtrix3_ GitHub organisation](https://github.com/MRtrix3), and using that. Might sort out a few issues... What do you think?

**Comment by Lestropie** [comment]
> If the licence allows us to include the code wholesale, the fact that it's technically a dependency shouldn't be a problem at all.

OK: if we can do it that way, then let's go with that. 

> How we might do this is up for grabs.

According to their page it's just a single `.hpp` file. Might not be worth mucking about with submodules if updating it only requires dumping the newest version of that one file in place and committing. If we end up down the track with multiple dependencies handled using submodules, then it'd make sense to add this to the list; but for this alone it might not be worth the trouble.

**Comment by jdtournier** [comment]
Well, if it's a single `.hpp` file, I totally agree. Besides, we'd need to rename that to a `.h` suffix anyway if the build script is to pick it up, so the submodule approach wouldn't work anyway...

**Comment by Lestropie** [comment]
Closed via #785 merge.
