### ISSUE TITLE
Sticky move in mrview

### ISSUE THREAD

**Issue by maedoc** [MRtrix3/mrtrix3#761]
I just got a shiny mac, and for some two touch combination on the touchpad, mrview gets stuck moving the image around in the window and no amount of clicking or esc seems to stop it; I usually have to quit and relaunch.

I compiled recently from Git (I can pull, recompile and test when plugged into AC again) against Qt5 from brew, in case that helps. Maybe it's a glitch in Qt or Mac, not mrview. Any tips would be helpful.

**Comment by maxpietsch** [comment]
I can confirm this issue on my mac. I also had to close mrview. It happened often when drawing ROIs via touch pad which might be coincidental but makes this bug very annoying... From memory, it might have happened after something like a pan gesture via [tap and hold](http://doc.qt.io/qt-5/qtapandholdgesture.html) but today it proves hard to reproduce. I have Qt 5.6.1.

**Comment by jdtournier** [comment]
I reckon @maxpietsch is right that it might be related to the handling of the pan gesture in Qt5. As far as I can tell, this is activated via a tap and hold (i.e. place your finger on the touchpad and leave it there without clicking or moving for a second or so), and then drag around to pan. It should revert back to normal behaviour if you take your finger off the touchpad for a second or so. 

That said, on the few occasions where I've actually had to use MRView on a Mac, I've found that this feature gets in the way more than it helps. In terms of getting stuck in some unusable state, I'm guessing the most likely explanation is that mouse press events that would have been propagated to the appropriate handlers are being intercepted by the gesture handling backend, which can cause trouble if for example our code registered a mouse click event that starts pan mode, but fails to receive the corresponding release event due to it being usurped by the gesture handler. That would prevent MRView from coming out of pan mode, for instance. 

So two options: get rid of the pan gesture (no great loss IMO), and/or make sure the gesture handler resets any structures related to mouse click events (probably wise to do this even if we get rid of the pan gesture, actually, just to avoid similar interactions with the pinch to zoom and rotate gestures...).

**Comment by maedoc** [comment]
Thanks for describing the mechanics of the gesture: at least now that I can do it intentionally, it doesn't seem to get stuck.. pebcak?

**Comment by jdtournier** [comment]
Maybe... :Wink:

But it does sound like there might be an issue with its interaction with the ROI tool. Definitely worth taking a look. And I'm open to feedback on whether that pan gesture is actually useful in any way. I don't have a Mac, so I don't have much experience with actually using it...

**Comment by maxpietsch** [comment]
This is still an issue with qt 5.9.1 (so not [this](https://codereview.qt-project.org/#/c/186452/) bug). 

I get sticky pan movements on my macbook air (dual core with little graphics RAM) when I have ODFs loaded with (>3) detail in the single pane view or at detail level 3 in ortho view. It seems to not happen when I zoom a lot in, hinting at that we have some kind of race condition between redrawing and touch release check. Also, it does only happen with the touchpad (built in or external), not with a mouse.

My current workaround is to deactivate ODF display, pan, reactivate it. If the pan cursor gets stuck then I change focus to another window and then back to mrview which often after some seconds becomes responsive and the mouse unstuck. Not great...
