### ISSUE TITLE
Stats: Handle NaNs

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#817]
I believe that for FBA as it exists now, if an appropriate subject fixel can't be found for a given template fixel, it is given a value of 0.0. This kind of issue is probably exacerbated in my particular case: lots of fixels in template space where there's simply no data for a subject, and zero isn't really a meaningful 'default value'.

Rather than throwing an exception, it would be preferable if deep in the guts of the stats code, non-finite values were detected and excluded from the relevant operations (could divert to different classes / functions if performance penalty in handling such is too great).

**Comment by draffelt** [comment]
This is going to be somewhat tricky. Since you would basically need to exclude specific subjects on a per voxel/fixel/edge basis. This would require a different design matrix per test, and therefore a pinv per fixel (instead of per permutation). 

I guess this sort of thing would also be useful for looking at patient populations with masked-out lesions.  I recall there is a SPM toolbox investigating brains with lesions. But i'm not sure if this is for stats, or just for registration.

**Comment by Lestropie** [comment]
Closed by #1543.
