### ISSUE TITLE
Return mean b0 image with dwiextract -bzero

### ISSUE THREAD

**Issue by dchristiaens** [MRtrix3/mrtrix3#845]
I very often find myself typing:
```
dwiextract -bzero dwi.mif - | mrmath -axis 3 - mean b0.mif
```
Give that `dwiextract -bzero` and `dwiextract -shell 0` are currently identical, I was thinking that maybe we could make `-bzero` output the mean b=0 image and reserve `-shell 0` for extracting all volumes at b=0.

In that case, the above would simplify to
```
dwiextract -bzero dwi.mif b0.mif
```
whereas
```
dwiextract -shell 0 dwi.mif b0series.mif
```
would still allow to extract all b=0 volumes.

Thoughts?

**Comment by jdtournier** [comment]
I'd be happy with that, but I think there's a bit more logic behind the `-bzero` than a simple `-shell 0` - no doubt @Lestropie will expand on this. 

Also, this is likely to break of lot of existing scripts, both ours and others. I'm not saying we therefore shouldn't do it, but we should only do this if we genuinely feel it's worthwhile.

**Comment by dchristiaens** [comment]
Yes, I was worried about that and you're right that we should discuss this carefully before changing anything.

**Comment by Lestropie** [comment]
`-bzero` extracts any volumes below the _b_-value threshold _without_ invoking the `DWI::Shells` class, and therefore works on non-shelled data (which would otherwise throw an exception).

Even if `dwiextract -bzero | mrmath mean` is a common combo, it's a perfectly reasonable combination of two well-defined operations; and the nature of the command naming convention makes it completely explicit as to what's going on. Personally I'd prefer to leave it that way, rather than having a convenience option saving a few characters but then having the same result achievable through two different-yet-very-similar syntaxes (`dwiextract -bzero` v.s. `dwiextract -shell 0 | mrmath mean`).

**Comment by draffelt** [comment]
I also find myself using the same command _a lot_, not just with the bzero, but also the DW volumes. 

I guess we could have a `-mean` option in dwiextract. However I'm not that convinced as it goes against  the whole the MRtrix/unix philosophy. I'm sure there are lots of other commonly used pipes we could eliminate by adding in more options here and there.  

Alternatively, you could just create a script or an [alias](http://stackoverflow.com/questions/7131670/make-bash-alias-that-takes-parameter).

**Comment by thijsdhollander** [comment]
I'm not too fussed to see functionality added for "shortcut" reasons myself, but I'm ok with the pipe as it stands too.  It's definitely not too obscure, I'd say.  Cases I'd give up that (hardcore :wink:) philosophy would be when the piping or other construct becomes obscure for your more average Joe user...

Other than that, if you do want to go for adding a shotcut in this case, I'd go for @draffelt's `-mean` proposal, or at least something with another name somehow.  I got `-bzero` sitting in quite a few important scripts myself, and as @jdtournier mentioned, I suppose I'm not the only one...

**Comment by draffelt** [comment]
Even though we can do it with piping, I think having a `-mean` option can't hurt. And won't break any existing scripts.

**Comment by Lestropie** [comment]
Having a separate `-mean` option to calculate the mean value per shell extracted, rather than forcing the `-bzero` option to calculate the mean value across shells, would definitely be preferable. Means it generalises to non-_b_=0 shells, is clear and explicit at the command-line as to what's going on, and is quite clearly a 'shortcut':
```
dwiextract -bzero -mean
```
v.s.
```
dwiextract -bzero | mrmath mean
```
I'd be happy with that. You'd need to be careful however about producing a 3D or 4D image depending on whether `-mean` is specified, and whether it's only one shell (or only the _b_=0's or only the non-_b_=0's) that is being extracted.

**Comment by thijsdhollander** [comment]
I'd already forgotten about the functionality of extracting multiple shells at once indeed... in that way, a `-mean` option can even do things that just a "simple" `| mrmath mean` can't; e.g. `dwiextract -shell 1000,3000 -mean` would output a 2-volume image with both b=1000 and b=3000 shell means.

**Comment by dchristiaens** [comment]
I'm glad we seem to agree that it's worthwhile having a short call to get the mean b=0 image. We could indeed design the interface in many ways. It doesn't even need to be in `dwiextract` as far as I'm concerned, but it would be good to have a short command for it.

However, I am not convinced about a `-mean` option. As @draffelt said, it goes against the Unix philosophy and it doesn't even save that many keystrokes. Sure, it would allow all sorts of fancy stuff with multiple shells, but I already created a script for that (#844). What I'd like to have as a user is a command to get the b0, as short and simple as possible, period. An alias `dwi2b0` would be ideal, if it didn't rely on it being available on any system I use.

My main point, however, was the seemingly double use of `-bzero` and `-shell 0`. @Lestropie, you say that 
> `-bzero` extracts any volumes below the b-value threshold _without_ invoking the `DWI::Shells` class, and therefore works on non-shelled data (which would otherwise throw an exception).

But couldn't you check that just as easily at runtime? If the `-shell` argument is 0 you mask all volumes with b < threshold, otherwise you call the Shell class... I don't see why avoiding the Shell class requires a separate option, or am I missing something?

About the issue with breaking existing scripts, that is indeed a valid concern. Our own scripts would be quickly updated with a find-replace, but the real question is if it will break our users code. Personally, I can think of little other use cases for `dwiextract -bzero` than to subsequently compute the mean b0. Assuming this is what the majority of users is using this for, we could let `dwiextract -bzero` output the mean b0 with an additional singleton dimension (cf. #344). As such, this change wouldn't break those users scripts since the subsequent `mrmath - mean ...` call would just become a no-operation. It's a bit of a hack and there will inevitably be some joe who extracts all b0's for some other purpose, but technically we're still in beta, right?

**Comment by thijsdhollander** [comment]
I'm a Joe that uses it quite often, both in scripts and directly, without following up with `mrmath mean`, needing all b=0's extracted.  I've taught the practice too to quite a few of my collaborators for different reasons.  One (simple) example is quickly assessing the level of motion or signal drift across a scan: both our own old and new schemes as well as a couple I designed for them nicely have the b=0's distributed over the series for this (and other) purposes.

I'm not convinced this shortcut is worth "breaking" (changing) that for... I don't fully understand why it has to use *that* specific or any *existing* option in general: if it's a desired addition (and I can definitely appreciate it for that purpose; I'm more pragmatic than a philosophy if it benefits convenience for users and doesn't confuse them 🙂) and there's a desire to keep it a simple single option (I can also appreciate that!), then why not add it with its own name?  That will also allow for a name that better indicates what it does, and sets it more clearly apart from `-shell 0`.  I don't feel that `-bzero` in a command that is described as just extracting images, clearly indicates that it will also compute the mean...  Something like `-meanbzero` would probably do a better job at that.

**Comment by jdtournier** [comment]
Nice to see so much discussion about this. Just thought I'd throw in my comments too.

First off, I'm personally not a huge fan of adding more options to existing commands to do things that can already be achieved very simply with existing commands. Besides adding a bit of extra bulk and code to maintain, I reckon it's also not necessarily going to be used a great deal. Few users will know about it, and those that know what they're doing will probably understand the logic of `dwiextract -bzero - | mrmath - mean ...` quite clearly anyway. More to the point, while it's convenient to just get the mean signal (admittedly a very common operation for us), it's not as flexible as the two-stage process unless we decide to also implement some/all of the other operations that `mrmath` supports. So all this to say that I don't necessarily find the argument for modifying the command itself particularly compelling. It's not difficult to do, so if people feel strongly about this, go for it - it's just not where I'd invest my efforts.

However, on the topic of making `-bzero` default to the mean _b_=0:

> Personally, I can think of little other use cases for dwiextract -bzero than to subsequently compute the mean b0. 

Actually, in practice that's probably going to be the _least_ common situation for users, given that it's likely to be the first thing that happens in `dwipreproc`, whether in the script itself or in preparation for it. You don't want to average at that point, since TOPUP can perform its own motion correction on the individual volumes...

**Comment by dchristiaens** [comment]
Point taken: there is a use for extracting all b0 images. I still don't see the point of having `-bzero` if `-shell 0` could theoretically give you the same output, but I don't mind preserving its legacy if people have become so fond of `-bzero` :wink: 

So let's keep `dwiextract` as is. I agree with @jdtournier that 
> I'm personally not a huge fan of adding more options to existing commands to do things that can already be achieved very simply with existing commands. Besides adding a bit of extra bulk and code to maintain, I reckon it's also not necessarily going to be used a great deal.

Therefore, rather than adding a `-mean` option to `dwiextract`, I'd rather include a one-line `dwi2b0` bash script in the `/scripts` folder if everyone is OK with that? Maybe more of these shortcuts / patterns / convenience functions are to follow?

**Comment by thijsdhollander** [comment]
> I'd rather include a one-line `dwi2b0` bash script in the `/scripts` folder if everyone is OK with that?

Yep, no worries.  For the reasons mentioned above, I'd suggest `dwi2meanb0` though, if the functionality is to be specifically just that.  Only one extra keystroke with auto-complete.

**Comment by dchristiaens** [comment]
Going through my old issues and surprised to see that this was still open. Since we've had the `dwishellmath` script for ages now, I'm closing this off.
