### ISSUE TITLE
Add F-test to fixelcfestats, mrclusterstats, and vectorstats

### ISSUE THREAD

**Issue by draffelt** [MRtrix3/mrtrix3#855]

**Comment by Lestropie** [comment]
Note: Could be expanded to / alternatively implemented as G-statistic as described in Winkler et al. NeuroImage 2014. Requires manual definition of variance groups in this instance (but if not provided, would default to a single variance group, and would give an identical result to the F-test).

**Comment by Lestropie** [comment]
I have an interesting dilemma here.

Currently, I store a flag for each statistical test to determine whether it's a t-test or an F-test. If it's a t-test, I take the square root of the value of F and determine the sign based on the regression coefficients. Now on its own, this does exactly as expected. However these values would typically then undergo statistical enhancement, which requires either a cluster-forming threshold or the use of an exponent during threshold-free cluster enhancement. Therefore, if both t-tests and F-tests are performed in a single command execution, the efficacy of statistical enhancement could vary substantially between these. In the extreme case of a single t-test contrast row and an F-test including only that row, the behaviour of the latter in e.g. CFE would be comparable to doubling the *H* parameter.

So: If performing statistical enhancement of F-tests, should the cluster-forming threshold and/or the TFCE *H* parameter be explicitly altered in order to make the enhancement behave comparably to how it has been tuned for t-tests? Or if it's added as a command-line option, what should be the default?

**Comment by Lestropie** [comment]
Bumping in case anybody has any thoughts on the comment above before #1543 is merged.

**Comment by Lestropie** [comment]
Residual comment closed by 3f9a809 pending merge in #1543.
