### ISSUE TITLE
Release distribution platforms

### ISSUE THREAD

**Issue by Lestropie** [MRtrix3/mrtrix3#902]
* GitHub releases

* Docker

* Snap

* NeuroDebian

* Tracking download / installation numbers: Make use of whatever mechanisms are in place within individual distribution platforms, but don't bother putting effort into trying to track e.g. unique git clones

* Encouragement to join community forum, regardless of installation mechanism

* Windows: Try to package MSYS2 & QT into single installer, removing unnecessary components to minimize size. No separate Windows 10 Ubuntu Bash install since it doesn't support QT.

**Comment by jdtournier** [comment]
Just a couple of comments here:

- the Neurodebian side of things will be managed by them independently. They've done a great job with MRtrix 0.2, I expect that'll continue just fine with MRtrix3

- On the Windows side: by all means try to reduce the size of the download by removing unnecessary components, but we should make sure the MSYS2 install is nonetheless fully functional. We should also figure out a way to support updates on that platform that don't require downloading the whole thing all over again (it'll be close to a 1GB download!). Best thing would be to set up a pacman repo for this so it can simply be included in the package sources list, and updated along with everything else with a simple `pacman -Syu`. It might also make installation much easier on Windows, we'd just need to get users to install MSYS2, then issue `pacman -Syu mrtrix3`, and they'd be set. No idea how much work that might be though...

**Comment by bjeurissen** [comment]
Regarding windows: I agree that the simplest option for the user would be an installer which bundles msys2 and qt. Stripping the unneeded Qt stuff is easy, but stripping the unneeded msys2 not so much... Also note that this approach should also include python.  I kind of gave up on this route for now because I always ended up breaking some part of the msys2 system and the full msys2 system is just huge... Another option is to let users use their terminal of choice, i.e. providing only the qt and mrtrix binaries in the installer, but this will be a nightmare to support. Should we still want to follow the installer route, we can reuse a lot of the code from the NSIS installer that I created for the 0.2 release.

Creating msys2 packages for mrtrix releases on the other hand is super-easy. I only had to modify the PKGBUILD script that I had lying around for arch linux. If you want to give it a try: https://www.dropbox.com/s/hk7006bgyzhej96/mrtrix3-0.3.16-1-x86_64.pkg.tar.xz?dl=0 . Curious to see if it will work on your systems as well. Ideally, one would test it on a clean msys2 install.

It should install with a simple ``pacman -U mrtrix3-0.3.16-1-x86_64.pkg.tar.xz`` pulling in all the runtime dependencies. Of course we would still need to setup a pacman repo, and maintain the package...

**Comment by elopio** [comment]
I work on snapcraft, and thought your project would be a really interesting addition to the Ubuntu store. So I made a snapcraft.yaml to help you getting started: #935 

Any questions or comments, please let me know.

**Comment by Lestropie** [comment]
Bumping for priority; @jdtournier I know you've been working on Windows packaging, is there anything else that other devs could be contributing to in this context?

**Comment by jdtournier** [comment]
Yes, we need to sort this out. So here's my thoughts:

- **Windows:** I reckon we should use a PKGBUILD file like @bjeurissen proposed (I also came up with my own version, pushed to [this repo](https://github.com/MRtrix3/MinGW)), to produce a package suitable for installation, and upload that to the release on GitHub (as is already the case for [3.0_RC1](https://github.com/MRtrix3/mrtrix3/releases/tag/3.0_RC1)). Users can download that and install with a `pacman -U mingw-w64-x86_64-mrtrix3-3.0_RC1-1-x86_64.pkg.tar.xz`, and `pacman` will deal with installing all required dependencies. So it should work even from a clean install of MSYS2 (I checked), which means first-time installation should be relatively easy. @bjeurissen mentioned we could set up our own repo, but that sounds like additional hassle - and adding our repo to `pacman`'s config requires editing `/etc/pacman.conf` manually, which of course can be done, but isn't as simple as I'd like. On the other hand, installing from the download means they can just copy/paste the relevant command, and it should just work. Other 'benefits' are that users would be in better control of which version they're running (it won't update behind their back), and we get download counts. :+1:

- **macOS:** I spoke with @maxpietsch about this on a number of occasions. One option is to install via a pre-compiled homebrew recipe ('bottles'...?), which has the advantage that we don't need to manage all the other dependencies already provided by homebrew. I'm not sure I fully understand all the intricacies involved in this, but no doubt @maxpietsch (or anyone else with an opinion regarding macOS) can comment on this. 

- **Linux:** this is undoubtedly the hardest to deal with, given the vast number of different distributions out there... We should definitely rely on 3rd party projects such as Neurodebian as the default go-to distribution channel, along with other newer technologies like docker and snapcraft, but I think we also need to provide a fallback binary installation that just works everywhere, most likely via the `package_mrtrix` script. This will need a bit more tweaking to figure out exactly which libraries are required, particularly on the graphics side of things. We don't want to include any system libraries such as OpenGL and X11, since these are designed to integrate tightly with the running kernel, and most likely won't work on different kernel versions. We just want all the Qt5 libraries and relevant plugins, and should rely on the running system to provide the remainder of the graphics stack. I had a quick look into that when I cleaned up the `package_mrtrix` script a few weeks back, but couldn't think of a simple, clean way of reliably sorting out which libraries need to be packaged... I might have a look into using the package manager (probably `pacman` on Arch Linux) to provide a clearer picture on that front. Ultimately, it might have to be dealt with manually... 

General issues to be considered throughout for all of these: 

- it would be good to be able to track downloads. However, the reality is we won't ever be able to do this with any degree of reliability. If _MRtrix3_ gets picked up by NeuroDebian for instance, that's a large fraction of our user base whose installs we won't be able to track (unless NeuroDebian itself provides this information). So I'm not sure we should make this a priority...

- it would be great to have automated processes in place to build the relevant packages and upload to the right places as soon as new tags are pushed to the master repo, but again I don't see that we'll be able to do this easily. We will at the very least probably need to rely on users running the relevant scripts manually from their systems. Anything else would I guess rely on some form of cross-compilation, with all the idiosyncrasies that involves. Hopefully, new releases will be sufficiently infrequent that this shouldn't become a burden. But at the very least we should work out foolproof scripts for each platform, and make sure they're available on GitHub so any of us can build the packages when required. 

- I'm torn between strategies that allow automated updates, and those that don't. The reality is most users probably don't want the software to be updated along with all the other parts of the system, and only perform an update consciously when they feel it's needed. It may very well be that 3rd party distribution channels will provide continuous updates, so it might be best to rely on them to do this, while we focus on providing one-off, downloadable packages. But I have to admit I'm not sure what the best strategy is here...

**Comment by maxpietsch** [comment]
I won't have time in the next weeks to look into it but I think the best would be homebrew [bottles](https://github.com/Homebrew/brew/blob/master/docs/Bottles.md) However, I am not sure if we can integrate into our mrtrix3 formula or if this has to be integrated with a official homebrew repo. [Here](https://github.com/Homebrew/homebrew-science/issues/1393) is one we could ask.

A truly standalone version would be to pack it up ourselves using something like package_mrtrix and wrap it in a defined folder structure that Apple calls a standalone application bundle (.app). 
As an .app is a directory, we could presumably add it to the path and have all binaries and scripts accessible from the terminal as well. This could then also be shipped with homebrew as a [cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) and would allow to have mrview in the /Applications folder.

For that, we'de need a copy of the package_mrtrix script that writes an .app [conform](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFBundles/Introduction/Introduction.html#//apple_ref/doc/uid/10000123i-CH1-SW1) folder which then could be manually dragged into the Applications folder or shipped via homebrew casks. To package mrview and shview we'd probably need to use a static version of qt: https://doc.qt.io/qt-5/osx-deployment.html

**Comment by bjeurissen** [comment]
Concerning windows packaging: for users it would be much easier to have a simple standalone installer, including all the dependencies, like I did for MRtrix2. We can reuse all the code from that installer without any effort, but the downside is that it will not come with the msys2 terminal, unless we can bundle a minimal version of that too.

**Comment by elopio** [comment]
I'm still happy to help with the packaging for Ubuntu :)

**Comment by jdtournier** [comment]
@elopio: thanks for the offer, it's always appreciated! I'm guessing you're talking about installation via snapcraft? That would be great, but in our field I reckon by far our biggest distribution vehicle for Debian-based distros has to be neurodebian. I do think snapcraft will prove useful for many though - though I have to admit I'm not sufficiently familiar with the technology to comment here...

**Comment by jdtournier** [comment]
@bjeurissen: I can see the appeal of a single-click installer, but given how much we ride on top of MSYS2, I don't think it makes much sense to go that route. We'd basically be repackaging all of MSYS2 and more... I reckon we could probably figure out a couple of commands that would download and install MRtrix3 from a fresh MSYS2 install - maybe a combination of `wget` and `pacman`... What would basically be a copy/paste job, which any user should be able to deal with - and if they can't, I don't see how they could possibly use MRtrix3 at all anyway...

Ultimately, if Windows subsystem for Linux works out Wayland support, we might be able to ditch MSYS2 altogether and rely purely on neurodebian for Windows too...

**Comment by jdtournier** [comment]
OK, now that `3.0_RC3` is out, it's time to revisit the issue of binary distribution. I've just uploaded an installable package for MSYS2 on WIndows. I'd appreciate if people with Windows installs could give it a shot. Basically, [download the package](https://github.com/MRtrix3/mrtrix3/releases/download/3.0_RC3/mingw-w64-x86_64-mrtrix3-3.0_RC3-1-x86_64.pkg.tar.xz), start up a MSYS2 terminal, navigate to wherever you downloaded it, and install it via:
```
pacman -U mingw-w64-x86_64-mrtrix3-3.0_RC3-1-x86_64.pkg.tar.xz
```
Let me know how you go. 

Would also be good to work out how to generate a binary version for macOS, preferably via homebrew or macports. Actually it'll probably need to be both to accommodate users of both systems (since they don't play well with each other, IIRC?)...

**Comment by maxpietsch** [comment]
I've had a look at binary distribution via homebrew. I don't think we'd get into homebrew-core (self-submission and too niche, see [criteria](https://docs.brew.sh/Acceptable-Formulae.html)). AFAIK, this is the only place where homebrew supports [versioned](https://docs.brew.sh/Versions) formulae but those need to be actively used (somewhere in top 3000 packages) or they might get removed. 

I see two alternatives:
1. submit a formula pull request to the [bioinformatics tap](https://github.com/brewsci/homebrew-bio)
2. build our own bottles in our own tap automatically with a modified version of `brew test-bot` on travis: [gist](https://gist.github.com/maelvalais/068af21911c7debc4655cdaa41bbf092). It relies on amazon S3 and Bintray storage. S3 storage is not free (but likely cheap and gives some insights into download stats [see comments here](https://gist.github.com/maelvalais/068af21911c7debc4655cdaa41bbf092#file-travis-yml)) and the script is not officially maintained script.

1 has the advantage that setting everything up should be comparatively easy but we'd be dependent on external maintainers. Formula update PR can be requested via "brew bump-formula-pr --strict foo with --url=... and --sha256=... or --tag=... and --revision=..." ([link](https://github.com/brewsci/homebrew-bio/blob/master/CONTRIBUTING.md))

The complexity of approach 2 is somewhat offputting and possibly fragile but a working example is [here](https://github.com/touist/homebrew-touist). It has the advantage that we could host separate versioned formulae in our own tap as separate formulae (mrtrix3, mrtrix3_3.0, mrtrix3_RC3, ...) and everything is under our control.

@bjeurissen How hard would it be to automate binary releases created via macports?

**Comment by bjeurissen** [comment]
It is relatively straightforward with macports, the downside however is that the generated installer will be massive as it will include a full qt5 installation + dozens of other libraries that a full qt install requires, but that we don't need at all.

I am currently trying to create a lightweight package just by compiling all the dependencies from scratch myself. The complexity and build time of this approach is actually not as bad as I assumed.

I will share the resulting binaries after lunch so you can give them a go in your Mac.

**Comment by bjeurissen** [comment]
@maxpietsch @dchristiaens, give this one a go : https://drive.google.com/file/d/1Rb9D77EUwVdrAdhqiVGQU9TO7ijCD2jX/view?usp=sharing

**Comment by bjeurissen** [comment]
On my system, I can unpack the zip file anywhere I want, add the bin folder to the PATH and it just works.

**Comment by bjeurissen** [comment]
Ok, tested in on my colleagues mac and it does not work... For some reason it still tapped into the macports libraries. Will fix that first and get back with a new version.

**Comment by bjeurissen** [comment]
@maxpietsch @dchristiaens, this version should work (tested on a freshly installed mac of colleague): https://drive.google.com/file/d/1Rb9D77EUwVdrAdhqiVGQU9TO7ijCD2jX/view?usp=sharing

Let me know if it breaks

**Comment by maxpietsch** [comment]
The last version works for me (High Sierra) as far as I can tell. I tested mrview and mrconvert. 

FYI, the shared libraries are:

```
/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1561.40.112)
/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 50.0.0)
/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 158.0.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1452.23.0)
/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1161.10.0)
/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 822.31.0)
/System/Library/Frameworks/CoreText.framework/Versions/A/CoreText (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo (compatibility version 1.2.0, current version 1.5.0)
/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1452.23.0)
/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
/System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/Metal.framework/Versions/A/Metal (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore (compatibility version 1.2.0, current version 1.11.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
/usr/lib/libcups.2.dylib (compatibility version 2.0.0, current version 2.12.0)
/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
@rpath/libQt5Core.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libQt5Gui.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libQt5Network.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libQt5OpenGL.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libQt5PrintSupport.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libQt5Sql.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libQt5Svg.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libQt5Widgets.5.dylib (compatibility version 5.12.0, current version 5.12.3)
@rpath/libmrtrix.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/libtiff.5.dylib (compatibility version 10.0.0, current version 10.0.0)
libcocoaprintersupport.dylib (compatibility version 0.0.0, current version 0.0.0)
libqcocoa.dylib (compatibility version 0.0.0, current version 0.0.0)
libqgenericbearer.dylib (compatibility version 0.0.0, current version 0.0.0)
libqgif.dylib (compatibility version 0.0.0, current version 0.0.0)
libqico.dylib (compatibility version 0.0.0, current version 0.0.0)
libqjpeg.dylib (compatibility version 0.0.0, current version 0.0.0)
libqmacstyle.dylib (compatibility version 0.0.0, current version 0.0.0)
libqminimal.dylib (compatibility version 0.0.0, current version 0.0.0)
libqsqlite.dylib (compatibility version 0.0.0, current version 0.0.0)
libqsvg.dylib (compatibility version 0.0.0, current version 0.0.0)
libqsvgicon.dylib (compatibility version 0.0.0, current version 0.0.0)
libqtuiotouchplugin.dylib (compatibility version 0.0.0, current version 0.0.0)
```
[otool.txt](https://github.com/MRtrix3/mrtrix3/files/3213915/otool.txt)

**Comment by bjeurissen** [comment]
Great! I tested it in Mojave, so we got a version that works on the last two versions. That brings us back to hardware that was released in 2009-2010. Do we need to ensure compatibility with earlier versions as well?

Noticed from your otool output that fftw3 is linked statically while libtiff is linked dynamically. Apparently fftw3's ./configure defaults to static version only. For consistency, should I make sure that both libs are linked statically leaving only qt libs as dynamic libs? Or make sure that all libs are linked dynamically?

**Comment by jdtournier** [comment]
> That brings us back to hardware that was released in 2009-2010. Do we need to ensure compatibility with earlier versions as well?

No, I think that's plenty enough. Good work!

> Noticed from your otool output that fftw3 is linked statically while libtiff is linked dynamically. Apparently fftw3's ./configure defaults to static version only. For consistency, should I make sure that both libs are linked statically leaving only qt libs as dynamic libs? Or make sure that all libs are linked dynamically?

Not fussed either way. Currently the only binary relying on FFTW in `mrdegibbs`, it's definitely going to be a smaller download with static linking. Not that it should make all that much difference to be honest... I'd leave it as-is, at least for now.
