### ISSUE TITLE
mrview argument parsing performace

### ISSUE THREAD

**Issue by maxpietsch** [MRtrix3/mrtrix3#910]
`mrview` in the current tag_0.3.16 branch, `mrview` opens the first and then loops through all images until it reaches the last one if multiple images are supplied via command line:

For instance images im0.mif im1.mif im2.mif, using `mrview im?.mif`, mrview flashes up im0.mif and im1.mif to then show im2.mif.

I guess that this is not intended?

**Comment by jdtournier** [comment]
Actually, that is (unfortunately) the expected behaviour now, as of [this merge](https://github.com/MRtrix3/mrtrix3/pull/884). As mentioned there, to be able to treat the `-load` option in the same way as providing the image as a regular argument, so that a command like this:

    mrview a.mif -interp 0 b.mif -interp 0

behaves as expected, with the same result as:

    mrview -load a.mif -interp 0 -load b.mif -interp 0

This does mean that listing the images on the command line now has the same effect as opening these images one after the other via the File->Open dialog. 

I had mentioned at the time that this would change behaviour, in that the last image on the command-line would now be the one displayed, rather than the first as was the case before. But the only way around this is to treat images provided as regular arguments differently from those opened via `-load`, by loading them before any command-line options are actually processed, but this leads to the unexpected behaviour that prompted this change in the first place...

Not saying I know what the right thing to do is here, but the current behaviour is probably the most sane, even if it is a bit awkward when just listing a few images on the command-line. Open to suggestions as to potential ways around it...

**Comment by maxpietsch** [comment]
Not a big deal if the images reside locally but it can be a bit annoying when browsing a large network repository with lots of large images. 

I think the easiest thing to do might be to parse all options sequentially but don't update the GUI if there are more images to load and no screenshot option requested. For that, we just would need to have a check if an image in the argument list is intended to be rendered and adjust the existing image load actions to have an option to not load and render the images but only add them to the image queue.

But, when using `mrview` interactively, I think it makes sense to expect to see the first image in the argument list, not the last. Ideally, we could associate options with images and store them in the image class and apply them when they are looked at. That way, we could parse all options, apply them but only show the first image in the queue with its options - if there is no screenshot option set. However, this gets complicated or ambiguous when tool options or global options are also supplied.

Not sure what is best or whether it is worth the hassle.

**Comment by jdtournier** [comment]
So just a bit of background here: the problem with delaying any updates is that a fair bit of work happens in the draw function itself. That's when the texture is created or updated, and the intensity range set if it wasn't already. It makes it quite tricky to guarantee correct operation if those updates are not performed in the order expected, which is why you have to update the display after every option currently.

So I completely agree that the current situation is not ideal. There's two options that I can see to deal with this if we think it's enough of a problem. One is to refactor the code so that any updates to data (not screen) that would normally happen in the draw call are now performed outside of it. This includes things like intensity reset and view reset that would normally just set certain variables to NaN and leave it to the draw call to update everything as required.  This also probably means loading image data into textures at load time rather than display time, which probably won't help to ensure snappy performance over network filesystems. The main issue really is the intensity reset: if that needs to be set properly, it requires a read through at least a slice of data (assuming we're locked to axes), at which point you might as well update the texture while you're at it. Even if we don't update the display after that option, we still need to ensure that the intensity scaling is correct after it had been invoked, otherwise a call like this:

    mrview a.mif -autoscale -volume 2 

will show the image autoscaled to the third volume rather than the expected first volume. I can't think of many other options that would introduce too many issues like this, but maybe some of the tools might also have similar problems.

The second option is to somehow make a clear separation between what happens when you list images on the command line, and what might happen _subsequently_ when invoking options (this is basically exactly what happened before this issue came up). One potential way to do this is to force options to appear _after_ the arguments, and revert to forcing the use of `-load` when loading images subsequently. We'd need to document very clearly that images listed as-is on the command line will be treated differently and are designed for routine display, while any _subsequent_ options are essentially equivalent to performing the corresponding GUI action. I'm not sure that would necessarily be sufficiently clear to users, but it would at least match exactly what's actually taking place, and wouldn't require a great deal of effort to implement (it's basically just reverting some of the changes implemented recently - although I think the bulk of them are OK). 

I have to say, having thought about this a bit more, I'm starting to favour the second option... Any other opinions...?

**Comment by maxpietsch** [comment]
Agreed, separating `-load` and images provided as arguments would be the easiest solution. 

>  images listed as-is on the command line will be treated differently and are designed for routine display, while any _subsequent_ options are essentially equivalent to performing the corresponding GUI action

Just to clarify, _all_ options are applied after the images that are provided as arguments are parsed, not just the ones following the images?

So `mrview a.mif -autoscale` is identical to `mrview -autoscale a.mif` but 
`mrview -load a.mif -autoscale` is not the same as `mrview  -autoscale -load a.mif`.

**Comment by thijsdhollander** [comment]
I agree with separating arguments and `-load` options' behaviour, so we can indeed accommodate both functionalities.  It does make the interface potentially slightly less intuitive to users ("Why does an image as an argument behave differently as when I provide it via `-load`?" will probably pop up a few times on the forum after we introduce this (again)), but as always the question is if that price is worth the value we get in return.  I *personally* feel having both possibilities provides enough value to justify it.

Max, as Donald mentioned somewhere we could:

> force options to appear after the arguments, and revert to forcing the use of -load when loading images subsequently

That would already do away with some potential ambiguities that would otherwise arise.

**Comment by jdtournier** [comment]
@thijsdhollander: exactly my thoughts. I'm almost thinking it might be worth including an overt separator just for that, something like this:

    mrview a.mif b.mif -- -fov 120 -volume 3 -autoscale

Similar to what `git` sometimes uses, and also `startx` (for those that can remember that far...). 

But I admit that might be pushing it a bit further than strictly necessary...

**Comment by thijsdhollander** [comment]
Hmm, I'd never seen/noticed that before (such a separator in any context).  I do like the idea of it, but as you say maybe it's pushing it too far... although I certainly wouldn't be against it!

**Comment by maxpietsch** [comment]
> force options to appear after the arguments, and revert to forcing the use of -load when loading images subsequently

oops, did not see that -.-

**Comment by maxpietsch** [comment]
Going through a bunch of compressed images stored on a network mounted drive reminded me of this issue... 

> wouldn't require a great deal of effort to implement (it's basically just reverting some of the changes implemented recently - although I think the bulk of them are OK).

I've had a look at 21bdcd10b0f8b827ebc37876579d09bb149a599e and I guess the change needed has to do with [this](https://github.com/MRtrix3/mrtrix3/commit/21bdcd10b0f8b827ebc37876579d09bb149a599e#diff-03ea9c2ac10df5d9f1a4d07072926716R1937) and [this](https://github.com/MRtrix3/mrtrix3/commit/21bdcd10b0f8b827ebc37876579d09bb149a599e#diff-03ea9c2ac10df5d9f1a4d07072926716L1923) block. I tried to modify it but then [this](https://xkcd.com/292/) happened. Any help welcome ;)

**Comment by jdtournier** [comment]
Not sure what you did here, but it's going to be a bit fiddly to fix this up properly. Basically, we want to detect all genuine arguments, make sure they appear before all other options (except from the standard ones like `-help`, `-debug`, etc), load all these images without any redraw, and set the first one listed as current, _then_ proceed to parsing the remaining command-line options. Most of that is reverting to previous functionality, but there were also changes to the way the updates were invoked (previously via `qApp->processEvents()`, now via a `QTimer`) that will muddy the water. The main issue as I see it is to enforce valid orderings (i.e. all arguments before any non-standard options): that will involve some fairly deep interactions between the main _MRtrix3_ parsing backend and `mrview`'s re-implementation of it...

**Comment by jdtournier** [comment]
pull request in #924
