### ISSUE TITLE
dwi2mask assertion failed

### ISSUE THREAD

**Issue by marjolein15** [MRtrix3/mrtrix3#931]
I had the following issue when trying to convert a DWI image (in nii.gz) to a whole brain mask with dwi2mask:

Assertion failed: ((i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))), function Block, file /usr/local/Cellar/eigen/3.2.2/include/eigen3/Eigen/src/Core/Block.h, line 118.
Abort trap: 6

Any help appreciated!

**Comment by jdtournier** [comment]
Nice to see you're running with asserts enabled! This looks like an out-of-bounds error, but it's going to be difficult to figure out precisely what happened without a bit more information. However, my first thought is that your Eigen installation is very outdated, and maybe that's the issue here. The current stable versions are 3.2.10 and 3.3.3. I'm assuming you're running on macOS? Any chance you could try to update Eigen, see if that helps? Note that you might need to update _MRtrix3_ too, at least as far as #820, to avoid issues introduced by Eigen 3.3...

If that doesn't fix it, please post the full command-line you used, we'll investigate.

**Comment by maxpietsch** [comment]
You can upgrade eigen3 with 

```
brew upgrade eigen3
```

Assuming you installed MRtrix manually you should be able to compile it with the new version of eigen3 with 
```
cd ~/mrtrix3
./configure
./build
```

**Comment by marjolein15** [comment]
Thanks, this solved the problem!
