### ISSUE TITLE
Registration symmetry not obvious from mrregister documentation.

### ISSUE THREAD

**Issue by bjeurissen** [MRtrix3/mrtrix3#942]
Assuming ``mrregister`` is now symmetric across all registration types, should we not rename the input parameters from ``moving`` and ``template`` to ``image1`` and ``image2``?

Also it might help to replace some occurrences of ''registration'' by ''symmetric registration''.

Currently, it reads as if only the nonlinear part is symmetric.

**Comment by maxpietsch** [comment]
Yes, everything is symmetric in the linear and nonlinear code. 

The input images are called `image1` and `image2` with description text `(moving)` and `(template)` because the output transformations (`-rigid`) and (`-affine`)  are directed and this might help to get the direction right. 

We could just change the synopsis to 
`SYNOPSIS = "Register two images together using a symmetric rigid, affine or non-linear transformation model";`
to make clear that `mrregister` is symmetric for all transformation models.

**Comment by bjeurissen** [comment]
I think changing the synopsis would indeed already make things clear.
