### ISSUE TITLE
5ttgen fsl error "T1_preBET.nii.gz": No such file or directory

### ISSUE THREAD

**Issue by isAarya** [MRtrix3/mrtrix3#975]
Hi, 
I am using 5ttgen fsl with my input T1 weighted image. 

This is my input command:
`5ttgen fsl -nocrop -mask ROI.mif  T12diff_space.nii.gz  T15tt.mif`

And I get the following error while running it,

```
5ttgen: Note that this script makes use of commands / algorithms that have relevant articles for citation; INCLUDING FROM EXTERNAL SOFTWARE PACKAGES. Please consult the help page (-help option) for more information.
5ttgen: 
5ttgen: Generated temporary directory: /tmp/5ttgen-tmp-YG37AF/
Command: mrconvert T12diff_space.nii.gz /tmp/5ttgen-tmp-YG37AF/input.mif -stride +1,+2,+3  -quiet
Command: mrconvert ROI.mif /tmp/5ttgen-tmp-YG37AF/mask.mif -datatype bit -stride +1,+2,+3  -quiet
5ttgen: Changing to temporary directory (/tmp/5ttgen-tmp-YG37AF/)
Command: mrconvert input.mif T1.nii  -quiet
Command: mrcalc input.mif mask.mif -mult T1_masked.nii  -quiet
Command: fast T1_masked.nii.gz
Command: run_first_all -s L_Accu,R_Accu,L_Caud,R_Caud,L_Pall,R_Pall,L_Puta,R_Puta,L_Thal,R_Thal -i T1.nii -o first
8108
Command: meshconvert first-L_Accu_first.vtk L_Accu.vtk -transform_first2real input.mif  -quiet
Command: mesh2pve L_Accu.vtk T1_preBET.nii.gz mesh2pve_L_Accu.nii  -quiet
mesh2pve: [ERROR] cannot access file "T1_preBET.nii.gz": No such file or directory
mesh2pve: [ERROR] error opening image "T1_preBET.nii.gz"
5ttgen: [ERROR] Command failed: mesh2pve L_Accu.vtk T1_preBET.nii.gz mesh2pve_L_Accu.nii  -quiet
5ttgen: Changing back to original directory (/5tt_tissue)
5ttgen: Deleting temporary directory /tmp/5ttgen-tmp-YG37AF/
```

It is complaining that a certain file "T1_preBET.nii.gz" does not exist. Where should this file be located ?

Can someone tell me how can I fix this.

I am using mrtrix3 on ubuntu 16 linux workstation.

Kind regards

**Comment by Lestropie** [comment]
Hi @isAarya,

It looks like the specific version of code you currently have checked out contains an error; it's probably from around the time when I first implemented the `-mask` and `-premasked` options for `5ttgen`. It's trying to use the image that is input to the FSL `bet` command (`T1_preBET.nii.gz`) as a template, but because you've used the `-mask` option, that image doesn't exist.

However I'm confident that the most up-to-date *MRtrix3* code does not contain this error. You can see on [this line](https://github.com/MRtrix3/mrtrix3/blob/master/lib/mrtrix3/_5ttgen/fsl.py#L178), the script accesses whichever image was used as the input to the FSL `fast` command to use for this template. So an update to the latest version should fix the issue.

Thanks
Rob
